import type { Question } from "./types";

export const questionsSciences: Omit<Question, "id">[] = [
  // ===== DIFFICULTE 1 — TRIVIAL (15s) =====
  {
    difficulty: 1, category: "corps-humain", type: "text", time_limit: 15,
    text: "Combien de poumons possède un être humain ?",
    choices: ["1", "2", "3", "4"],
    correct_index: 1,
    explanation: "L'être humain possède deux poumons, situés dans la cage thoracique de part et d'autre du cœur.",
    svg_config: null,
  },
  {
    difficulty: 1, category: "astronomie", type: "text", time_limit: 15,
    text: "Quel astre est au centre du système solaire ?",
    choices: ["La Lune", "La Terre", "Le Soleil", "Jupiter"],
    correct_index: 2,
    explanation: "Le Soleil, une étoile, est au centre du système solaire et toutes les planètes gravitent autour de lui.",
    svg_config: null,
  },
  {
    difficulty: 1, category: "physique", type: "text", time_limit: 15,
    text: "À quelle température l'eau bout-elle au niveau de la mer ?",
    choices: ["50 °C", "80 °C", "100 °C", "150 °C"],
    correct_index: 2,
    explanation: "Au niveau de la mer, sous une pression atmosphérique normale, l'eau bout à 100 °C.",
    svg_config: null,
  },
  {
    difficulty: 1, category: "animaux", type: "text", time_limit: 15,
    text: "Quel est le plus grand animal vivant sur Terre ?",
    choices: ["L'éléphant d'Afrique", "La baleine bleue", "Le requin-baleine", "Le cachalot"],
    correct_index: 1,
    explanation: "La baleine bleue est le plus grand animal connu, pouvant dépasser 30 mètres de long.",
    svg_config: null,
  },
  {
    difficulty: 1, category: "botanique", type: "text", time_limit: 15,
    text: "Que produisent les plantes vertes grâce à la lumière du Soleil ?",
    choices: ["De l'oxygène", "Du méthane", "De l'azote", "De l'hélium"],
    correct_index: 0,
    explanation: "Par la photosynthèse, les plantes vertes produisent de l'oxygène à partir du dioxyde de carbone et de l'eau.",
    svg_config: null,
  },
  {
    difficulty: 1, category: "chimie", type: "text", time_limit: 15,
    text: "Quelle est la formule chimique de l'eau ?",
    choices: ["CO2", "H2O", "O2", "NaCl"],
    correct_index: 1,
    explanation: "L'eau est composée de deux atomes d'hydrogène et d'un atome d'oxygène, d'où la formule H2O.",
    svg_config: null,
  },
  {
    difficulty: 1, category: "astronomie", type: "text", time_limit: 15,
    text: "Quel est le satellite naturel de la Terre ?",
    choices: ["Mars", "La Lune", "Vénus", "Titan"],
    correct_index: 1,
    explanation: "La Lune est l'unique satellite naturel de la Terre, autour de laquelle elle tourne en environ 27 jours.",
    svg_config: null,
  },
  {
    difficulty: 1, category: "biologie", type: "text", time_limit: 15,
    text: "De quoi a besoin un être humain pour respirer ?",
    choices: ["D'azote", "D'oxygène", "De dioxyde de carbone", "D'hélium"],
    correct_index: 1,
    explanation: "L'organisme humain a besoin d'oxygène, capté par les poumons puis transporté par le sang vers les cellules.",
    svg_config: null,
  },
  {
    difficulty: 1, category: "corps-humain", type: "text", time_limit: 15,
    text: "Quel organe pompe le sang dans le corps humain ?",
    choices: ["Le foie", "Les reins", "Le cœur", "L'estomac"],
    correct_index: 2,
    explanation: "Le cœur est un muscle qui pompe le sang en continu pour le faire circuler dans tout l'organisme.",
    svg_config: null,
  },
  {
    difficulty: 1, category: "animaux", type: "text", time_limit: 15,
    text: "Combien de pattes possède une araignée ?",
    choices: ["6", "8", "10", "12"],
    correct_index: 1,
    explanation: "Les araignées sont des arachnides et possèdent huit pattes, contrairement aux insectes qui en ont six.",
    svg_config: null,
  },

  // ===== DIFFICULTE 2 — TRES FACILE (15s) =====
  {
    difficulty: 2, category: "astronomie", type: "text", time_limit: 15,
    text: "Quelle planète est surnommée la « planète rouge » ?",
    choices: ["Vénus", "Mars", "Jupiter", "Mercure"],
    correct_index: 1,
    explanation: "Mars apparaît rougeâtre à cause de l'oxyde de fer (rouille) présent à sa surface.",
    svg_config: null,
  },
  {
    difficulty: 2, category: "chimie", type: "text", time_limit: 15,
    text: "Quel gaz les êtres humains rejettent-ils en expirant ?",
    choices: ["De l'oxygène", "Du dioxyde de carbone", "De l'hydrogène", "De l'ozone"],
    correct_index: 1,
    explanation: "En respirant, l'organisme consomme de l'oxygène et rejette du dioxyde de carbone (CO2).",
    svg_config: null,
  },
  {
    difficulty: 2, category: "corps-humain", type: "text", time_limit: 15,
    text: "Combien d'os possède approximativement le squelette d'un adulte ?",
    choices: ["106", "206", "306", "406"],
    correct_index: 1,
    explanation: "Le squelette d'un adulte compte environ 206 os ; un nouveau-né en a davantage car certains fusionnent en grandissant.",
    svg_config: null,
  },
  {
    difficulty: 2, category: "animaux", type: "text", time_limit: 15,
    text: "Quel animal est le plus rapide à la course sur terre ?",
    choices: ["Le lion", "Le guépard", "Le cheval", "Le lévrier"],
    correct_index: 1,
    explanation: "Le guépard est le mammifère terrestre le plus rapide, capable d'atteindre de très hautes vitesses sur de courtes distances.",
    svg_config: null,
  },
  {
    difficulty: 2, category: "physique", type: "text", time_limit: 15,
    text: "Quelle force fait tomber les objets vers le sol ?",
    choices: ["Le magnétisme", "La gravité", "L'électricité", "La friction"],
    correct_index: 1,
    explanation: "La gravité (ou pesanteur) attire les objets vers le centre de la Terre, ce qui les fait tomber.",
    svg_config: null,
  },
  {
    difficulty: 2, category: "botanique", type: "text", time_limit: 15,
    text: "Quelle partie de la plante absorbe l'eau dans le sol ?",
    choices: ["Les feuilles", "Les racines", "Les fleurs", "Les fruits"],
    correct_index: 1,
    explanation: "Les racines ancrent la plante et absorbent l'eau ainsi que les sels minéraux présents dans le sol.",
    svg_config: null,
  },
  {
    difficulty: 2, category: "geologie", type: "text", time_limit: 15,
    text: "Comment appelle-t-on la roche en fusion qui sort d'un volcan ?",
    choices: ["Le magma sous terre uniquement", "La lave", "Le granite", "Le calcaire"],
    correct_index: 1,
    explanation: "Une fois sortie à la surface lors d'une éruption, la roche en fusion s'appelle la lave (elle se nomme magma sous terre).",
    svg_config: null,
  },
  {
    difficulty: 2, category: "biologie", type: "text", time_limit: 15,
    text: "Quel est l'unité de base de tous les êtres vivants ?",
    choices: ["L'atome", "La cellule", "La molécule", "Le tissu"],
    correct_index: 1,
    explanation: "La cellule est la plus petite unité vivante ; tous les organismes en sont constitués.",
    svg_config: null,
  },
  {
    difficulty: 2, category: "astronomie", type: "text", time_limit: 15,
    text: "Quelle est la plus grande planète du système solaire ?",
    choices: ["Saturne", "Jupiter", "Neptune", "La Terre"],
    correct_index: 1,
    explanation: "Jupiter est la plus grande planète du système solaire, une géante gazeuse bien plus massive que toutes les autres réunies.",
    svg_config: null,
  },
  {
    difficulty: 2, category: "animaux", type: "text", time_limit: 15,
    text: "Quel animal est un mammifère marin et non un poisson ?",
    choices: ["Le requin", "Le dauphin", "Le thon", "La sardine"],
    correct_index: 1,
    explanation: "Le dauphin est un mammifère : il respire de l'air avec des poumons et allaite ses petits, contrairement aux poissons.",
    svg_config: null,
  },

  // ===== DIFFICULTE 3 — FACILE (15s) =====
  {
    difficulty: 3, category: "chimie", type: "text", time_limit: 15,
    text: "Quel est le symbole chimique de l'oxygène ?",
    choices: ["Or", "O", "Ox", "Os"],
    correct_index: 1,
    explanation: "Le symbole chimique de l'oxygène est O, d'après le latin « oxygenium ».",
    svg_config: null,
  },
  {
    difficulty: 3, category: "corps-humain", type: "text", time_limit: 15,
    text: "Quel organe filtre le sang et produit l'urine ?",
    choices: ["Le foie", "Les reins", "La rate", "Le pancréas"],
    correct_index: 1,
    explanation: "Les reins filtrent le sang pour éliminer les déchets, produisant l'urine qui est ensuite évacuée.",
    svg_config: null,
  },
  {
    difficulty: 3, category: "astronomie", type: "text", time_limit: 15,
    text: "Quelle planète est la plus proche du Soleil ?",
    choices: ["Vénus", "Mercure", "Mars", "La Terre"],
    correct_index: 1,
    explanation: "Mercure est la planète la plus proche du Soleil, et aussi la plus petite du système solaire.",
    svg_config: null,
  },
  {
    difficulty: 3, category: "physique", type: "text", time_limit: 15,
    text: "Quelle est l'unité de mesure de la force dans le Système international ?",
    choices: ["Le joule", "Le watt", "Le newton", "Le pascal"],
    correct_index: 2,
    explanation: "La force se mesure en newtons (N), du nom du physicien Isaac Newton.",
    svg_config: null,
  },
  {
    difficulty: 3, category: "biologie", type: "text", time_limit: 15,
    text: "Comment appelle-t-on la transformation d'une chenille en papillon ?",
    choices: ["La mutation", "La métamorphose", "La mitose", "La pollinisation"],
    correct_index: 1,
    explanation: "La métamorphose désigne la transformation profonde de la chenille en papillon, en passant par le stade de chrysalide.",
    svg_config: null,
  },
  {
    difficulty: 3, category: "ecologie", type: "text", time_limit: 15,
    text: "Quel gaz est principalement responsable de l'effet de serre additionnel d'origine humaine ?",
    choices: ["L'oxygène", "Le dioxyde de carbone", "L'azote", "L'argon"],
    correct_index: 1,
    explanation: "Le dioxyde de carbone (CO2), émis surtout par la combustion d'énergies fossiles, est le principal gaz à effet de serre d'origine humaine.",
    svg_config: null,
  },
  {
    difficulty: 3, category: "geologie", type: "text", time_limit: 15,
    text: "Quelle est la planète tellurique sur laquelle nous vivons ?",
    choices: ["Mars", "La Terre", "Vénus", "Mercure"],
    correct_index: 1,
    explanation: "La Terre est une planète tellurique (rocheuse), la seule connue à abriter la vie.",
    svg_config: null,
  },
  {
    difficulty: 3, category: "animaux", type: "text", time_limit: 15,
    text: "Quel groupe d'animaux a le sang à température variable (« sang froid ») ?",
    choices: ["Les mammifères", "Les oiseaux", "Les reptiles", "Tous les précédents"],
    correct_index: 2,
    explanation: "Les reptiles sont ectothermes : leur température corporelle dépend du milieu, contrairement aux mammifères et oiseaux.",
    svg_config: null,
  },
  {
    difficulty: 3, category: "botanique", type: "text", time_limit: 15,
    text: "Quel pigment donne leur couleur verte aux feuilles ?",
    choices: ["La mélanine", "La chlorophylle", "L'hémoglobine", "Le carotène"],
    correct_index: 1,
    explanation: "La chlorophylle, pigment vert, capte la lumière du Soleil et permet la photosynthèse.",
    svg_config: null,
  },
  {
    difficulty: 3, category: "physique", type: "text", time_limit: 15,
    text: "Quel état de la matière a une forme propre et un volume propre ?",
    choices: ["Le gaz", "Le liquide", "Le solide", "Le plasma"],
    correct_index: 2,
    explanation: "Un solide possède à la fois une forme et un volume propres, contrairement au liquide (volume fixe, forme variable) et au gaz.",
    svg_config: null,
  },

  // ===== DIFFICULTE 4 — MOYEN-FACILE (20s) =====
  {
    difficulty: 4, category: "chimie", type: "text", time_limit: 20,
    text: "Combien d'électrons un atome neutre d'hydrogène possède-t-il ?",
    choices: ["0", "1", "2", "3"],
    correct_index: 1,
    explanation: "L'hydrogène a un numéro atomique de 1 : un atome neutre possède donc un proton et un électron.",
    svg_config: null,
  },
  {
    difficulty: 4, category: "corps-humain", type: "text", time_limit: 20,
    text: "Quel est le groupe sanguin dit « donneur universel » ?",
    choices: ["AB+", "O négatif", "A+", "B négatif"],
    correct_index: 1,
    explanation: "Le groupe O négatif ne porte ni antigènes A, B, ni rhésus D, ce qui en fait le donneur universel de globules rouges.",
    svg_config: null,
  },
  {
    difficulty: 4, category: "astronomie", type: "text", time_limit: 20,
    text: "Combien de temps met environ la lumière du Soleil pour atteindre la Terre ?",
    choices: ["8 secondes", "8 minutes", "8 heures", "8 jours"],
    correct_index: 1,
    explanation: "La lumière met environ 8 minutes (8 min 20 s) pour parcourir les 150 millions de kilomètres qui séparent le Soleil de la Terre.",
    svg_config: null,
  },
  {
    difficulty: 4, category: "physique", type: "text", time_limit: 20,
    text: "Quelle grandeur le voltmètre mesure-t-il ?",
    choices: ["L'intensité", "La tension électrique", "La résistance", "La puissance"],
    correct_index: 1,
    explanation: "Le voltmètre mesure la tension électrique, exprimée en volts, entre deux points d'un circuit.",
    svg_config: null,
  },
  {
    difficulty: 4, category: "biologie", type: "text", time_limit: 20,
    text: "Comment appelle-t-on la division d'une cellule en deux cellules filles identiques ?",
    choices: ["La méiose", "La mitose", "La fécondation", "La fermentation"],
    correct_index: 1,
    explanation: "La mitose est la division cellulaire produisant deux cellules filles génétiquement identiques à la cellule mère.",
    svg_config: null,
  },
  {
    difficulty: 4, category: "geologie", type: "text", time_limit: 20,
    text: "Quelle échelle mesure traditionnellement la magnitude des séismes ?",
    choices: ["L'échelle de Beaufort", "L'échelle de Richter", "L'échelle de Mohs", "L'échelle Celsius"],
    correct_index: 1,
    explanation: "L'échelle de Richter (et ses variantes) mesure la magnitude, c'est-à-dire l'énergie libérée par un séisme.",
    svg_config: null,
  },
  {
    difficulty: 4, category: "animaux", type: "text", time_limit: 20,
    text: "Quel est le seul mammifère capable d'un vol battu véritable ?",
    choices: ["L'écureuil volant", "La chauve-souris", "Le colibri", "Le ptérodactyle"],
    correct_index: 1,
    explanation: "La chauve-souris est le seul mammifère qui vole réellement ; l'écureuil volant ne fait que planer.",
    svg_config: null,
  },
  {
    difficulty: 4, category: "chimie", type: "text", time_limit: 20,
    text: "Quel est le pH d'une solution neutre à 25 °C ?",
    choices: ["0", "7", "10", "14"],
    correct_index: 1,
    explanation: "À 25 °C, une solution neutre comme l'eau pure a un pH de 7 ; en dessous elle est acide, au-dessus elle est basique.",
    svg_config: null,
  },
  {
    difficulty: 4, category: "botanique", type: "text", time_limit: 20,
    text: "Comment appelle-t-on le transfert du pollen permettant la reproduction des plantes à fleurs ?",
    choices: ["La germination", "La pollinisation", "La photosynthèse", "La transpiration"],
    correct_index: 1,
    explanation: "La pollinisation est le transport du pollen vers le pistil, étape clé de la reproduction des plantes à fleurs.",
    svg_config: null,
  },
  {
    difficulty: 4, category: "ecologie", type: "text", time_limit: 20,
    text: "Comment qualifie-t-on un animal qui se nourrit à la fois de végétaux et d'autres animaux ?",
    choices: ["Herbivore", "Carnivore", "Omnivore", "Détritivore"],
    correct_index: 2,
    explanation: "Un omnivore consomme aussi bien des végétaux que des animaux ; c'est le cas par exemple de l'être humain ou de l'ours.",
    svg_config: null,
  },

  // ===== DIFFICULTE 5 — MOYEN (20s) =====
  {
    difficulty: 5, category: "physique", type: "text", time_limit: 20,
    text: "Quelle est la vitesse de la lumière dans le vide, en valeur arrondie ?",
    choices: ["300 km/s", "3 000 km/s", "300 000 km/s", "30 000 km/s"],
    correct_index: 2,
    explanation: "La lumière se propage à environ 300 000 km/s dans le vide (précisément 299 792 km/s).",
    svg_config: null,
  },
  {
    difficulty: 5, category: "chimie", type: "text", time_limit: 20,
    text: "Quel élément chimique a pour symbole « Na » ?",
    choices: ["Le nickel", "L'azote", "Le sodium", "Le néon"],
    correct_index: 2,
    explanation: "Le symbole Na vient du latin « natrium » et désigne le sodium.",
    svg_config: null,
  },
  {
    difficulty: 5, category: "corps-humain", type: "text", time_limit: 20,
    text: "Quel est l'os le plus long du corps humain ?",
    choices: ["Le tibia", "Le fémur", "L'humérus", "Le radius"],
    correct_index: 1,
    explanation: "Le fémur, os de la cuisse, est l'os le plus long et l'un des plus solides du corps humain.",
    svg_config: null,
  },
  {
    difficulty: 5, category: "astronomie", type: "text", time_limit: 20,
    text: "Quelle galaxie contient notre système solaire ?",
    choices: ["Andromède", "La Voie lactée", "Le Triangle", "Le Grand Nuage de Magellan"],
    correct_index: 1,
    explanation: "Notre système solaire se situe dans la Voie lactée, une galaxie spirale comptant des centaines de milliards d'étoiles.",
    svg_config: null,
  },
  {
    difficulty: 5, category: "biologie", type: "text", time_limit: 20,
    text: "Quelle molécule porte l'information génétique dans nos cellules ?",
    choices: ["L'ATP", "L'ADN", "Le glucose", "Le collagène"],
    correct_index: 1,
    explanation: "L'ADN (acide désoxyribonucléique) contient l'information génétique sous forme de gènes.",
    svg_config: null,
  },
  {
    difficulty: 5, category: "geologie", type: "text", time_limit: 20,
    text: "Quel est le minéral le plus dur, qui vaut 10 sur l'échelle de Mohs ?",
    choices: ["Le quartz", "Le diamant", "Le talc", "Le corindon"],
    correct_index: 1,
    explanation: "Le diamant, constitué de carbone, est le minéral naturel le plus dur et occupe la valeur maximale (10) de l'échelle de Mohs.",
    svg_config: null,
  },
  {
    difficulty: 5, category: "animaux", type: "text", time_limit: 20,
    text: "Combien de cœurs possède une pieuvre ?",
    choices: ["1", "2", "3", "5"],
    correct_index: 2,
    explanation: "La pieuvre possède trois cœurs : deux pompent le sang vers les branchies et un vers le reste du corps.",
    svg_config: null,
  },
  {
    difficulty: 5, category: "physique", type: "text", time_limit: 20,
    text: "Comment appelle-t-on le changement direct d'un solide en gaz, sans passer par l'état liquide ?",
    choices: ["La fusion", "L'évaporation", "La sublimation", "La condensation"],
    correct_index: 2,
    explanation: "La sublimation est le passage direct de l'état solide à l'état gazeux, comme pour la neige carbonique (glace de CO2).",
    svg_config: null,
  },
  {
    difficulty: 5, category: "chimie", type: "text", time_limit: 20,
    text: "Quel gaz constitue environ 78 % de l'air que nous respirons ?",
    choices: ["L'oxygène", "Le dioxyde de carbone", "L'azote", "L'argon"],
    correct_index: 2,
    explanation: "L'air est composé d'environ 78 % d'azote et 21 % d'oxygène, le reste étant surtout de l'argon et du CO2.",
    svg_config: null,
  },
  {
    difficulty: 5, category: "botanique", type: "text", time_limit: 20,
    text: "Comment appelle-t-on les arbres qui conservent leurs feuilles toute l'année ?",
    choices: ["Caducs", "Persistants", "Annuels", "Vivaces"],
    correct_index: 1,
    explanation: "Les arbres à feuillage persistant (comme les conifères) gardent leurs feuilles toute l'année, contrairement aux arbres à feuillage caduc.",
    svg_config: null,
  },

  // ===== DIFFICULTE 6 — MOYEN-DIFFICILE (20s) =====
  {
    difficulty: 6, category: "chimie", type: "text", time_limit: 20,
    text: "Combien d'éléments compte approximativement le tableau périodique aujourd'hui ?",
    choices: ["88", "98", "118", "150"],
    correct_index: 2,
    explanation: "Le tableau périodique comprend 118 éléments officiellement reconnus, de l'hydrogène (1) à l'oganesson (118).",
    svg_config: null,
  },
  {
    difficulty: 6, category: "biologie", type: "text", time_limit: 20,
    text: "Dans quel organite de la cellule se déroule principalement la respiration cellulaire ?",
    choices: ["Le noyau", "La mitochondrie", "Le ribosome", "L'appareil de Golgi"],
    correct_index: 1,
    explanation: "La mitochondrie est le siège de la respiration cellulaire et produit l'énergie (ATP) de la cellule.",
    svg_config: null,
  },
  {
    difficulty: 6, category: "astronomie", type: "text", time_limit: 20,
    text: "Quelle planète possède les anneaux les plus visibles et spectaculaires ?",
    choices: ["Jupiter", "Saturne", "Uranus", "Neptune"],
    correct_index: 1,
    explanation: "Saturne est célèbre pour ses anneaux spectaculaires, composés de glace et de roches ; les autres géantes ont des anneaux ténus.",
    svg_config: null,
  },
  {
    difficulty: 6, category: "physique", type: "text", time_limit: 20,
    text: "Quelle est l'unité de mesure de l'énergie dans le Système international ?",
    choices: ["Le watt", "Le joule", "Le newton", "Le volt"],
    correct_index: 1,
    explanation: "L'énergie se mesure en joules (J) dans le Système international ; le watt mesure une puissance (joules par seconde).",
    svg_config: null,
  },
  {
    difficulty: 6, category: "corps-humain", type: "text", time_limit: 20,
    text: "Quel est le plus grand organe du corps humain ?",
    choices: ["Le foie", "Le cerveau", "La peau", "Les poumons"],
    correct_index: 2,
    explanation: "La peau est le plus grand organe du corps humain par sa surface et sa masse.",
    svg_config: null,
  },
  {
    difficulty: 6, category: "geologie", type: "text", time_limit: 20,
    text: "Quelle est la couche la plus externe de la Terre, sur laquelle nous vivons ?",
    choices: ["Le manteau", "Le noyau", "La croûte terrestre", "L'asthénosphère"],
    correct_index: 2,
    explanation: "La croûte terrestre est la couche solide la plus externe de la Terre, surmontant le manteau.",
    svg_config: null,
  },
  {
    difficulty: 6, category: "ecologie", type: "text", time_limit: 20,
    text: "Comment appelle-t-on l'ensemble des êtres vivants et de leur milieu en interaction ?",
    choices: ["Une population", "Un écosystème", "Une espèce", "Une biosphère"],
    correct_index: 1,
    explanation: "Un écosystème regroupe les êtres vivants (biocénose) et leur milieu physique (biotope) en interaction.",
    svg_config: null,
  },
  {
    difficulty: 6, category: "chimie", type: "text", time_limit: 20,
    text: "Quel métal est liquide à température ambiante ?",
    choices: ["Le plomb", "Le mercure", "L'étain", "L'aluminium"],
    correct_index: 1,
    explanation: "Le mercure est le seul métal liquide à température ambiante, ce qui lui valait d'être utilisé dans les thermomètres.",
    svg_config: null,
  },
  {
    difficulty: 6, category: "animaux", type: "text", time_limit: 20,
    text: "À quelle classe d'animaux appartiennent les dauphins, baleines et marsouins ?",
    choices: ["Les poissons", "Les mammifères", "Les amphibiens", "Les reptiles"],
    correct_index: 1,
    explanation: "Dauphins, baleines et marsouins sont des cétacés, un ordre de mammifères marins.",
    svg_config: null,
  },
  {
    difficulty: 6, category: "biologie", type: "text", time_limit: 20,
    text: "Quel scientifique a formulé la théorie de l'évolution par sélection naturelle ?",
    choices: ["Louis Pasteur", "Charles Darwin", "Gregor Mendel", "Carl von Linné"],
    correct_index: 1,
    explanation: "Charles Darwin a exposé la théorie de l'évolution par sélection naturelle dans « L'Origine des espèces » (1859).",
    svg_config: null,
  },

  // ===== DIFFICULTE 7 — DIFFICILE (25s) =====
  {
    difficulty: 7, category: "physique", type: "text", time_limit: 25,
    text: "Quel physicien a énoncé la célèbre équation E = mc² ?",
    choices: ["Isaac Newton", "Albert Einstein", "Niels Bohr", "Max Planck"],
    correct_index: 1,
    explanation: "Albert Einstein a établi E = mc² dans le cadre de la relativité restreinte (1905), reliant masse et énergie.",
    svg_config: null,
  },
  {
    difficulty: 7, category: "chimie", type: "text", time_limit: 25,
    text: "Quel élément chimique a pour symbole « Fe » ?",
    choices: ["Le fluor", "Le fer", "Le francium", "Le fermium"],
    correct_index: 1,
    explanation: "Le symbole Fe vient du latin « ferrum » et désigne le fer.",
    svg_config: null,
  },
  {
    difficulty: 7, category: "biologie", type: "text", time_limit: 25,
    text: "Combien de paires de chromosomes une cellule humaine normale possède-t-elle ?",
    choices: ["21 paires", "22 paires", "23 paires", "24 paires"],
    correct_index: 2,
    explanation: "Une cellule humaine normale contient 23 paires de chromosomes, soit 46 au total.",
    svg_config: null,
  },
  {
    difficulty: 7, category: "astronomie", type: "text", time_limit: 25,
    text: "Comment appelle-t-on une étoile qui s'effondre en un objet si dense que la lumière ne peut s'en échapper ?",
    choices: ["Une naine blanche", "Une supernova", "Un trou noir", "Une étoile à neutrons"],
    correct_index: 2,
    explanation: "Un trou noir est une région de l'espace si dense que sa gravité empêche même la lumière de s'en échapper.",
    svg_config: null,
  },
  {
    difficulty: 7, category: "corps-humain", type: "text", time_limit: 25,
    text: "Quelle hormone régule principalement le taux de sucre dans le sang en le faisant baisser ?",
    choices: ["L'adrénaline", "L'insuline", "La thyroxine", "Le cortisol"],
    correct_index: 1,
    explanation: "L'insuline, sécrétée par le pancréas, abaisse la glycémie en facilitant l'entrée du glucose dans les cellules.",
    svg_config: null,
  },
  {
    difficulty: 7, category: "chimie", type: "text", time_limit: 25,
    text: "Quel est le gaz noble le plus léger ?",
    choices: ["L'argon", "Le néon", "L'hélium", "Le krypton"],
    correct_index: 2,
    explanation: "L'hélium est le gaz noble le plus léger ; c'est aussi le deuxième élément le plus léger après l'hydrogène.",
    svg_config: null,
  },
  {
    difficulty: 7, category: "geologie", type: "text", time_limit: 25,
    text: "Comment appelle-t-on le supercontinent qui regroupait toutes les terres il y a environ 250 millions d'années ?",
    choices: ["Le Gondwana", "La Laurasie", "La Pangée", "La Rodinia"],
    correct_index: 2,
    explanation: "La Pangée était le supercontinent unique du Permien-Trias, qui s'est ensuite fragmenté en les continents actuels.",
    svg_config: null,
  },
  {
    difficulty: 7, category: "physique", type: "text", time_limit: 25,
    text: "Quelle loi physique stipule que l'action est toujours égale et opposée à la réaction ?",
    choices: ["La première loi de Newton", "La troisième loi de Newton", "La loi d'Ohm", "La loi de Hooke"],
    correct_index: 1,
    explanation: "La troisième loi de Newton énonce que toute action s'accompagne d'une réaction de même intensité et de sens opposé.",
    svg_config: null,
  },
  {
    difficulty: 7, category: "botanique", type: "text", time_limit: 25,
    text: "Quel terme désigne les plantes qui produisent des graines protégées dans un fruit ?",
    choices: ["Gymnospermes", "Angiospermes", "Ptéridophytes", "Bryophytes"],
    correct_index: 1,
    explanation: "Les angiospermes sont les plantes à fleurs dont les graines sont enfermées dans un fruit, contrairement aux gymnospermes (comme les conifères).",
    svg_config: null,
  },
  {
    difficulty: 7, category: "biologie", type: "text", time_limit: 25,
    text: "Quel scientifique est considéré comme le père de la génétique pour ses travaux sur les petits pois ?",
    choices: ["Charles Darwin", "Gregor Mendel", "Louis Pasteur", "Alexander Fleming"],
    correct_index: 1,
    explanation: "Gregor Mendel a établi les lois de l'hérédité grâce à ses expériences sur les pois, fondant la génétique.",
    svg_config: null,
  },

  // ===== DIFFICULTE 8 — TRES DIFFICILE (25s) =====
  {
    difficulty: 8, category: "chimie", type: "text", time_limit: 25,
    text: "Quel est le numéro atomique du carbone ?",
    choices: ["4", "6", "8", "12"],
    correct_index: 1,
    explanation: "Le carbone a pour numéro atomique 6 : son noyau contient 6 protons. Sa masse atomique courante (≈12) ne doit pas être confondue avec ce numéro.",
    svg_config: null,
  },
  {
    difficulty: 8, category: "physique", type: "text", time_limit: 25,
    text: "Quelle particule subatomique porte une charge électrique négative ?",
    choices: ["Le proton", "Le neutron", "L'électron", "Le photon"],
    correct_index: 2,
    explanation: "L'électron porte une charge négative ; le proton est positif et le neutron est électriquement neutre.",
    svg_config: null,
  },
  {
    difficulty: 8, category: "biologie", type: "text", time_limit: 25,
    text: "Comment appelle-t-on le processus par lequel l'ARN messager est traduit en protéine ?",
    choices: ["La transcription", "La traduction", "La réplication", "La transduction"],
    correct_index: 1,
    explanation: "La traduction est l'étape, réalisée par les ribosomes, qui convertit la séquence de l'ARN messager en une chaîne d'acides aminés.",
    svg_config: null,
  },
  {
    difficulty: 8, category: "astronomie", type: "text", time_limit: 25,
    text: "Comment nomme-t-on l'unité de distance correspondant à la distance moyenne Terre-Soleil ?",
    choices: ["L'année-lumière", "Le parsec", "L'unité astronomique", "Le méga-mètre"],
    correct_index: 2,
    explanation: "L'unité astronomique (ua) correspond à la distance moyenne Terre-Soleil, soit environ 150 millions de kilomètres.",
    svg_config: null,
  },
  {
    difficulty: 8, category: "chimie", type: "text", time_limit: 25,
    text: "Quel type de liaison chimique se forme par mise en commun d'électrons entre deux atomes ?",
    choices: ["La liaison ionique", "La liaison covalente", "La liaison métallique", "La liaison hydrogène"],
    correct_index: 1,
    explanation: "La liaison covalente résulte du partage d'une ou plusieurs paires d'électrons entre deux atomes, comme dans la molécule H2.",
    svg_config: null,
  },
  {
    difficulty: 8, category: "corps-humain", type: "text", time_limit: 25,
    text: "Quelle partie du cerveau est principalement responsable de l'équilibre et de la coordination des mouvements ?",
    choices: ["Le cortex frontal", "Le cervelet", "L'hypothalamus", "Le bulbe rachidien"],
    correct_index: 1,
    explanation: "Le cervelet coordonne les mouvements et contribue au maintien de l'équilibre et de la posture.",
    svg_config: null,
  },
  {
    difficulty: 8, category: "physique", type: "text", time_limit: 25,
    text: "Selon la loi d'Ohm, quelle relation lie tension (U), intensité (I) et résistance (R) ?",
    choices: ["U = I / R", "U = R / I", "U = R × I", "U = I − R"],
    correct_index: 2,
    explanation: "La loi d'Ohm s'écrit U = R × I : la tension est le produit de la résistance par l'intensité du courant.",
    svg_config: null,
  },
  {
    difficulty: 8, category: "geologie", type: "text", time_limit: 25,
    text: "Quelle théorie explique le déplacement des grandes plaques de la lithosphère terrestre ?",
    choices: ["La dérive génétique", "La tectonique des plaques", "Le cycle de Wilson uniquement", "L'isostasie"],
    correct_index: 1,
    explanation: "La tectonique des plaques décrit le déplacement des plaques lithosphériques, à l'origine des séismes, volcans et chaînes de montagnes.",
    svg_config: null,
  },
  {
    difficulty: 8, category: "biologie", type: "text", time_limit: 25,
    text: "Quel pigment des globules rouges transporte l'oxygène dans le sang ?",
    choices: ["La myoglobine", "L'hémoglobine", "La chlorophylle", "La kératine"],
    correct_index: 1,
    explanation: "L'hémoglobine, contenue dans les globules rouges, fixe l'oxygène au niveau des poumons et le distribue aux tissus.",
    svg_config: null,
  },
  {
    difficulty: 8, category: "astronomie", type: "text", time_limit: 25,
    text: "Comment appelle-t-on l'explosion qui marque la fin de vie de certaines étoiles massives ?",
    choices: ["Une nova", "Une supernova", "Une protoétoile", "Une géante rouge"],
    correct_index: 1,
    explanation: "Une supernova est l'explosion cataclysmique d'une étoile massive en fin de vie, dispersant ses éléments dans l'espace.",
    svg_config: null,
  },

  // ===== DIFFICULTE 9 — EXPERT (30s) =====
  {
    difficulty: 9, category: "physique", type: "text", time_limit: 30,
    text: "Quel principe de la mécanique quantique stipule qu'on ne peut connaître simultanément avec précision la position et la quantité de mouvement d'une particule ?",
    choices: ["Le principe de Pauli", "Le principe d'incertitude de Heisenberg", "Le principe d'Archimède", "Le principe de Le Chatelier"],
    correct_index: 1,
    explanation: "Le principe d'incertitude de Heisenberg pose une limite fondamentale à la précision simultanée sur la position et la quantité de mouvement.",
    svg_config: null,
  },
  {
    difficulty: 9, category: "chimie", type: "text", time_limit: 30,
    text: "Quel chimiste russe est à l'origine de la classification périodique des éléments en 1869 ?",
    choices: ["Antoine Lavoisier", "Dmitri Mendeleïev", "Marie Curie", "Linus Pauling"],
    correct_index: 1,
    explanation: "Dmitri Mendeleïev a proposé en 1869 le tableau périodique, prédisant même l'existence d'éléments encore inconnus.",
    svg_config: null,
  },
  {
    difficulty: 9, category: "biologie", type: "text", time_limit: 30,
    text: "Quelle enzyme est utilisée pour amplifier l'ADN lors d'une réaction en chaîne par polymérase (PCR) ?",
    choices: ["La ligase", "L'ADN polymérase", "L'ARN polymérase", "La protéase"],
    correct_index: 1,
    explanation: "La PCR utilise une ADN polymérase thermostable (comme la Taq polymérase) pour synthétiser de nouveaux brins et amplifier l'ADN.",
    svg_config: null,
  },
  {
    difficulty: 9, category: "astronomie", type: "text", time_limit: 30,
    text: "Comment nomme-t-on le rayon limite d'un trou noir au-delà duquel rien ne peut s'échapper ?",
    choices: ["Le rayon de Bohr", "Le rayon de Schwarzschild", "Le rayon de Hubble", "Le rayon de Roche"],
    correct_index: 1,
    explanation: "Le rayon de Schwarzschild définit l'horizon des événements d'un trou noir non rotatif, frontière au-delà de laquelle rien ne ressort.",
    svg_config: null,
  },
  {
    difficulty: 9, category: "chimie", type: "text", time_limit: 30,
    text: "Combien vaut approximativement le nombre d'Avogadro ?",
    choices: ["6,02 × 10²³", "3,14 × 10⁸", "1,60 × 10⁻¹⁹", "9,81 × 10²"],
    correct_index: 0,
    explanation: "Le nombre d'Avogadro vaut environ 6,02 × 10²³ : c'est le nombre d'entités élémentaires contenues dans une mole.",
    svg_config: null,
  },
  {
    difficulty: 9, category: "physique", type: "text", time_limit: 30,
    text: "Quelle est l'unité de mesure de la résistance électrique ?",
    choices: ["Le farad", "Le henry", "L'ohm", "Le siemens"],
    correct_index: 2,
    explanation: "La résistance électrique se mesure en ohms (symbole Ω), du nom du physicien Georg Ohm.",
    svg_config: null,
  },
  {
    difficulty: 9, category: "biologie", type: "text", time_limit: 30,
    text: "Quel cycle biochimique produit l'essentiel de l'ATP dans la mitochondrie en consommant de l'oxygène ?",
    choices: ["La glycolyse", "Le cycle de Krebs", "La fermentation lactique", "Le cycle de Calvin"],
    correct_index: 1,
    explanation: "Le cycle de Krebs (cycle de l'acide citrique), couplé à la chaîne respiratoire, génère la majeure partie de l'ATP cellulaire en aérobie.",
    svg_config: null,
  },
  {
    difficulty: 9, category: "geologie", type: "text", time_limit: 30,
    text: "Quel isotope du carbone est utilisé pour dater des restes organiques de quelques milliers d'années ?",
    choices: ["Le carbone 12", "Le carbone 13", "Le carbone 14", "Le carbone 11"],
    correct_index: 2,
    explanation: "Le carbone 14, radioactif, est utilisé pour dater des matériaux organiques grâce à sa désintégration à période connue.",
    svg_config: null,
  },
  {
    difficulty: 9, category: "chimie", type: "text", time_limit: 30,
    text: "Quel élément possède le numéro atomique le plus élevé parmi ceux présents naturellement en quantité notable sur Terre ?",
    choices: ["Le plomb", "L'or", "L'uranium", "Le radium"],
    correct_index: 2,
    explanation: "L'uranium (numéro atomique 92) est l'élément naturel le plus lourd présent en quantité notable dans la croûte terrestre.",
    svg_config: null,
  },
  {
    difficulty: 9, category: "physique", type: "text", time_limit: 30,
    text: "Quel phénomène décrit le changement de fréquence d'une onde perçue lorsqu'une source se rapproche ou s'éloigne ?",
    choices: ["L'effet Doppler", "L'effet photoélectrique", "L'effet Joule", "L'effet Compton"],
    correct_index: 0,
    explanation: "L'effet Doppler explique la variation de fréquence perçue selon le mouvement relatif entre la source et l'observateur (ex. sirène qui passe).",
    svg_config: null,
  },

  // ===== DIFFICULTE 10 — MAITRE (30s) =====
  {
    difficulty: 10, category: "physique", type: "text", time_limit: 30,
    text: "Quelle particule, découverte au CERN en 2012, est associée au mécanisme conférant leur masse aux autres particules ?",
    choices: ["Le neutrino", "Le boson de Higgs", "Le quark top", "Le muon"],
    correct_index: 1,
    explanation: "Le boson de Higgs, détecté au CERN en 2012, est lié au champ de Higgs qui confère leur masse aux particules élémentaires.",
    svg_config: null,
  },
  {
    difficulty: 10, category: "chimie", type: "text", time_limit: 30,
    text: "Quel principe énonce qu'un système à l'équilibre, perturbé, évolue pour s'opposer à la perturbation ?",
    choices: ["Le principe de Pauli", "Le principe de Le Chatelier", "Le principe d'Avogadro", "Le principe de Hund"],
    correct_index: 1,
    explanation: "Le principe de Le Chatelier décrit comment un équilibre chimique se déplace pour atténuer une modification de température, pression ou concentration.",
    svg_config: null,
  },
  {
    difficulty: 10, category: "biologie", type: "text", time_limit: 30,
    text: "Quelles sont les quatre bases azotées constituant l'ADN ?",
    choices: ["Adénine, Thymine, Guanine, Cytosine", "Adénine, Uracile, Guanine, Cytosine", "Adénine, Thymine, Glycine, Cytosine", "Alanine, Thymine, Guanine, Cystéine"],
    correct_index: 0,
    explanation: "L'ADN est constitué des bases adénine (A), thymine (T), guanine (G) et cytosine (C) ; l'uracile remplace la thymine dans l'ARN.",
    svg_config: null,
  },
  {
    difficulty: 10, category: "astronomie", type: "text", time_limit: 30,
    text: "Quelle loi de Kepler établit que le carré de la période orbitale est proportionnel au cube du demi-grand axe ?",
    choices: ["La première loi", "La deuxième loi", "La troisième loi", "La quatrième loi"],
    correct_index: 2,
    explanation: "La troisième loi de Kepler relie le carré de la période de révolution au cube du demi-grand axe de l'orbite (T² ∝ a³).",
    svg_config: null,
  },
  {
    difficulty: 10, category: "physique", type: "text", time_limit: 30,
    text: "Quel est l'ordre de grandeur de la constante de gravitation universelle G ?",
    choices: ["6,67 × 10⁻¹¹ N·m²/kg²", "9,81 × 10⁰ N·m²/kg²", "3,00 × 10⁸ N·m²/kg²", "1,38 × 10⁻²³ N·m²/kg²"],
    correct_index: 0,
    explanation: "La constante de gravitation universelle G vaut environ 6,67 × 10⁻¹¹ N·m²/kg² dans la loi de Newton.",
    svg_config: null,
  },
  {
    difficulty: 10, category: "chimie", type: "text", time_limit: 30,
    text: "Quelle géométrie adopte la molécule de méthane (CH4) autour de l'atome de carbone central ?",
    choices: ["Plane carrée", "Tétraédrique", "Linéaire", "Octaédrique"],
    correct_index: 1,
    explanation: "Le méthane CH4 adopte une géométrie tétraédrique, avec des angles de liaison d'environ 109,5° autour du carbone.",
    svg_config: null,
  },
  {
    difficulty: 10, category: "biologie", type: "text", time_limit: 30,
    text: "Quel chercheur a découvert la pénicilline en 1928 ?",
    choices: ["Louis Pasteur", "Alexander Fleming", "Robert Koch", "Joseph Lister"],
    correct_index: 1,
    explanation: "Alexander Fleming a découvert en 1928 la pénicilline, produite par le champignon Penicillium, premier antibiotique de l'histoire.",
    svg_config: null,
  },
  {
    difficulty: 10, category: "physique", type: "text", time_limit: 30,
    text: "Que stipule le deuxième principe de la thermodynamique à propos de l'entropie d'un système isolé ?",
    choices: ["Elle diminue toujours", "Elle reste constante", "Elle ne peut que croître ou rester constante", "Elle est toujours nulle"],
    correct_index: 2,
    explanation: "Le deuxième principe de la thermodynamique énonce que l'entropie d'un système isolé ne peut que croître ou, à la limite, rester constante.",
    svg_config: null,
  },
  {
    difficulty: 10, category: "chimie", type: "text", time_limit: 30,
    text: "Quel scientifique a reçu deux prix Nobel dans deux disciplines scientifiques différentes (physique et chimie) ?",
    choices: ["Albert Einstein", "Marie Curie", "Linus Pauling", "Niels Bohr"],
    correct_index: 1,
    explanation: "Marie Curie a reçu le prix Nobel de physique en 1903 et celui de chimie en 1911, fait unique pour deux disciplines scientifiques distinctes.",
    svg_config: null,
  },
  {
    difficulty: 10, category: "astronomie", type: "text", time_limit: 30,
    text: "Comment nomme-t-on le rayonnement fossile, vestige micro-onde du Big Bang, découvert en 1965 ?",
    choices: ["Le rayonnement synchrotron", "Le fond diffus cosmologique", "Le vent solaire", "Le rayonnement de Hawking"],
    correct_index: 1,
    explanation: "Le fond diffus cosmologique (rayonnement de fond à 2,7 K) est le vestige micro-onde du Big Bang, observé pour la première fois en 1965.",
    svg_config: null,
  },
];
