import type { Question } from "./types";

export const questionsVraiFaux: Omit<Question, "id">[] = [
  // ===== DIFFICULTE 1 — TRES CONNU (15s) =====
  {
    difficulty: 1, category: "corps-mythe", type: "text", time_limit: 15,
    text: "On n'utilise que 10 % de notre cerveau.",
    choices: ["Vrai", "Faux"],
    correct_index: 1,
    explanation: "Faux. C'est un mythe tenace : l'imagerie cérébrale montre que nous utilisons la quasi-totalité de notre cerveau, à des moments différents.",
    svg_config: null,
  },
  {
    difficulty: 1, category: "nature-mythe", type: "text", time_limit: 15,
    text: "La Grande Muraille de Chine est visible à l'œil nu depuis la Lune.",
    choices: ["Vrai", "Faux"],
    correct_index: 1,
    explanation: "Faux. Elle est bien trop étroite pour être distinguée à l'œil nu depuis la Lune ; même en orbite basse, elle est à peine visible.",
    svg_config: null,
  },
  {
    difficulty: 1, category: "nature-mythe", type: "text", time_limit: 15,
    text: "Un poisson rouge n'a une mémoire que de trois secondes.",
    choices: ["Vrai", "Faux"],
    correct_index: 1,
    explanation: "Faux. Les poissons rouges peuvent mémoriser des informations pendant des semaines, voire des mois, comme l'ont montré plusieurs expériences.",
    svg_config: null,
  },
  {
    difficulty: 1, category: "science-mythe", type: "text", time_limit: 15,
    text: "La foudre peut frapper deux fois au même endroit.",
    choices: ["Vrai", "Faux"],
    correct_index: 0,
    explanation: "Vrai. La foudre frappe souvent plusieurs fois le même point : la Tour Eiffel ou l'Empire State Building sont touchés des dizaines de fois par an.",
    svg_config: null,
  },
  {
    difficulty: 1, category: "nature-mythe", type: "text", time_limit: 15,
    text: "Les chauves-souris sont aveugles.",
    choices: ["Vrai", "Faux"],
    correct_index: 1,
    explanation: "Faux. Toutes les chauves-souris voient ; certaines ont même une excellente vue. Elles utilisent l'écholocation en complément, pas en remplacement.",
    svg_config: null,
  },
  {
    difficulty: 1, category: "corps-mythe", type: "text", time_limit: 15,
    text: "Le sang est bleu dans nos veines avant d'être oxygéné.",
    choices: ["Vrai", "Faux"],
    correct_index: 1,
    explanation: "Faux. Le sang est toujours rouge ; il paraît bleuâtre à travers la peau à cause de la façon dont la lumière est absorbée et diffusée.",
    svg_config: null,
  },
  {
    difficulty: 1, category: "science-mythe", type: "text", time_limit: 15,
    text: "L'eau conduit l'électricité même quand elle est parfaitement pure.",
    choices: ["Vrai", "Faux"],
    correct_index: 1,
    explanation: "Faux. L'eau pure est un mauvais conducteur ; c'est la présence de sels et d'ions dissous qui rend l'eau du robinet conductrice.",
    svg_config: null,
  },
  {
    difficulty: 1, category: "nature-mythe", type: "text", time_limit: 15,
    text: "Les autruches enfouissent leur tête dans le sable quand elles ont peur.",
    choices: ["Vrai", "Faux"],
    correct_index: 1,
    explanation: "Faux. Elles abaissent la tête au ras du sol pour surveiller ou retourner leurs œufs, mais ne l'enterrent jamais : elles s'asphyxieraient.",
    svg_config: null,
  },
  {
    difficulty: 1, category: "corps-mythe", type: "text", time_limit: 15,
    text: "Les empreintes digitales sont uniques à chaque individu.",
    choices: ["Vrai", "Faux"],
    correct_index: 0,
    explanation: "Vrai. Même les vrais jumeaux, qui partagent le même ADN, ont des empreintes digitales différentes, car elles se forment selon des conditions aléatoires in utero.",
    svg_config: null,
  },
  {
    difficulty: 1, category: "science-mythe", type: "text", time_limit: 15,
    text: "Le Soleil est une étoile.",
    choices: ["Vrai", "Faux"],
    correct_index: 0,
    explanation: "Vrai. Le Soleil est une étoile de type naine jaune, simplement bien plus proche de nous que toutes les autres étoiles.",
    svg_config: null,
  },

  // ===== DIFFICULTE 2 — CONNU (15s) =====
  {
    difficulty: 2, category: "histoire-mythe", type: "text", time_limit: 15,
    text: "Napoléon Bonaparte était particulièrement petit pour son époque.",
    choices: ["Vrai", "Faux"],
    correct_index: 1,
    explanation: "Faux. Il mesurait environ 1,68 m, taille moyenne à l'époque. La confusion vient d'une différence entre les pouces français et anglais et de la propagande.",
    svg_config: null,
  },
  {
    difficulty: 2, category: "corps-mythe", type: "text", time_limit: 15,
    text: "Couper ses cheveux les fait repousser plus épais et plus vite.",
    choices: ["Vrai", "Faux"],
    correct_index: 1,
    explanation: "Faux. La coupe n'affecte ni la vitesse ni l'épaisseur de la repousse ; le poil coupé paraît juste plus dru car son extrémité est nette.",
    svg_config: null,
  },
  {
    difficulty: 2, category: "nature-mythe", type: "text", time_limit: 15,
    text: "Les taureaux sont enragés par la couleur rouge.",
    choices: ["Vrai", "Faux"],
    correct_index: 1,
    explanation: "Faux. Les taureaux sont partiellement daltoniens et ne distinguent pas le rouge ; c'est le mouvement de la cape qui les fait charger.",
    svg_config: null,
  },
  {
    difficulty: 2, category: "corps-mythe", type: "text", time_limit: 15,
    text: "Avaler un chewing-gum reste sept ans dans l'estomac.",
    choices: ["Vrai", "Faux"],
    correct_index: 1,
    explanation: "Faux. Le chewing-gum n'est pas digéré mais traverse normalement le système digestif et est évacué en quelques jours.",
    svg_config: null,
  },
  {
    difficulty: 2, category: "science-mythe", type: "text", time_limit: 15,
    text: "Les diamants se forment à partir de charbon comprimé.",
    choices: ["Vrai", "Faux"],
    correct_index: 1,
    explanation: "Faux. La plupart des diamants se sont formés dans le manteau terrestre à partir de carbone, bien avant l'apparition des forêts qui ont donné le charbon.",
    svg_config: null,
  },
  {
    difficulty: 2, category: "corps-mythe", type: "text", time_limit: 15,
    text: "Le corps humain compte plus de bactéries que de cellules humaines.",
    choices: ["Vrai", "Faux"],
    correct_index: 0,
    explanation: "Vrai. Le nombre de cellules bactériennes du microbiote est du même ordre, voire légèrement supérieur, à celui de nos propres cellules.",
    svg_config: null,
  },
  {
    difficulty: 2, category: "nature-mythe", type: "text", time_limit: 15,
    text: "Le miel ne se périme jamais s'il est bien conservé.",
    choices: ["Vrai", "Faux"],
    correct_index: 0,
    explanation: "Vrai. Grâce à sa faible teneur en eau et son acidité, le miel correctement stocké peut se conserver des années ; on en a retrouvé de comestible dans des tombes antiques.",
    svg_config: null,
  },
  {
    difficulty: 2, category: "science-mythe", type: "text", time_limit: 15,
    text: "Un éclair est plus chaud que la surface du Soleil.",
    choices: ["Vrai", "Faux"],
    correct_index: 0,
    explanation: "Vrai. Un éclair peut atteindre environ 30 000 °C, soit près de cinq fois la température de la surface du Soleil (environ 5 500 °C).",
    svg_config: null,
  },
  {
    difficulty: 2, category: "nature-mythe", type: "text", time_limit: 15,
    text: "Les manchots et les ours polaires ne vivent pas sur le même pôle.",
    choices: ["Vrai", "Faux"],
    correct_index: 0,
    explanation: "Vrai. Les manchots vivent surtout dans l'hémisphère sud (Antarctique) tandis que les ours polaires vivent dans l'Arctique : ils ne se croisent jamais.",
    svg_config: null,
  },
  {
    difficulty: 2, category: "histoire-mythe", type: "text", time_limit: 15,
    text: "Les Vikings portaient des casques à cornes.",
    choices: ["Vrai", "Faux"],
    correct_index: 1,
    explanation: "Faux. Aucune preuve archéologique ne confirme cela ; l'image des casques à cornes vient surtout des costumes d'opéra du XIXe siècle.",
    svg_config: null,
  },

  // ===== DIFFICULTE 3 — CONNU (15s) =====
  {
    difficulty: 3, category: "corps-mythe", type: "text", time_limit: 15,
    text: "La langue possède des zones distinctes pour chaque goût (sucré, salé...).",
    choices: ["Vrai", "Faux"],
    correct_index: 1,
    explanation: "Faux. La fameuse carte des goûts est erronée : toutes les zones de la langue peuvent percevoir les cinq saveurs de base.",
    svg_config: null,
  },
  {
    difficulty: 3, category: "science-mythe", type: "text", time_limit: 15,
    text: "L'étoile Polaire est l'étoile la plus brillante du ciel nocturne.",
    choices: ["Vrai", "Faux"],
    correct_index: 1,
    explanation: "Faux. L'étoile la plus brillante est Sirius. L'étoile Polaire est connue car elle indique le nord, pas pour son éclat.",
    svg_config: null,
  },
  {
    difficulty: 3, category: "histoire-mythe", type: "text", time_limit: 15,
    text: "On a longtemps cru, au Moyen Âge, que la Terre était plate.",
    choices: ["Vrai", "Faux"],
    correct_index: 1,
    explanation: "Faux. Dès l'Antiquité, les savants savaient la Terre ronde ; l'idée d'un Moyen Âge croyant à une Terre plate est un mythe du XIXe siècle.",
    svg_config: null,
  },
  {
    difficulty: 3, category: "nature-mythe", type: "text", time_limit: 15,
    text: "Les caméléons changent de couleur uniquement pour se camoufler.",
    choices: ["Vrai", "Faux"],
    correct_index: 1,
    explanation: "Faux. Ils changent surtout de couleur pour réguler leur température et communiquer leurs émotions ou leur statut social.",
    svg_config: null,
  },
  {
    difficulty: 3, category: "corps-mythe", type: "text", time_limit: 15,
    text: "Faire craquer ses doigts provoque de l'arthrose.",
    choices: ["Vrai", "Faux"],
    correct_index: 1,
    explanation: "Faux. Les études, dont celle d'un médecin l'ayant pratiqué sur une seule main pendant des décennies, n'ont montré aucun lien avec l'arthrose.",
    svg_config: null,
  },
  {
    difficulty: 3, category: "science-mythe", type: "text", time_limit: 15,
    text: "Il existe plus d'étoiles dans l'univers observable que de grains de sable sur Terre.",
    choices: ["Vrai", "Faux"],
    correct_index: 0,
    explanation: "Vrai. Les estimations donnent environ 10^24 étoiles, un nombre supérieur aux estimations du total des grains de sable de toutes les plages et déserts.",
    svg_config: null,
  },
  {
    difficulty: 3, category: "nature-mythe", type: "text", time_limit: 15,
    text: "Le bananier n'est pas un arbre mais une plante herbacée géante.",
    choices: ["Vrai", "Faux"],
    correct_index: 0,
    explanation: "Vrai. Le bananier n'a pas de tronc ligneux : son « tronc » apparent est constitué de feuilles enroulées, c'est une plante herbacée géante.",
    svg_config: null,
  },
  {
    difficulty: 3, category: "culture-mythe", type: "text", time_limit: 15,
    text: "Albert Einstein était un mauvais élève en mathématiques.",
    choices: ["Vrai", "Faux"],
    correct_index: 1,
    explanation: "Faux. Einstein excellait en mathématiques dès le plus jeune âge ; il maîtrisait le calcul différentiel avant 15 ans.",
    svg_config: null,
  },
  {
    difficulty: 3, category: "science-mythe", type: "text", time_limit: 15,
    text: "Sur la Lune, un astronaute est en apesanteur car il n'y a pas de gravité.",
    choices: ["Vrai", "Faux"],
    correct_index: 1,
    explanation: "Faux. La Lune possède bien une gravité (environ un sixième de celle de la Terre) ; c'est pourquoi les astronautes y retombent au sol.",
    svg_config: null,
  },
  {
    difficulty: 3, category: "nature-mythe", type: "text", time_limit: 15,
    text: "La pieuvre possède trois cœurs.",
    choices: ["Vrai", "Faux"],
    correct_index: 0,
    explanation: "Vrai. La pieuvre a trois cœurs : deux pompent le sang vers les branchies et un troisième le distribue au reste du corps.",
    svg_config: null,
  },

  // ===== DIFFICULTE 4 — INTERMEDIAIRE (20s) =====
  {
    difficulty: 4, category: "science-mythe", type: "text", time_limit: 20,
    text: "La Muraille de Chine est la seule construction humaine visible depuis l'espace.",
    choices: ["Vrai", "Faux"],
    correct_index: 1,
    explanation: "Faux. Depuis l'orbite basse, on distingue de nombreuses constructions (villes, aéroports, routes), et la Muraille est en réalité difficile à repérer.",
    svg_config: null,
  },
  {
    difficulty: 4, category: "corps-mythe", type: "text", time_limit: 20,
    text: "Les humains n'ont que cinq sens.",
    choices: ["Vrai", "Faux"],
    correct_index: 1,
    explanation: "Faux. Outre les cinq sens classiques, on possède la proprioception, l'équilibre, la perception de la température, de la douleur, etc.",
    svg_config: null,
  },
  {
    difficulty: 4, category: "histoire-mythe", type: "text", time_limit: 20,
    text: "Marie-Antoinette a réellement dit « Qu'ils mangent de la brioche ».",
    choices: ["Vrai", "Faux"],
    correct_index: 1,
    explanation: "Faux. Cette phrase circulait dans des écrits (notamment chez Rousseau) avant même son arrivée en France ; rien ne prouve qu'elle l'ait prononcée.",
    svg_config: null,
  },
  {
    difficulty: 4, category: "nature-mythe", type: "text", time_limit: 20,
    text: "Les fourmis ne dorment jamais.",
    choices: ["Vrai", "Faux"],
    correct_index: 1,
    explanation: "Faux. Les fourmis font de nombreuses micro-siestes ; les reines peuvent dormir plusieurs heures par jour, réparties en courtes périodes.",
    svg_config: null,
  },
  {
    difficulty: 4, category: "science-mythe", type: "text", time_limit: 20,
    text: "L'or est si rare que tout l'or jamais extrait tiendrait dans quelques piscines olympiques.",
    choices: ["Vrai", "Faux"],
    correct_index: 0,
    explanation: "Vrai. Tout l'or extrait dans l'histoire humaine formerait un cube d'environ 22 mètres d'arête, soit l'équivalent de quelques piscines olympiques.",
    svg_config: null,
  },
  {
    difficulty: 4, category: "corps-mythe", type: "text", time_limit: 20,
    text: "On perd la majeure partie de sa chaleur corporelle par la tête.",
    choices: ["Vrai", "Faux"],
    correct_index: 1,
    explanation: "Faux. La tête ne représente qu'environ 10 % de la surface corporelle ; on perd de la chaleur partout où la peau est exposée.",
    svg_config: null,
  },
  {
    difficulty: 4, category: "nature-mythe", type: "text", time_limit: 20,
    text: "Le venin et le poison désignent la même chose.",
    choices: ["Vrai", "Faux"],
    correct_index: 1,
    explanation: "Faux. Le venin est injecté (morsure, piqûre), tandis que le poison agit par ingestion, inhalation ou contact ; un animal peut être l'un sans être l'autre.",
    svg_config: null,
  },
  {
    difficulty: 4, category: "histoire-mythe", type: "text", time_limit: 20,
    text: "Les pyramides d'Égypte ont été construites par des esclaves.",
    choices: ["Vrai", "Faux"],
    correct_index: 1,
    explanation: "Faux. Les recherches archéologiques montrent qu'elles ont été bâties par des ouvriers payés et nourris, logés dans des villages dédiés.",
    svg_config: null,
  },
  {
    difficulty: 4, category: "science-mythe", type: "text", time_limit: 20,
    text: "Le verre est un liquide qui s'écoule très lentement, ce qui explique les vitres anciennes plus épaisses en bas.",
    choices: ["Vrai", "Faux"],
    correct_index: 1,
    explanation: "Faux. Le verre est un solide amorphe qui ne s'écoule pas ; l'épaisseur inégale des vieilles vitres vient de leur procédé de fabrication.",
    svg_config: null,
  },
  {
    difficulty: 4, category: "nature-mythe", type: "text", time_limit: 20,
    text: "Les escargots peuvent dormir plusieurs années d'affilée.",
    choices: ["Vrai", "Faux"],
    correct_index: 0,
    explanation: "Vrai. Certains escargots entrent en estivation prolongée et peuvent rester dormants pendant plusieurs années en attendant des conditions favorables.",
    svg_config: null,
  },

  // ===== DIFFICULTE 5 — INTERMEDIAIRE (20s) =====
  {
    difficulty: 5, category: "science-mythe", type: "text", time_limit: 20,
    text: "Un centime lâché du haut d'un gratte-ciel peut tuer un passant en bas.",
    choices: ["Vrai", "Faux"],
    correct_index: 1,
    explanation: "Faux. À cause de sa forme plate et de la résistance de l'air, une pièce atteint une vitesse terminale modérée et ne ferait pas de dégât mortel.",
    svg_config: null,
  },
  {
    difficulty: 5, category: "corps-mythe", type: "text", time_limit: 20,
    text: "Le cerveau humain est lisse chez certaines personnes en bonne santé.",
    choices: ["Vrai", "Faux"],
    correct_index: 1,
    explanation: "Faux. Un cerveau lisse (lissencéphalie) est une malformation grave ; un cerveau humain sain présente toujours des circonvolutions.",
    svg_config: null,
  },
  {
    difficulty: 5, category: "histoire-mythe", type: "text", time_limit: 20,
    text: "Thomas Edison a inventé l'ampoule électrique.",
    choices: ["Vrai", "Faux"],
    correct_index: 1,
    explanation: "Faux. Edison a perfectionné et commercialisé une ampoule durable, mais d'autres, comme Joseph Swan, avaient développé l'incandescence avant lui.",
    svg_config: null,
  },
  {
    difficulty: 5, category: "nature-mythe", type: "text", time_limit: 20,
    text: "Les requins ne sont jamais atteints de cancer.",
    choices: ["Vrai", "Faux"],
    correct_index: 1,
    explanation: "Faux. Des tumeurs cancéreuses ont bel et bien été documentées chez les requins ; ce mythe a alimenté un commerce de cartilage sans fondement.",
    svg_config: null,
  },
  {
    difficulty: 5, category: "science-mythe", type: "text", time_limit: 20,
    text: "L'eau chaude peut geler plus vite que l'eau froide dans certaines conditions.",
    choices: ["Vrai", "Faux"],
    correct_index: 0,
    explanation: "Vrai. C'est l'effet Mpemba, observé dans certaines conditions expérimentales, même si son mécanisme exact fait encore débat.",
    svg_config: null,
  },
  {
    difficulty: 5, category: "corps-mythe", type: "text", time_limit: 20,
    text: "Lire dans la pénombre abîme durablement la vue.",
    choices: ["Vrai", "Faux"],
    correct_index: 1,
    explanation: "Faux. Lire dans une faible lumière fatigue les yeux temporairement, mais ne cause pas de dommage permanent à la vision.",
    svg_config: null,
  },
  {
    difficulty: 5, category: "culture-mythe", type: "text", time_limit: 20,
    text: "Walt Disney a été cryogénisé après sa mort.",
    choices: ["Vrai", "Faux"],
    correct_index: 1,
    explanation: "Faux. Walt Disney a été incinéré en 1966 ; la légende de sa congélation est une rumeur sans aucun fondement.",
    svg_config: null,
  },
  {
    difficulty: 5, category: "nature-mythe", type: "text", time_limit: 20,
    text: "Une plante peut survivre uniquement en se nourrissant de la lumière, sans terre.",
    choices: ["Vrai", "Faux"],
    correct_index: 0,
    explanation: "Vrai. En culture hydroponique, les plantes poussent sans terre, leurs racines baignant dans une solution nutritive, la lumière assurant la photosynthèse.",
    svg_config: null,
  },
  {
    difficulty: 5, category: "science-mythe", type: "text", time_limit: 20,
    text: "Les saisons sont dues à l'inclinaison de l'axe de la Terre, pas à sa distance au Soleil.",
    choices: ["Vrai", "Faux"],
    correct_index: 0,
    explanation: "Vrai. Les saisons résultent de l'inclinaison de l'axe terrestre ; la Terre est même légèrement plus proche du Soleil en hiver dans l'hémisphère nord.",
    svg_config: null,
  },
  {
    difficulty: 5, category: "histoire-mythe", type: "text", time_limit: 20,
    text: "La Tour Eiffel devait à l'origine être démontée après quelques années.",
    choices: ["Vrai", "Faux"],
    correct_index: 0,
    explanation: "Vrai. Conçue pour l'Exposition de 1889, elle devait être démontée après 20 ans, mais fut sauvée grâce à son utilité comme antenne radio.",
    svg_config: null,
  },

  // ===== DIFFICULTE 6 — INTERMEDIAIRE (20s) =====
  {
    difficulty: 6, category: "science-mythe", type: "text", time_limit: 20,
    text: "Le son se propage plus vite dans l'eau que dans l'air.",
    choices: ["Vrai", "Faux"],
    correct_index: 0,
    explanation: "Vrai. Le son voyage environ quatre fois plus vite dans l'eau (environ 1 480 m/s) que dans l'air (environ 340 m/s).",
    svg_config: null,
  },
  {
    difficulty: 6, category: "corps-mythe", type: "text", time_limit: 20,
    text: "Le sucre rend les enfants hyperactifs.",
    choices: ["Vrai", "Faux"],
    correct_index: 1,
    explanation: "Faux. De nombreuses études contrôlées n'ont trouvé aucun lien entre consommation de sucre et hyperactivité ; l'effet attendu biaise la perception des parents.",
    svg_config: null,
  },
  {
    difficulty: 6, category: "nature-mythe", type: "text", time_limit: 20,
    text: "Les abeilles meurent toujours après avoir piqué.",
    choices: ["Vrai", "Faux"],
    correct_index: 1,
    explanation: "Faux. Seules les abeilles mellifères meurent en piquant un mammifère, car leur dard reste accroché ; elles survivent en piquant d'autres insectes, et les guêpes ne meurent pas.",
    svg_config: null,
  },
  {
    difficulty: 6, category: "histoire-mythe", type: "text", time_limit: 20,
    text: "Les gladiateurs romains combattaient presque toujours à mort.",
    choices: ["Vrai", "Faux"],
    correct_index: 1,
    explanation: "Faux. Les gladiateurs représentaient un investissement coûteux ; la plupart des combats ne se terminaient pas par la mort, qui restait l'exception.",
    svg_config: null,
  },
  {
    difficulty: 6, category: "science-mythe", type: "text", time_limit: 20,
    text: "Le mont Everest est la montagne la plus haute de la Terre mesurée depuis sa base.",
    choices: ["Vrai", "Faux"],
    correct_index: 1,
    explanation: "Faux. L'Everest a le plus haut sommet au-dessus du niveau de la mer, mais le Mauna Kea, mesuré depuis sa base sous-marine, est plus élevé.",
    svg_config: null,
  },
  {
    difficulty: 6, category: "corps-mythe", type: "text", time_limit: 20,
    text: "Les ongles et les cheveux continuent de pousser après la mort.",
    choices: ["Vrai", "Faux"],
    correct_index: 1,
    explanation: "Faux. La peau se rétracte en se déshydratant, donnant l'illusion que ongles et cheveux poussent, mais aucune croissance réelle n'a lieu.",
    svg_config: null,
  },
  {
    difficulty: 6, category: "nature-mythe", type: "text", time_limit: 20,
    text: "Un crocodile pleure réellement de fausses larmes en mangeant.",
    choices: ["Vrai", "Faux"],
    correct_index: 0,
    explanation: "Vrai. Les crocodiles sécrètent bien des larmes en mangeant, probablement à cause de l'air expulsé qui stimule les glandes lacrymales : d'où l'expression.",
    svg_config: null,
  },
  {
    difficulty: 6, category: "culture-mythe", type: "text", time_limit: 20,
    text: "Le chiffre romain pour 4 sur les horloges est souvent IIII au lieu de IV.",
    choices: ["Vrai", "Faux"],
    correct_index: 0,
    explanation: "Vrai. De nombreuses horloges anciennes utilisent IIII plutôt que IV, pour des raisons d'équilibre visuel et de tradition.",
    svg_config: null,
  },
  {
    difficulty: 6, category: "science-mythe", type: "text", time_limit: 20,
    text: "La couleur d'une flamme indique sa température.",
    choices: ["Vrai", "Faux"],
    correct_index: 0,
    explanation: "Vrai. En règle générale, une flamme bleue est plus chaude qu'une flamme jaune ou rouge ; la couleur reflète l'énergie thermique émise.",
    svg_config: null,
  },
  {
    difficulty: 6, category: "histoire-mythe", type: "text", time_limit: 20,
    text: "La rotondité de la Terre était déjà admise par les savants bien avant le voyage de Christophe Colomb.",
    choices: ["Vrai", "Faux"],
    correct_index: 0,
    explanation: "Vrai. Les savants connaissaient la rotondité de la Terre depuis l'Antiquité ; Colomb avait surtout sous-estimé sa circonférence.",
    svg_config: null,
  },

  // ===== DIFFICULTE 7 — DIFFICILE (25s) =====
  {
    difficulty: 7, category: "science-mythe", type: "text", time_limit: 25,
    text: "Un objet métallique chaud et un objet en bois à la même température semblent aussi chauds au toucher.",
    choices: ["Vrai", "Faux"],
    correct_index: 1,
    explanation: "Faux. Le métal conduit la chaleur bien plus vite que le bois ; à température égale, le métal paraît plus chaud (ou plus froid) au toucher.",
    svg_config: null,
  },
  {
    difficulty: 7, category: "corps-mythe", type: "text", time_limit: 25,
    text: "Les humains et les dinosaures n'ont jamais coexisté.",
    choices: ["Vrai", "Faux"],
    correct_index: 1,
    explanation: "Faux. Les oiseaux sont des dinosaures théropodes ; au sens strict, des dinosaures vivants côtoient donc l'humain. Les dinosaures non aviens, eux, avaient disparu.",
    svg_config: null,
  },
  {
    difficulty: 7, category: "histoire-mythe", type: "text", time_limit: 25,
    text: "La guillotine était encore utilisée en France dans les années 1970.",
    choices: ["Vrai", "Faux"],
    correct_index: 0,
    explanation: "Vrai. La dernière exécution par guillotine en France a eu lieu en 1977, avant l'abolition de la peine de mort en 1981.",
    svg_config: null,
  },
  {
    difficulty: 7, category: "nature-mythe", type: "text", time_limit: 25,
    text: "Les manchots peuvent boire de l'eau de mer salée.",
    choices: ["Vrai", "Faux"],
    correct_index: 0,
    explanation: "Vrai. Les manchots possèdent une glande à sel près des yeux qui filtre et évacue l'excès de sel, leur permettant de boire de l'eau de mer.",
    svg_config: null,
  },
  {
    difficulty: 7, category: "science-mythe", type: "text", time_limit: 25,
    text: "Vénus est la planète la plus chaude du système solaire, bien qu'elle ne soit pas la plus proche du Soleil.",
    choices: ["Vrai", "Faux"],
    correct_index: 0,
    explanation: "Vrai. L'épais effet de serre de son atmosphère de CO2 maintient Vénus à environ 460 °C, plus chaude que Mercure pourtant plus proche du Soleil.",
    svg_config: null,
  },
  {
    difficulty: 7, category: "corps-mythe", type: "text", time_limit: 25,
    text: "On ne peut pas attraper un rhume simplement parce qu'on a froid.",
    choices: ["Vrai", "Faux"],
    correct_index: 0,
    explanation: "Vrai. Le rhume est causé par des virus ; le froid ne le provoque pas directement, même s'il peut favoriser leur transmission en hiver.",
    svg_config: null,
  },
  {
    difficulty: 7, category: "culture-mythe", type: "text", time_limit: 25,
    text: "La devise « In God We Trust » figure sur les billets américains depuis la fondation des États-Unis.",
    choices: ["Vrai", "Faux"],
    correct_index: 1,
    explanation: "Faux. Cette devise n'est devenue officielle qu'en 1956 et n'apparaît sur les billets que depuis 1957.",
    svg_config: null,
  },
  {
    difficulty: 7, category: "nature-mythe", type: "text", time_limit: 25,
    text: "Le koala n'est pas un ours.",
    choices: ["Vrai", "Faux"],
    correct_index: 0,
    explanation: "Vrai. Le koala est un marsupial, sans aucun lien de parenté avec les ours ; l'appellation « ours koala » est trompeuse.",
    svg_config: null,
  },
  {
    difficulty: 7, category: "histoire-mythe", type: "text", time_limit: 25,
    text: "Einstein a refusé un poste de président d'État qu'on lui avait proposé.",
    choices: ["Vrai", "Faux"],
    correct_index: 0,
    explanation: "Vrai. En 1952, on proposa à Einstein la présidence de l'État d'Israël, qu'il déclina poliment.",
    svg_config: null,
  },
  {
    difficulty: 7, category: "science-mythe", type: "text", time_limit: 25,
    text: "Le diamant est la substance naturelle connue la plus dure et rien ne peut le rayer.",
    choices: ["Vrai", "Faux"],
    correct_index: 1,
    explanation: "Faux. Le diamant est le minéral naturel le plus dur, mais il peut être rayé par un autre diamant, et des matériaux comme certains nanomatériaux le surpassent.",
    svg_config: null,
  },

  // ===== DIFFICULTE 8 — DIFFICILE (25s) =====
  {
    difficulty: 8, category: "science-mythe", type: "text", time_limit: 25,
    text: "Le sens de rotation du tourbillon d'un évier dépend de l'hémisphère où l'on se trouve.",
    choices: ["Vrai", "Faux"],
    correct_index: 1,
    explanation: "Faux. À l'échelle d'un évier, la force de Coriolis est négligeable ; la forme du bassin et le mouvement initial de l'eau déterminent le sens.",
    svg_config: null,
  },
  {
    difficulty: 8, category: "histoire-mythe", type: "text", time_limit: 25,
    text: "Oxford, l'université, est plus ancienne que l'Empire aztèque.",
    choices: ["Vrai", "Faux"],
    correct_index: 0,
    explanation: "Vrai. L'enseignement à Oxford remonte au moins au XIe siècle, tandis que Tenochtitlan, capitale aztèque, fut fondée en 1325.",
    svg_config: null,
  },
  {
    difficulty: 8, category: "corps-mythe", type: "text", time_limit: 25,
    text: "L'estomac humain produit un acide capable de dissoudre une lame de rasoir.",
    choices: ["Vrai", "Faux"],
    correct_index: 0,
    explanation: "Vrai. L'acide chlorhydrique gastrique est assez puissant pour attaquer des métaux comme le fer ; une muqueuse renouvelée protège l'estomac de lui-même.",
    svg_config: null,
  },
  {
    difficulty: 8, category: "nature-mythe", type: "text", time_limit: 25,
    text: "Les bébés naissent avec plus d'os que les adultes.",
    choices: ["Vrai", "Faux"],
    correct_index: 0,
    explanation: "Vrai. Un nouveau-né a environ 300 os qui fusionnent en grandissant pour aboutir aux 206 os de l'adulte.",
    svg_config: null,
  },
  {
    difficulty: 8, category: "science-mythe", type: "text", time_limit: 25,
    text: "Mars apparaît parfois aussi grosse que la Lune dans le ciel nocturne.",
    choices: ["Vrai", "Faux"],
    correct_index: 1,
    explanation: "Faux. C'est un canular récurrent : Mars reste toujours un point lumineux à l'œil nu, jamais comparable à la Lune.",
    svg_config: null,
  },
  {
    difficulty: 8, category: "culture-mythe", type: "text", time_limit: 25,
    text: "Le célèbre cri de Tarzan a été créé à partir de plusieurs sons mixés en studio.",
    choices: ["Vrai", "Faux"],
    correct_index: 0,
    explanation: "Vrai. Le cri emblématique des films des années 1930 résulte d'un montage sonore combinant plusieurs enregistrements, et non d'un seul cri humain.",
    svg_config: null,
  },
  {
    difficulty: 8, category: "histoire-mythe", type: "text", time_limit: 25,
    text: "La guerre la plus courte de l'histoire a duré moins d'une heure.",
    choices: ["Vrai", "Faux"],
    correct_index: 0,
    explanation: "Vrai. La guerre anglo-zanzibarienne de 1896 a duré environ 38 à 45 minutes, ce qui en fait la plus courte guerre documentée.",
    svg_config: null,
  },
  {
    difficulty: 8, category: "nature-mythe", type: "text", time_limit: 25,
    text: "Les éléphants sont les seuls mammifères incapables de sauter.",
    choices: ["Vrai", "Faux"],
    correct_index: 1,
    explanation: "Faux. S'il est vrai que les éléphants adultes ne sautent pas, ils ne sont pas les seuls : les paresseux, hippopotames et rhinocéros ne sautent pas non plus.",
    svg_config: null,
  },
  {
    difficulty: 8, category: "science-mythe", type: "text", time_limit: 25,
    text: "Un kilogramme de plumes pèse autant qu'un kilogramme de plomb.",
    choices: ["Vrai", "Faux"],
    correct_index: 0,
    explanation: "Vrai. Par définition, un kilogramme égale un kilogramme ; seul le volume diffère, pas la masse.",
    svg_config: null,
  },
  {
    difficulty: 8, category: "corps-mythe", type: "text", time_limit: 25,
    text: "L'humain partage environ 50 % de son ADN avec une banane.",
    choices: ["Vrai", "Faux"],
    correct_index: 0,
    explanation: "Vrai. En comparant les gènes communs au vivant, on estime que l'humain partage de l'ordre de 50 % de ses gènes avec la banane.",
    svg_config: null,
  },

  // ===== DIFFICULTE 9 — TRES DIFFICILE (30s) =====
  {
    difficulty: 9, category: "science-mythe", type: "text", time_limit: 30,
    text: "Le miel est techniquement du vomi d'abeille.",
    choices: ["Vrai", "Faux"],
    correct_index: 1,
    explanation: "Faux. Le nectar est stocké dans un jabot spécialisé (l'estomac à miel), distinct de l'estomac digestif ; il n'est pas digéré, donc parler de « vomi » est inexact.",
    svg_config: null,
  },
  {
    difficulty: 9, category: "histoire-mythe", type: "text", time_limit: 30,
    text: "Cléopâtre a vécu plus près dans le temps de l'invention du smartphone que de la construction de la grande pyramide de Khéops.",
    choices: ["Vrai", "Faux"],
    correct_index: 0,
    explanation: "Vrai. La pyramide de Khéops date d'environ 2560 av. J.-C. et Cléopâtre vivait vers 30 av. J.-C., soit plus proche de notre époque que de la pyramide.",
    svg_config: null,
  },
  {
    difficulty: 9, category: "corps-mythe", type: "text", time_limit: 30,
    text: "La langue n'est pas le muscle le plus fort du corps humain.",
    choices: ["Vrai", "Faux"],
    correct_index: 0,
    explanation: "Vrai. La langue est endurante mais pas la plus puissante ; selon le critère retenu, le masséter (mâchoire) ou le grand fessier sont bien plus forts.",
    svg_config: null,
  },
  {
    difficulty: 9, category: "nature-mythe", type: "text", time_limit: 30,
    text: "Certaines tortues respirent en partie par leur arrière-train.",
    choices: ["Vrai", "Faux"],
    correct_index: 0,
    explanation: "Vrai. Plusieurs espèces de tortues d'eau peuvent absorber de l'oxygène via des tissus très vascularisés du cloaque, ce qui les aide à hiverner sous l'eau.",
    svg_config: null,
  },
  {
    difficulty: 9, category: "science-mythe", type: "text", time_limit: 30,
    text: "La lumière du Soleil que nous voyons a été émise il y a environ huit minutes.",
    choices: ["Vrai", "Faux"],
    correct_index: 0,
    explanation: "Vrai. La lumière met environ 8 minutes et 20 secondes à parcourir les 150 millions de kilomètres entre le Soleil et la Terre.",
    svg_config: null,
  },
  {
    difficulty: 9, category: "culture-mythe", type: "text", time_limit: 30,
    text: "Le célèbre « effet placebo » fonctionne aussi quand le patient sait qu'il prend un placebo.",
    choices: ["Vrai", "Faux"],
    correct_index: 0,
    explanation: "Vrai. Des études sur le placebo « ouvert » montrent un effet bénéfique mesurable sur certains symptômes même lorsque le patient sait qu'il s'agit d'un placebo.",
    svg_config: null,
  },
  {
    difficulty: 9, category: "histoire-mythe", type: "text", time_limit: 30,
    text: "Les mammouths laineux existaient encore quand les pyramides d'Égypte étaient déjà construites.",
    choices: ["Vrai", "Faux"],
    correct_index: 0,
    explanation: "Vrai. Une population de mammouths a survécu sur l'île Wrangel jusqu'à environ 2000 av. J.-C., après la construction des grandes pyramides.",
    svg_config: null,
  },
  {
    difficulty: 9, category: "nature-mythe", type: "text", time_limit: 30,
    text: "Les flamants roses naissent déjà roses.",
    choices: ["Vrai", "Faux"],
    correct_index: 1,
    explanation: "Faux. Les flamants naissent gris ; leur couleur rose vient des pigments (caroténoïdes) présents dans leur alimentation, comme les crustacés.",
    svg_config: null,
  },
  {
    difficulty: 9, category: "science-mythe", type: "text", time_limit: 30,
    text: "L'espace n'est pas totalement silencieux : le son peut s'y propager dans certains milieux denses.",
    choices: ["Vrai", "Faux"],
    correct_index: 0,
    explanation: "Vrai. Dans le vide quasi parfait, le son ne se propage pas, mais dans des milieux comme les nuages de gaz d'amas galactiques, des ondes sonores existent.",
    svg_config: null,
  },
  {
    difficulty: 9, category: "corps-mythe", type: "text", time_limit: 30,
    text: "Les vrais jumeaux ont exactement le même ADN tout au long de leur vie.",
    choices: ["Vrai", "Faux"],
    correct_index: 1,
    explanation: "Faux. Ils partent du même ADN, mais des mutations apparaissent dès le développement et au fil de la vie, créant de petites différences génétiques.",
    svg_config: null,
  },

  // ===== DIFFICULTE 10 — PIEGE D'EXPERT (30s) =====
  {
    difficulty: 10, category: "science-mythe", type: "text", time_limit: 30,
    text: "Le chiffre du « nombre de couleurs de l'arc-en-ciel » à sept a été fixé par Isaac Newton.",
    choices: ["Vrai", "Faux"],
    correct_index: 0,
    explanation: "Vrai. Newton a choisi d'y voir sept couleurs, ajoutant l'indigo, par analogie avec les sept notes de la gamme musicale ; le spectre est en réalité continu.",
    svg_config: null,
  },
  {
    difficulty: 10, category: "histoire-mythe", type: "text", time_limit: 30,
    text: "La célèbre « défenestration de Prague » a été suivie par la survie des personnes jetées par la fenêtre.",
    choices: ["Vrai", "Faux"],
    correct_index: 0,
    explanation: "Vrai. Lors de la défenestration de 1618, les hommes jetés survécurent à la chute, amortie selon les récits par un tas de fumier ou la grâce divine.",
    svg_config: null,
  },
  {
    difficulty: 10, category: "nature-mythe", type: "text", time_limit: 30,
    text: "Le wombat produit des excréments de forme cubique.",
    choices: ["Vrai", "Faux"],
    correct_index: 0,
    explanation: "Vrai. Le wombat est le seul animal connu à produire des crottes en forme de cube, grâce à l'élasticité variable de ses intestins.",
    svg_config: null,
  },
  {
    difficulty: 10, category: "science-mythe", type: "text", time_limit: 30,
    text: "Le métal gallium fond dans la main à la chaleur du corps humain.",
    choices: ["Vrai", "Faux"],
    correct_index: 0,
    explanation: "Vrai. Le gallium fond à environ 29,8 °C, en dessous de la température du corps, et se liquéfie donc dans une main chaude.",
    svg_config: null,
  },
  {
    difficulty: 10, category: "corps-mythe", type: "text", time_limit: 30,
    text: "L'appendice humain ne sert strictement à rien.",
    choices: ["Vrai", "Faux"],
    correct_index: 1,
    explanation: "Faux. Longtemps jugé inutile, l'appendice servirait de réservoir pour les bonnes bactéries intestinales, aidant à recoloniser l'intestin après une infection.",
    svg_config: null,
  },
  {
    difficulty: 10, category: "histoire-mythe", type: "text", time_limit: 30,
    text: "Napoléon a été attaqué par une horde de lapins lors d'une partie de chasse.",
    choices: ["Vrai", "Faux"],
    correct_index: 0,
    explanation: "Vrai. Lors d'une chasse organisée, des lapins domestiques relâchés se ruèrent vers Napoléon au lieu de fuir, l'épisode est rapporté par plusieurs sources.",
    svg_config: null,
  },
  {
    difficulty: 10, category: "nature-mythe", type: "text", time_limit: 30,
    text: "Les méduses sont composées à plus de 95 % d'eau.",
    choices: ["Vrai", "Faux"],
    correct_index: 0,
    explanation: "Vrai. Le corps d'une méduse est constitué d'environ 95 à 98 % d'eau, ce qui explique qu'elle se dessèche presque entièrement hors de l'eau.",
    svg_config: null,
  },
  {
    difficulty: 10, category: "science-mythe", type: "text", time_limit: 30,
    text: "Le verre ordinaire bloque l'essentiel des UVB responsables des coups de soleil.",
    choices: ["Vrai", "Faux"],
    correct_index: 0,
    explanation: "Vrai. Le verre ordinaire arrête l'essentiel des UVB responsables des coups de soleil ; on bronze peu derrière une vitre, même si des UVA passent.",
    svg_config: null,
  },
  {
    difficulty: 10, category: "culture-mythe", type: "text", time_limit: 30,
    text: "Le mot « OK » est l'une des expressions les plus universellement comprises au monde.",
    choices: ["Vrai", "Faux"],
    correct_index: 0,
    explanation: "Vrai. « OK » est considéré comme l'un des mots les plus reconnus et utilisés à travers les langues et les cultures du monde.",
    svg_config: null,
  },
  {
    difficulty: 10, category: "histoire-mythe", type: "text", time_limit: 30,
    text: "Les Romains de l'Antiquité utilisaient l'urine comme produit pour blanchir les dents.",
    choices: ["Vrai", "Faux"],
    correct_index: 0,
    explanation: "Vrai. L'ammoniac contenu dans l'urine, parfois importée, servait de blanchissant ; les Romains s'en servaient aussi pour nettoyer le linge.",
    svg_config: null,
  },
];
