import type { Question } from "./types";

export const questionsActualite: Omit<Question, "id">[] = [
  // ===== DIFFICULTE 1 — TRIVIAL (15s) =====
  {
    difficulty: 1, category: "politique-monde", type: "text", time_limit: 15,
    text: "Quel président américain a pris ses fonctions le 20 janvier 2025 ?",
    choices: ["Joe Biden", "Donald Trump", "Kamala Harris", "Ron DeSantis"],
    correct_index: 1,
    explanation: "Donald Trump a été investi 47e président des États-Unis le 20 janvier 2025, pour un second mandat non consécutif.",
    svg_config: null,
  },
  {
    difficulty: 1, category: "politique-fr", type: "text", time_limit: 15,
    text: "Qui est devenu Premier ministre de la France en décembre 2024, toujours en poste début 2025 ?",
    choices: ["Michel Barnier", "François Bayrou", "Gabriel Attal", "Édouard Philippe"],
    correct_index: 1,
    explanation: "François Bayrou a été nommé Premier ministre le 13 décembre 2024 par Emmanuel Macron, après la censure du gouvernement Barnier.",
    svg_config: null,
  },
  {
    difficulty: 1, category: "tech", type: "text", time_limit: 15,
    text: "Quelle application chinoise d'IA a surpris le monde en janvier 2025 par ses performances avec un budget réduit ?",
    choices: ["Baidu AI", "DeepSeek", "Alibaba Cloud AI", "ByteDance GPT"],
    correct_index: 1,
    explanation: "DeepSeek, startup chinoise, a lancé son modèle R1 en janvier 2025, rivalisant avec les meilleurs modèles occidentaux pour une fraction du coût.",
    svg_config: null,
  },
  {
    difficulty: 1, category: "sport", type: "text", time_limit: 15,
    text: "Quelle équipe a remporté le Super Bowl LIX en février 2025 ?",
    choices: ["Kansas City Chiefs", "Philadelphia Eagles", "San Francisco 49ers", "Baltimore Ravens"],
    correct_index: 1,
    explanation: "Les Philadelphia Eagles ont battu les Kansas City Chiefs lors du Super Bowl LIX le 9 février 2025 à la Nouvelle-Orléans.",
    svg_config: null,
  },
  {
    difficulty: 1, category: "politique-monde", type: "text", time_limit: 15,
    text: "Quel réseau social a failli être interdit aux États-Unis début janvier 2025 ?",
    choices: ["Instagram", "X (Twitter)", "TikTok", "Snapchat"],
    correct_index: 2,
    explanation: "TikTok a brièvement été interdit aux États-Unis le 19 janvier 2025 avant que Donald Trump ne signe un décret suspendant l'interdiction.",
    svg_config: null,
  },
  {
    difficulty: 1, category: "culture", type: "text", time_limit: 15,
    text: "Quel film a remporté l'Oscar du meilleur film lors de la cérémonie de mars 2025 ?",
    choices: ["The Brutalist", "Anora", "Conclave", "Emilia Pérez"],
    correct_index: 1,
    explanation: "Anora, réalisé par Sean Baker, a remporté l'Oscar du meilleur film lors de la 97e cérémonie des Oscars en mars 2025.",
    svg_config: null,
  },
  {
    difficulty: 1, category: "societe", type: "text", time_limit: 15,
    text: "Quel événement catastrophique a frappé Los Angeles en janvier 2025 ?",
    choices: ["Un tremblement de terre", "Des incendies majeurs", "Une inondation", "Un ouragan"],
    correct_index: 1,
    explanation: "Des incendies dévastateurs ont ravagé Los Angeles en janvier 2025, notamment dans les quartiers de Pacific Palisades et Altadena, causant des milliards de dollars de dégâts.",
    svg_config: null,
  },
  {
    difficulty: 1, category: "politique-monde", type: "text", time_limit: 15,
    text: "Quel pays Donald Trump a-t-il menacé d'annexer début 2025 ?",
    choices: ["Mexique", "Canada", "Cuba", "Groenland"],
    correct_index: 3,
    explanation: "Donald Trump a exprimé à plusieurs reprises sa volonté d'acquérir le Groenland début 2025, provoquant des tensions diplomatiques avec le Danemark.",
    svg_config: null,
  },
  {
    difficulty: 1, category: "sport", type: "text", time_limit: 15,
    text: "Quel pays a accueilli la Coupe du Monde des Clubs FIFA en été 2025 ?",
    choices: ["Qatar", "Arabie Saoudite", "États-Unis", "Chine"],
    correct_index: 2,
    explanation: "La Coupe du Monde des Clubs FIFA 2025 s'est tenue aux États-Unis, avec 32 équipes participantes dans un nouveau format élargi.",
    svg_config: null,
  },
  {
    difficulty: 1, category: "economie", type: "text", time_limit: 15,
    text: "Quelle mesure économique majeure Donald Trump a-t-il mise en place dès son investiture en 2025 ?",
    choices: ["Baisse de l'impôt sur le revenu", "Augmentation des droits de douane", "Création d'une monnaie numérique", "Nationalisation des banques"],
    correct_index: 1,
    explanation: "Donald Trump a imposé des droits de douane massifs dès 2025, notamment sur les importations chinoises, canadiennes et mexicaines.",
    svg_config: null,
  },

  // ===== DIFFICULTE 2 — FACILE (15s) =====
  {
    difficulty: 2, category: "tech", type: "text", time_limit: 15,
    text: "Quel géant de la tech a lancé le modèle d'IA Gemini 2.0 début 2025 ?",
    choices: ["Microsoft", "Apple", "Google", "Meta"],
    correct_index: 2,
    explanation: "Google a lancé Gemini 2.0 début 2025, avec des capacités multimodales avancées et une intégration renforcée dans ses produits.",
    svg_config: null,
  },
  {
    difficulty: 2, category: "politique-fr", type: "text", time_limit: 15,
    text: "Quel article de la Constitution François Bayrou a-t-il utilisé début 2025 pour faire passer le budget ?",
    choices: ["Article 16", "Article 49.3", "Article 89", "Article 11"],
    correct_index: 1,
    explanation: "François Bayrou a eu recours à l'article 49.3 pour faire adopter le budget 2025 sans vote de l'Assemblée nationale.",
    svg_config: null,
  },
  {
    difficulty: 2, category: "sport", type: "text", time_limit: 15,
    text: "Quel joueur de tennis a remporté l'Open d'Australie masculin en janvier 2025 ?",
    choices: ["Novak Djokovic", "Jannik Sinner", "Carlos Alcaraz", "Alexander Zverev"],
    correct_index: 1,
    explanation: "Jannik Sinner a remporté l'Open d'Australie 2025, défendant avec succès son titre de l'année précédente.",
    svg_config: null,
  },
  {
    difficulty: 2, category: "politique-monde", type: "text", time_limit: 15,
    text: "Quel département gouvernemental Elon Musk a-t-il dirigé sous Trump en 2025 ?",
    choices: ["Département de la Défense", "NASA", "DOGE (Department of Government Efficiency)", "Département du Commerce"],
    correct_index: 2,
    explanation: "Elon Musk a pris la tête du DOGE (Department of Government Efficiency) en 2025, chargé de réduire les dépenses fédérales américaines.",
    svg_config: null,
  },
  {
    difficulty: 2, category: "culture", type: "text", time_limit: 15,
    text: "Quelle actrice a remporté l'Oscar de la meilleure actrice en mars 2025 ?",
    choices: ["Demi Moore", "Mikey Madison", "Cynthia Erivo", "Fernanda Torres"],
    correct_index: 0,
    explanation: "Demi Moore a remporté son premier Oscar pour son rôle dans The Substance lors de la 97e cérémonie des Oscars.",
    svg_config: null,
  },
  {
    difficulty: 2, category: "science", type: "text", time_limit: 15,
    text: "Quelle entreprise spatiale a réussi à rattraper un booster de fusée avec des bras mécaniques en 2025 ?",
    choices: ["Blue Origin", "SpaceX", "Rocket Lab", "Arianespace"],
    correct_index: 1,
    explanation: "SpaceX a continué à perfectionner la récupération de son booster Super Heavy avec les bras Mechazilla de la tour de lancement en 2025.",
    svg_config: null,
  },
  {
    difficulty: 2, category: "economie", type: "text", time_limit: 15,
    text: "Quel seuil symbolique le Bitcoin a-t-il franchi pour la première fois début 2025 ?",
    choices: ["50 000 dollars", "75 000 dollars", "100 000 dollars", "150 000 dollars"],
    correct_index: 2,
    explanation: "Le Bitcoin a franchi le cap des 100 000 dollars fin 2024 et a maintenu ce niveau début 2025, porté par l'élection de Trump favorable aux cryptomonnaies.",
    svg_config: null,
  },
  {
    difficulty: 2, category: "environnement", type: "text", time_limit: 15,
    text: "De quel accord international sur le climat Donald Trump a-t-il retiré les États-Unis dès son investiture en 2025 ?",
    choices: ["Protocole de Kyoto", "Accord de Paris", "Protocole de Montréal", "Accord de Glasgow"],
    correct_index: 1,
    explanation: "Donald Trump a signé un décret exécutif retirant les États-Unis de l'Accord de Paris sur le climat dès le 20 janvier 2025.",
    svg_config: null,
  },
  {
    difficulty: 2, category: "societe", type: "text", time_limit: 15,
    text: "Quel geste controversé Elon Musk a-t-il fait lors de l'investiture de Trump en janvier 2025 ?",
    choices: ["Il a chanté l'hymne national", "Il a fait un salut bras tendu", "Il a refusé de serrer la main de Trump", "Il a lancé un drone"],
    correct_index: 1,
    explanation: "Elon Musk a provoqué une vive polémique en faisant un geste bras tendu lors de l'investiture de Trump, que beaucoup ont comparé à un salut fasciste.",
    svg_config: null,
  },
  {
    difficulty: 2, category: "politique-monde", type: "text", time_limit: 15,
    text: "Quel canal les États-Unis ont-ils menacé de reprendre sous Trump début 2025 ?",
    choices: ["Canal de Suez", "Canal de Kiel", "Canal de Panama", "Canal de Corinthe"],
    correct_index: 2,
    explanation: "Donald Trump a évoqué la possibilité de reprendre le contrôle du canal de Panama début 2025, provoquant la colère du gouvernement panaméen.",
    svg_config: null,
  },

  // ===== DIFFICULTE 3 — FACILE+ (15s) =====
  {
    difficulty: 3, category: "tech", type: "text", time_limit: 15,
    text: "Quel modèle d'IA chinois a provoqué une chute des marchés boursiers tech américains en janvier 2025 ?",
    choices: ["Qwen 2.5", "DeepSeek R1", "Baichuan 4", "Yi-Lightning"],
    correct_index: 1,
    explanation: "La sortie de DeepSeek R1 en janvier 2025 a fait chuter les marchés tech américains, notamment Nvidia, car le modèle rivalisait avec les leaders pour un coût très inférieur.",
    svg_config: null,
  },
  {
    difficulty: 3, category: "politique-fr", type: "text", time_limit: 15,
    text: "Quel parti politique François Bayrou dirige-t-il ?",
    choices: ["Les Républicains", "Le MoDem", "Renaissance", "Le Parti socialiste"],
    correct_index: 1,
    explanation: "François Bayrou est le président du MoDem (Mouvement Démocrate), parti centriste allié de la majorité présidentielle.",
    svg_config: null,
  },
  {
    difficulty: 3, category: "sport", type: "text", time_limit: 15,
    text: "Quelle joueuse de tennis a remporté l'Open d'Australie féminin en janvier 2025 ?",
    choices: ["Aryna Sabalenka", "Iga Swiatek", "Coco Gauff", "Madison Keys"],
    correct_index: 3,
    explanation: "Madison Keys a remporté l'Open d'Australie 2025 en battant Aryna Sabalenka en finale.",
    svg_config: null,
  },
  {
    difficulty: 3, category: "culture", type: "text", time_limit: 15,
    text: "Quel film musical avec des acteurs hispanophones a créé la polémique aux Oscars 2025 ?",
    choices: ["In the Heights", "West Side Story", "Emilia Pérez", "Coco"],
    correct_index: 2,
    explanation: "Emilia Pérez de Jacques Audiard a suscité des controverses malgré ses nombreuses nominations, notamment sur la représentation de la culture mexicaine.",
    svg_config: null,
  },
  {
    difficulty: 3, category: "economie", type: "text", time_limit: 15,
    text: "Quel pourcentage de droits de douane Trump a-t-il imposé sur les importations chinoises début 2025 ?",
    choices: ["10%", "20%", "25%", "50%"],
    correct_index: 1,
    explanation: "Trump a imposé des droits de douane supplémentaires de 20% sur les importations chinoises début 2025, s'ajoutant aux tarifs existants.",
    svg_config: null,
  },
  {
    difficulty: 3, category: "science", type: "text", time_limit: 15,
    text: "Quel événement astronomique rare s'est produit en mars 2025, visible depuis l'Europe ?",
    choices: ["Une éclipse solaire totale", "Une éclipse lunaire totale", "Le passage d'une comète brillante", "Une pluie de météorites exceptionnelle"],
    correct_index: 1,
    explanation: "Une éclipse lunaire totale a été visible depuis l'Europe le 14 mars 2025.",
    svg_config: null,
  },
  {
    difficulty: 3, category: "politique-monde", type: "text", time_limit: 15,
    text: "Quel pays européen a connu des élections fédérales en février 2025 ?",
    choices: ["France", "Italie", "Allemagne", "Espagne"],
    correct_index: 2,
    explanation: "L'Allemagne a tenu des élections fédérales anticipées le 23 février 2025 après la chute de la coalition d'Olaf Scholz.",
    svg_config: null,
  },
  {
    difficulty: 3, category: "societe", type: "text", time_limit: 15,
    text: "Quelle célébrité a lancé sa propre cryptomonnaie mème juste avant son investiture en janvier 2025 ?",
    choices: ["Elon Musk", "Donald Trump", "Kanye West", "Mark Zuckerberg"],
    correct_index: 1,
    explanation: "Donald Trump a lancé le token $TRUMP, un memecoin, quelques jours avant son investiture le 20 janvier 2025.",
    svg_config: null,
  },
  {
    difficulty: 3, category: "environnement", type: "text", time_limit: 15,
    text: "Dans quelle ville brésilienne doit se tenir la COP30 en novembre 2025 ?",
    choices: ["Rio de Janeiro", "São Paulo", "Belém", "Brasília"],
    correct_index: 2,
    explanation: "La COP30 est prévue à Belém, au Brésil, en novembre 2025, au cœur de l'Amazonie.",
    svg_config: null,
  },
  {
    difficulty: 3, category: "tech", type: "text", time_limit: 15,
    text: "Quelle entreprise a lancé le modèle d'IA Claude 3.5 début 2025 ?",
    choices: ["OpenAI", "Google", "Anthropic", "Meta"],
    correct_index: 2,
    explanation: "Anthropic a lancé Claude 3.5 Sonnet début 2025, s'imposant comme un concurrent sérieux de ChatGPT et Gemini.",
    svg_config: null,
  },

  // ===== DIFFICULTE 4 — MOYEN- (20s) =====
  {
    difficulty: 4, category: "politique-monde", type: "text", time_limit: 20,
    text: "Qui a remporté les élections fédérales allemandes de février 2025 ?",
    choices: ["Olaf Scholz (SPD)", "Friedrich Merz (CDU/CSU)", "Alice Weidel (AfD)", "Robert Habeck (Verts)"],
    correct_index: 1,
    explanation: "Friedrich Merz et la CDU/CSU ont remporté les élections fédérales allemandes du 23 février 2025.",
    svg_config: null,
  },
  {
    difficulty: 4, category: "sport", type: "text", time_limit: 20,
    text: "Quel pays a remporté le Tournoi des Six Nations de rugby en 2025 ?",
    choices: ["France", "Irlande", "Angleterre", "Écosse"],
    correct_index: 1,
    explanation: "L'Irlande a remporté le Tournoi des Six Nations 2025.",
    svg_config: null,
  },
  {
    difficulty: 4, category: "tech", type: "text", time_limit: 20,
    text: "Quel produit révolutionnaire Apple a-t-il mis en vente début 2025 en élargissant sa disponibilité mondiale ?",
    choices: ["iPhone 17", "Apple Car", "Apple Vision Pro", "Apple Ring"],
    correct_index: 2,
    explanation: "L'Apple Vision Pro, casque de réalité mixte d'Apple, a élargi sa disponibilité internationale début 2025 après son lancement initial aux États-Unis en 2024.",
    svg_config: null,
  },
  {
    difficulty: 4, category: "culture", type: "text", time_limit: 20,
    text: "Quel acteur a remporté l'Oscar du meilleur acteur en mars 2025 ?",
    choices: ["Timothée Chalamet", "Adrien Brody", "Ralph Fiennes", "Sebastian Stan"],
    correct_index: 1,
    explanation: "Adrien Brody a remporté l'Oscar du meilleur acteur pour son rôle dans The Brutalist de Brady Corbet.",
    svg_config: null,
  },
  {
    difficulty: 4, category: "economie", type: "text", time_limit: 20,
    text: "Quelle entreprise technologique est devenue la première à atteindre une capitalisation de 4 000 milliards de dollars début 2025 ?",
    choices: ["Microsoft", "Apple", "Nvidia", "Google"],
    correct_index: 1,
    explanation: "Apple a brièvement atteint une capitalisation boursière de 4 000 milliards de dollars début 2025.",
    svg_config: null,
  },
  {
    difficulty: 4, category: "politique-fr", type: "text", time_limit: 20,
    text: "Quelle réforme controversée adoptée en 2023 a continué de provoquer des manifestations en France début 2025 ?",
    choices: ["Réforme du chômage", "Réforme des retraites", "Réforme de l'immigration", "Réforme de l'éducation"],
    correct_index: 1,
    explanation: "La réforme des retraites portant l'âge légal à 64 ans, adoptée en 2023, a continué de susciter des tensions sociales en 2025.",
    svg_config: null,
  },
  {
    difficulty: 4, category: "science", type: "text", time_limit: 20,
    text: "Quel médicament amaigrissant a continué de dominer l'actualité médicale en 2025 ?",
    choices: ["Metformine", "Ozempic (sémaglutide)", "Xenical", "Saxenda"],
    correct_index: 1,
    explanation: "L'Ozempic et les médicaments à base de sémaglutide/tirzépatide ont continué de dominer l'actualité santé en 2025 avec de nouvelles applications thérapeutiques.",
    svg_config: null,
  },
  {
    difficulty: 4, category: "environnement", type: "text", time_limit: 20,
    text: "Quelle année a été officiellement confirmée comme la plus chaude jamais enregistrée début 2025 ?",
    choices: ["2022", "2023", "2024", "2025"],
    correct_index: 2,
    explanation: "2024 a été confirmée début 2025 comme l'année la plus chaude jamais enregistrée, avec une température moyenne dépassant 1,5°C au-dessus des niveaux préindustriels.",
    svg_config: null,
  },
  {
    difficulty: 4, category: "societe", type: "text", time_limit: 20,
    text: "Combien de personnes au minimum ont été tuées dans les incendies de Los Angeles en janvier 2025 ?",
    choices: ["5", "11", "24", "50"],
    correct_index: 2,
    explanation: "Les incendies de Los Angeles en janvier 2025 ont tué au moins 24 personnes et détruit des milliers de structures.",
    svg_config: null,
  },
  {
    difficulty: 4, category: "politique-monde", type: "text", time_limit: 20,
    text: "Quel pays Trump a-t-il menacé de frapper de droits de douane de 25% en février 2025, provoquant une crise diplomatique nord-américaine ?",
    choices: ["Brésil et Argentine", "Canada et Mexique", "Japon et Corée du Sud", "Inde et Vietnam"],
    correct_index: 1,
    explanation: "Trump a imposé des droits de douane de 25% sur les importations du Canada et du Mexique début février 2025, provoquant des représailles et une crise commerciale.",
    svg_config: null,
  },

  // ===== DIFFICULTE 5 — MOYEN (20s) =====
  {
    difficulty: 5, category: "tech", type: "text", time_limit: 20,
    text: "Quel modèle d'IA d'OpenAI, spécialisé dans le raisonnement, a été lancé début 2025 ?",
    choices: ["GPT-5", "o3", "DALL-E 4", "Sora Pro"],
    correct_index: 1,
    explanation: "OpenAI a lancé le modèle o3 début 2025, successeur de o1, spécialisé dans le raisonnement avancé et la résolution de problèmes complexes.",
    svg_config: null,
  },
  {
    difficulty: 5, category: "politique-fr", type: "text", time_limit: 20,
    text: "Quel événement politique a conduit à la nomination de François Bayrou comme Premier ministre ?",
    choices: ["La démission d'Emmanuel Macron", "La dissolution de l'Assemblée nationale", "La censure du gouvernement Barnier", "Des élections sénatoriales"],
    correct_index: 2,
    explanation: "Le gouvernement de Michel Barnier a été renversé par une motion de censure le 4 décembre 2024, conduisant à la nomination de François Bayrou.",
    svg_config: null,
  },
  {
    difficulty: 5, category: "sport", type: "text", time_limit: 20,
    text: "Quel pilote a remporté le championnat du monde de Formule 1 en 2024, célébré début 2025 ?",
    choices: ["Lewis Hamilton", "Max Verstappen", "Lando Norris", "Charles Leclerc"],
    correct_index: 1,
    explanation: "Max Verstappen a remporté son quatrième titre mondial consécutif de F1 en 2024.",
    svg_config: null,
  },
  {
    difficulty: 5, category: "economie", type: "text", time_limit: 20,
    text: "Quel terme désigne le département créé par Elon Musk pour réduire les dépenses fédérales américaines ?",
    choices: ["MAGA Fund", "DOGE", "SAVE", "TRIM"],
    correct_index: 1,
    explanation: "Le DOGE (Department of Government Efficiency) a été créé par Trump et dirigé par Elon Musk pour identifier et éliminer les dépenses fédérales jugées inutiles.",
    svg_config: null,
  },
  {
    difficulty: 5, category: "culture", type: "text", time_limit: 20,
    text: "Quel film de Brady Corbet a reçu de nombreuses nominations aux Oscars 2025 ?",
    choices: ["Oppenheimer", "The Brutalist", "Killers of the Flower Moon", "Dune: Part Two"],
    correct_index: 1,
    explanation: "The Brutalist de Brady Corbet a reçu 10 nominations aux Oscars 2025, dont celle du meilleur film.",
    svg_config: null,
  },
  {
    difficulty: 5, category: "science", type: "text", time_limit: 20,
    text: "Quelle mission spatiale de la NASA, visant un retour sur la Lune, a continué sa progression en 2025 ?",
    choices: ["Apollo 18", "Artemis", "Orion Solo", "Lunar Gateway Express"],
    correct_index: 1,
    explanation: "Le programme Artemis de la NASA a poursuivi sa progression en 2025 avec la préparation des missions Artemis II et III pour un retour humain sur la Lune.",
    svg_config: null,
  },
  {
    difficulty: 5, category: "politique-monde", type: "text", time_limit: 20,
    text: "Quel envoyé spécial Trump a-t-il nommé pour tenter de résoudre le conflit en Ukraine ?",
    choices: ["Mike Pompeo", "Keith Kellogg", "John Bolton", "Jared Kushner"],
    correct_index: 1,
    explanation: "Trump a nommé le général Keith Kellogg comme envoyé spécial pour l'Ukraine et la Russie début 2025.",
    svg_config: null,
  },
  {
    difficulty: 5, category: "societe", type: "text", time_limit: 20,
    text: "Quel pays a légalisé l'euthanasie en 2025 après un long débat parlementaire ?",
    choices: ["France", "Italie", "Royaume-Uni", "Allemagne"],
    correct_index: 0,
    explanation: "La France a avancé sur un projet de loi sur l'aide à mourir en 2025, relançant le débat sur la fin de vie.",
    svg_config: null,
  },
  {
    difficulty: 5, category: "environnement", type: "text", time_limit: 20,
    text: "Quel phénomène climatique El Niño/La Niña a dominé les conditions météorologiques début 2025 ?",
    choices: ["El Niño fort", "La Niña modérée", "Conditions neutres", "El Niño faible"],
    correct_index: 1,
    explanation: "La Niña s'est installée fin 2024 et a dominé les conditions météorologiques mondiales début 2025.",
    svg_config: null,
  },
  {
    difficulty: 5, category: "tech", type: "text", time_limit: 20,
    text: "Quel géant de la tech a annoncé un investissement massif de 500 milliards de dollars dans l'infrastructure IA avec le projet Stargate en 2025 ?",
    choices: ["Google", "Apple", "OpenAI / SoftBank / Oracle", "Amazon"],
    correct_index: 2,
    explanation: "Le projet Stargate, annoncé en janvier 2025, est un partenariat entre OpenAI, SoftBank et Oracle prévoyant 500 milliards de dollars d'investissement dans l'infrastructure IA aux États-Unis.",
    svg_config: null,
  },

  // ===== DIFFICULTE 6 — MOYEN+ (25s) =====
  {
    difficulty: 6, category: "politique-monde", type: "text", time_limit: 25,
    text: "Quel ancien président du Honduras a été extradé et condamné aux États-Unis début 2025 pour trafic de drogue ?",
    choices: ["Manuel Zelaya", "Juan Orlando Hernández", "Porfirio Lobo", "Roberto Micheletti"],
    correct_index: 1,
    explanation: "Juan Orlando Hernández a été condamné à 45 ans de prison par un tribunal américain pour trafic de drogue et corruption.",
    svg_config: null,
  },
  {
    difficulty: 6, category: "sport", type: "text", time_limit: 25,
    text: "Quel club de football a remporté la Ligue des Champions 2024-2025 ?",
    choices: ["Real Madrid", "Manchester City", "Inter Milan", "PSG"],
    correct_index: 0,
    explanation: "Le Real Madrid a poursuivi sa domination européenne lors de la saison 2024-2025 de la Ligue des Champions.",
    svg_config: null,
  },
  {
    difficulty: 6, category: "tech", type: "text", time_limit: 25,
    text: "Combien aurait coûté l'entraînement du modèle DeepSeek R1 selon les estimations, comparé aux milliards dépensés par les concurrents ?",
    choices: ["500 000 dollars", "6 millions de dollars", "50 millions de dollars", "500 millions de dollars"],
    correct_index: 1,
    explanation: "DeepSeek R1 aurait été entraîné pour environ 6 millions de dollars, une fraction du coût des modèles concurrents qui nécessitent des centaines de millions.",
    svg_config: null,
  },
  {
    difficulty: 6, category: "politique-fr", type: "text", time_limit: 25,
    text: "Quel ministre de l'Intérieur a été nommé dans le gouvernement Bayrou en décembre 2024 ?",
    choices: ["Gérald Darmanin", "Bruno Retailleau", "Christophe Castaner", "Éric Dupond-Moretti"],
    correct_index: 1,
    explanation: "Bruno Retailleau a été maintenu au poste de ministre de l'Intérieur dans le gouvernement Bayrou, après avoir déjà occupé ce poste sous Barnier.",
    svg_config: null,
  },
  {
    difficulty: 6, category: "culture", type: "text", time_limit: 25,
    text: "Quel réalisateur français a réalisé Emilia Pérez, nommé aux Oscars 2025 ?",
    choices: ["Luc Besson", "Jacques Audiard", "Cédric Klapisch", "François Ozon"],
    correct_index: 1,
    explanation: "Jacques Audiard a réalisé Emilia Pérez, film musical franco-mexicain qui a reçu de nombreuses nominations aux Oscars 2025.",
    svg_config: null,
  },
  {
    difficulty: 6, category: "economie", type: "text", time_limit: 25,
    text: "Quelle action liée à l'IA a vu sa valeur boursière chuter de plus de 15% en un jour suite à l'annonce de DeepSeek en janvier 2025 ?",
    choices: ["Apple", "Microsoft", "Nvidia", "Google"],
    correct_index: 2,
    explanation: "Nvidia a perdu près de 600 milliards de dollars de capitalisation en une seule journée le 27 janvier 2025, sa plus grande chute historique, après l'annonce de DeepSeek R1.",
    svg_config: null,
  },
  {
    difficulty: 6, category: "science", type: "text", time_limit: 25,
    text: "Quel vaccin à ARN messager contre le cancer a progressé vers des essais cliniques avancés en 2025 ?",
    choices: ["Un vaccin Pfizer contre le mélanome", "Un vaccin Moderna contre le cancer du poumon", "Un vaccin BioNTech/Moderna contre le mélanome", "Un vaccin Sanofi contre le cancer du sein"],
    correct_index: 2,
    explanation: "Le vaccin personnalisé à ARNm contre le mélanome, développé par Moderna et BioNTech, a progressé vers des phases avancées d'essais cliniques en 2025.",
    svg_config: null,
  },
  {
    difficulty: 6, category: "environnement", type: "text", time_limit: 25,
    text: "Quel pays a annoncé début 2025 vouloir tripler sa capacité nucléaire d'ici 2050 pour atteindre la neutralité carbone ?",
    choices: ["Allemagne", "France", "Japon", "Royaume-Uni"],
    correct_index: 1,
    explanation: "La France a confirmé début 2025 son ambition de construire de nouveaux réacteurs EPR2 pour tripler sa capacité nucléaire et atteindre la neutralité carbone.",
    svg_config: null,
  },
  {
    difficulty: 6, category: "societe", type: "text", time_limit: 25,
    text: "Quel réseau social a changé ses politiques de modération en supprimant le fact-checking par des tiers début 2025 ?",
    choices: ["X (Twitter)", "Facebook / Meta", "YouTube", "TikTok"],
    correct_index: 1,
    explanation: "Meta a annoncé début janvier 2025 la suppression de son programme de fact-checking par des tiers sur Facebook et Instagram, le remplaçant par des notes communautaires.",
    svg_config: null,
  },
  {
    difficulty: 6, category: "politique-monde", type: "text", time_limit: 25,
    text: "Quel pays a rejoint officiellement le groupe BRICS en tant que membre à part entière en janvier 2025 ?",
    choices: ["Turquie", "Indonésie", "Malaisie", "Toutes ces réponses"],
    correct_index: 1,
    explanation: "L'Indonésie a rejoint les BRICS en tant que membre à part entière début 2025, rejoignant les nouveaux membres acceptés lors du sommet de Kazan.",
    svg_config: null,
  },

  // ===== DIFFICULTE 7 — DIFFICILE (25s) =====
  {
    difficulty: 7, category: "tech", type: "text", time_limit: 25,
    text: "Quel outil de génération vidéo par IA, développé par OpenAI, est devenu accessible au public début 2025 ?",
    choices: ["Runway Gen-3", "Sora", "Pika 2.0", "Stable Video"],
    correct_index: 1,
    explanation: "Sora, l'outil de génération vidéo par IA d'OpenAI, a été progressivement rendu accessible au public début 2025 après des mois de tests.",
    svg_config: null,
  },
  {
    difficulty: 7, category: "politique-fr", type: "text", time_limit: 25,
    text: "Quel montant de déficit public la France a-t-elle enregistré en 2024, révélé début 2025 ?",
    choices: ["3,5% du PIB", "5,0% du PIB", "5,8% du PIB", "6,2% du PIB"],
    correct_index: 2,
    explanation: "Le déficit public français s'est établi à environ 5,8% du PIB en 2024, bien au-dessus des prévisions et de la limite européenne de 3%.",
    svg_config: null,
  },
  {
    difficulty: 7, category: "sport", type: "text", time_limit: 25,
    text: "Dans quelle écurie Lewis Hamilton a-t-il fait ses débuts en tant que pilote en 2025 ?",
    choices: ["Red Bull", "McLaren", "Ferrari", "Aston Martin"],
    correct_index: 2,
    explanation: "Lewis Hamilton a rejoint Ferrari pour la saison 2025 de Formule 1 après avoir quitté Mercedes, réalisant un rêve de longue date.",
    svg_config: null,
  },
  {
    difficulty: 7, category: "economie", type: "text", time_limit: 25,
    text: "Quel pays a vu sa monnaie s'effondrer début 2025 face aux politiques tarifaires de Trump ?",
    choices: ["Brésil", "Mexique", "Turquie", "Canada"],
    correct_index: 3,
    explanation: "Le dollar canadien a subi une forte pression baissière début 2025 face aux menaces puis à l'imposition de tarifs douaniers de 25% par Trump.",
    svg_config: null,
  },
  {
    difficulty: 7, category: "culture", type: "text", time_limit: 25,
    text: "Quelle chanteuse a dominé les Grammy Awards 2025 avec le plus de récompenses ?",
    choices: ["Taylor Swift", "Beyoncé", "Billie Eilish", "Sabrina Carpenter"],
    correct_index: 1,
    explanation: "Beyoncé a dominé les Grammy Awards 2025 avec son album Cowboy Carter, remportant plusieurs récompenses majeures.",
    svg_config: null,
  },
  {
    difficulty: 7, category: "science", type: "text", time_limit: 25,
    text: "Quelle avancée majeure en informatique quantique Google a-t-il annoncée avec sa puce Willow fin 2024, célébrée début 2025 ?",
    choices: ["100 qubits stables", "Suprématie quantique dans le calcul d'erreurs", "Premier ordinateur quantique commercial", "Téléportation quantique sur 1000 km"],
    correct_index: 1,
    explanation: "Google a annoncé que sa puce Willow avait franchi un seuil clé en correction d'erreurs quantiques, démontrant que plus on ajoute de qubits, moins il y a d'erreurs.",
    svg_config: null,
  },
  {
    difficulty: 7, category: "politique-monde", type: "text", time_limit: 25,
    text: "Quel accord de cessez-le-feu a été conclu entre Israël et le Hamas en janvier 2025 ?",
    choices: ["Accords d'Oslo III", "Accord de Doha", "Accord de Camp David II", "Accord d'Abraham II"],
    correct_index: 1,
    explanation: "Un accord de cessez-le-feu entre Israël et le Hamas a été conclu à Doha en janvier 2025, prévoyant la libération d'otages et de prisonniers palestiniens.",
    svg_config: null,
  },
  {
    difficulty: 7, category: "environnement", type: "text", time_limit: 25,
    text: "Quel record de température moyenne mondiale a été battu en 2024, confirmé début 2025 ?",
    choices: ["1,2°C au-dessus des niveaux préindustriels", "1,35°C au-dessus", "1,55°C au-dessus", "1,8°C au-dessus"],
    correct_index: 2,
    explanation: "La température moyenne mondiale en 2024 a dépassé pour la première fois 1,5°C au-dessus des niveaux préindustriels sur une année complète, atteignant environ 1,55°C.",
    svg_config: null,
  },
  {
    difficulty: 7, category: "societe", type: "text", time_limit: 25,
    text: "Quel pays a été frappé par un séisme dévastateur en janvier 2025, faisant des milliers de victimes ?",
    choices: ["Népal", "Turquie", "Tibet (Chine)", "Maroc"],
    correct_index: 2,
    explanation: "Un séisme de magnitude 7,1 a frappé le Tibet (Chine) le 7 janvier 2025, près de Shigatse, causant plus de 120 morts et des milliers de blessés.",
    svg_config: null,
  },
  {
    difficulty: 7, category: "politique-fr", type: "text", time_limit: 25,
    text: "Quelle figure politique française a annoncé sa candidature potentielle à la présidentielle 2027 début 2025 ?",
    choices: ["Marine Le Pen", "Édouard Philippe", "Jean-Luc Mélenchon", "Jordan Bardella"],
    correct_index: 1,
    explanation: "Édouard Philippe a poursuivi sa stratégie de pré-candidature à l'élection présidentielle de 2027, multipliant les déplacements et prises de position début 2025.",
    svg_config: null,
  },

  // ===== DIFFICULTE 8 — DIFFICILE+ (25s) =====
  {
    difficulty: 8, category: "tech", type: "text", time_limit: 25,
    text: "Quel concurrent chinois de Nvidia a développé des puces IA que DeepSeek a utilisées pour contourner les restrictions d'exportation américaines ?",
    choices: ["SMIC", "Huawei (Ascend)", "Cambricon", "Biren Technology"],
    correct_index: 1,
    explanation: "DeepSeek a utilisé des puces Nvidia H800 (version restreinte pour la Chine) ainsi que des puces Huawei Ascend pour entraîner ses modèles malgré les restrictions américaines.",
    svg_config: null,
  },
  {
    difficulty: 8, category: "politique-monde", type: "text", time_limit: 25,
    text: "Quel dirigeant syrien a été renversé fin 2024 par une offensive rebelle, événement majeur analysé début 2025 ?",
    choices: ["Hafez al-Assad", "Bachar al-Assad", "Hassan Nasrallah", "Abou Mohammed al-Joulani"],
    correct_index: 1,
    explanation: "Bachar al-Assad a été renversé en décembre 2024 par une offensive menée par des groupes rebelles dont Hayat Tahrir al-Sham, mettant fin à des décennies de règne familial.",
    svg_config: null,
  },
  {
    difficulty: 8, category: "sport", type: "text", time_limit: 25,
    text: "Combien de titres du Grand Chelem Novak Djokovic détenait-il début 2025 ?",
    choices: ["22", "23", "24", "25"],
    correct_index: 2,
    explanation: "Novak Djokovic détenait 24 titres du Grand Chelem début 2025, un record absolu dans le tennis masculin.",
    svg_config: null,
  },
  {
    difficulty: 8, category: "economie", type: "text", time_limit: 25,
    text: "Quel taux directeur la BCE (Banque Centrale Européenne) visait-elle début 2025 après plusieurs baisses ?",
    choices: ["2,00%", "2,75%", "3,50%", "4,00%"],
    correct_index: 1,
    explanation: "La BCE a continué sa politique de baisse des taux début 2025, ramenant son taux de dépôt vers 2,75% pour soutenir l'économie européenne en ralentissement.",
    svg_config: null,
  },
  {
    difficulty: 8, category: "culture", type: "text", time_limit: 25,
    text: "Quel film a remporté la Palme d'or au Festival de Cannes 2025 ?",
    choices: ["Eddington de Ari Aster", "The Mastermind", "A Man of Reason", "On s'en fout"],
    correct_index: 0,
    explanation: "Le Festival de Cannes 2025 a présenté de nombreux films très attendus dont la compétition officielle pour la Palme d'or.",
    svg_config: null,
  },
  {
    difficulty: 8, category: "science", type: "text", time_limit: 25,
    text: "Quel record de durée pour une réaction de fusion nucléaire a été battu début 2025 ?",
    choices: ["10 secondes à 100 millions de degrés", "17 minutes de plasma stable", "1000 secondes de confinement", "5 minutes de production nette d'énergie"],
    correct_index: 2,
    explanation: "Le tokamak EAST chinois a atteint un record de 1000 secondes de confinement de plasma en mode H, une étape clé vers la fusion commerciale.",
    svg_config: null,
  },
  {
    difficulty: 8, category: "politique-fr", type: "text", time_limit: 25,
    text: "Quelle procédure judiciaire menaçait Marine Le Pen d'inéligibilité début 2025 ?",
    choices: ["Affaire des emplois fictifs du FN au Parlement européen", "Affaire des financements libyens", "Affaire du financement russe", "Affaire des sondages de l'Élysée"],
    correct_index: 0,
    explanation: "Marine Le Pen a été condamnée en première instance dans l'affaire des emplois fictifs d'assistants parlementaires européens du FN, avec une peine d'inéligibilité.",
    svg_config: null,
  },
  {
    difficulty: 8, category: "environnement", type: "text", time_limit: 25,
    text: "Quelle île nation du Pacifique a intensifié ses appels à la communauté internationale face à la montée des eaux en 2025 ?",
    choices: ["Fidji", "Tuvalu", "Hawaï", "Madagascar"],
    correct_index: 1,
    explanation: "Tuvalu, l'un des pays les plus menacés par la montée des eaux, a intensifié ses appels diplomatiques en 2025, négociant même des accords de relocalisation avec l'Australie.",
    svg_config: null,
  },
  {
    difficulty: 8, category: "societe", type: "text", time_limit: 25,
    text: "Quel pays européen a durci sa législation sur l'immigration en imposant des contrôles aux frontières prolongés début 2025 ?",
    choices: ["Espagne", "Italie", "Allemagne", "Suède"],
    correct_index: 2,
    explanation: "L'Allemagne a prolongé ses contrôles aux frontières terrestres début 2025 et durci sa politique d'asile, marquant un virage politique significatif.",
    svg_config: null,
  },
  {
    difficulty: 8, category: "tech", type: "text", time_limit: 25,
    text: "Quelle fonctionnalité controversée Apple Intelligence a-t-elle introduite début 2025 qui résumait incorrectement les notifications ?",
    choices: ["Smart Reply", "Notification Summaries", "AI Photo Editor", "Siri GPT"],
    correct_index: 1,
    explanation: "Apple Intelligence Notification Summaries a été critiquée début 2025 pour produire des résumés inexacts et parfois trompeurs des notifications, notamment d'actualités.",
    svg_config: null,
  },

  // ===== DIFFICULTE 9 — TRES DIFFICILE (30s) =====
  {
    difficulty: 9, category: "politique-monde", type: "text", time_limit: 30,
    text: "Quel décret exécutif signé par Trump le jour de son investiture visait à mettre fin au droit du sol aux États-Unis ?",
    choices: ["Executive Order on Border Security", "Protecting the Meaning of Citizenship", "America First Immigration Act", "Securing American Birthright"],
    correct_index: 1,
    explanation: "Trump a signé un décret intitulé 'Protecting the Meaning and Value of American Citizenship' visant à restreindre le droit du sol, immédiatement contesté devant les tribunaux.",
    svg_config: null,
  },
  {
    difficulty: 9, category: "tech", type: "text", time_limit: 30,
    text: "Quelle technique d'entraînement innovante DeepSeek a-t-il utilisée pour réduire drastiquement ses coûts ?",
    choices: ["Knowledge distillation pure", "Mixture of Experts (MoE) avec quantification FP8", "Transfer learning depuis GPT-4", "Pruning neuronal adaptatif"],
    correct_index: 1,
    explanation: "DeepSeek a utilisé une architecture Mixture of Experts (MoE) combinée à une quantification FP8, permettant d'entraîner un modèle de 671 milliards de paramètres à faible coût.",
    svg_config: null,
  },
  {
    difficulty: 9, category: "sport", type: "text", time_limit: 30,
    text: "Quel changement majeur de format la Ligue des Champions a-t-elle adopté pour la saison 2024-2025 ?",
    choices: ["Passage à 48 équipes", "Phase de ligue unique à 36 équipes remplaçant les groupes", "Matchs aller-retour supprimés en quarts", "Introduction de prolongations au format golden goal"],
    correct_index: 1,
    explanation: "La Ligue des Champions 2024-2025 a adopté un nouveau format avec une phase de ligue unique à 36 équipes, chacune jouant 8 matchs contre des adversaires différents.",
    svg_config: null,
  },
  {
    difficulty: 9, category: "economie", type: "text", time_limit: 30,
    text: "Combien de milliards de dollars de capitalisation Nvidia a-t-elle perdu le 27 janvier 2025, jour du 'choc DeepSeek' ?",
    choices: ["200 milliards", "400 milliards", "593 milliards", "800 milliards"],
    correct_index: 2,
    explanation: "Nvidia a perdu environ 593 milliards de dollars de capitalisation le 27 janvier 2025, la plus grande perte de valeur en une journée jamais enregistrée pour une entreprise.",
    svg_config: null,
  },
  {
    difficulty: 9, category: "politique-fr", type: "text", time_limit: 30,
    text: "Combien de temps le gouvernement de Michel Barnier a-t-il duré avant d'être censuré ?",
    choices: ["45 jours", "61 jours", "90 jours", "120 jours"],
    correct_index: 2,
    explanation: "Le gouvernement Barnier a duré environ 90 jours (du 5 septembre au 4 décembre 2024), en faisant l'un des plus courts de la Ve République.",
    svg_config: null,
  },
  {
    difficulty: 9, category: "science", type: "text", time_limit: 30,
    text: "Quelle mission spatiale privée a réalisé la première sortie extravéhiculaire (EVA) commerciale en 2024, saluée en 2025 ?",
    choices: ["Axiom Mission 4", "Polaris Dawn", "Blue Origin Orbital", "Virgin Galactic Unity"],
    correct_index: 1,
    explanation: "La mission Polaris Dawn de SpaceX, lancée en septembre 2024, a réalisé la première sortie extravéhiculaire entièrement commerciale de l'histoire spatiale.",
    svg_config: null,
  },
  {
    difficulty: 9, category: "culture", type: "text", time_limit: 30,
    text: "Quelle actrice trans espagnole a remporté un prix d'interprétation à Cannes 2024 pour Emilia Pérez, devenant figure majeure aux Oscars 2025 ?",
    choices: ["Penélope Cruz", "Karla Sofía Gascón", "Zoe Saldaña", "Selena Gomez"],
    correct_index: 1,
    explanation: "Karla Sofía Gascón a été la première actrice ouvertement transgenre nommée aux Oscars pour son rôle dans Emilia Pérez de Jacques Audiard.",
    svg_config: null,
  },
  {
    difficulty: 9, category: "environnement", type: "text", time_limit: 30,
    text: "Quel pourcentage de la production électrique mondiale les énergies renouvelables ont-elles atteint en 2024 selon le bilan publié début 2025 ?",
    choices: ["20%", "25%", "30%", "35%"],
    correct_index: 2,
    explanation: "Les énergies renouvelables ont atteint environ 30% de la production électrique mondiale en 2024, un record historique porté par le solaire et l'éolien.",
    svg_config: null,
  },
  {
    difficulty: 9, category: "societe", type: "text", time_limit: 30,
    text: "Quel scandale lié à l'IA a touché le monde de l'édition académique début 2025 ?",
    choices: ["Des thèses entièrement générées par IA", "Des articles scientifiques avec des images générées par IA publiés dans des revues prestigieuses", "Un prix Nobel attribué à une découverte faite par IA", "Une IA nommée co-auteur d'un manuel universitaire"],
    correct_index: 1,
    explanation: "De nombreux articles scientifiques contenant des images manifestement générées par IA (avec des erreurs typiques) ont été découverts dans des revues prestigieuses début 2025, soulevant des questions sur l'intégrité académique.",
    svg_config: null,
  },
  {
    difficulty: 9, category: "politique-monde", type: "text", time_limit: 30,
    text: "Quel pourcentage de droits de douane cumulés les États-Unis ont-ils imposé sur les produits chinois début 2025 en combinant les tarifs existants et nouveaux ?",
    choices: ["25%", "35%", "45%", "Plus de 50%"],
    correct_index: 2,
    explanation: "Avec les tarifs cumulés de l'ère Trump 1, Biden, et les nouveaux de 2025, les droits de douane américains sur de nombreux produits chinois ont atteint environ 45% ou plus.",
    svg_config: null,
  },

  // ===== DIFFICULTE 10 — EXPERT (30s) =====
  {
    difficulty: 10, category: "tech", type: "text", time_limit: 30,
    text: "Quel benchmark d'IA DeepSeek R1 a-t-il égalé ou dépassé face à GPT-4o lors de sa sortie en janvier 2025 ?",
    choices: ["MMLU uniquement", "HumanEval uniquement", "AIME 2024 (mathématiques) et GPQA (sciences)", "SuperGLUE et SQuAD"],
    correct_index: 2,
    explanation: "DeepSeek R1 a rivalisé avec les meilleurs modèles sur les benchmarks AIME 2024 (compétitions de mathématiques) et GPQA (questions scientifiques de niveau doctorat).",
    svg_config: null,
  },
  {
    difficulty: 10, category: "politique-monde", type: "text", time_limit: 30,
    text: "Quel nom de code portait l'offensive rebelle syrienne qui a renversé Assad en décembre 2024 ?",
    choices: ["Opération Aube de la Liberté", "Opération Dissuasion de l'Agression", "Opération Tempête du Levant", "Opération Bouclier du Peuple"],
    correct_index: 1,
    explanation: "L'offensive rebelle menée par Hayat Tahrir al-Sham portait le nom d'Opération Dissuasion de l'Agression (Rad' al-Udwan) et a conduit à la chute d'Assad en 12 jours.",
    svg_config: null,
  },
  {
    difficulty: 10, category: "sport", type: "text", time_limit: 30,
    text: "Quel était le score exact du Super Bowl LIX entre les Eagles et les Chiefs en février 2025 ?",
    choices: ["31-22", "40-22", "34-29", "28-25"],
    correct_index: 1,
    explanation: "Les Philadelphia Eagles ont battu les Kansas City Chiefs 40-22 lors du Super Bowl LIX, une victoire dominante qui a empêché le three-peat des Chiefs.",
    svg_config: null,
  },
  {
    difficulty: 10, category: "economie", type: "text", time_limit: 30,
    text: "Quel nom porte la cryptomonnaie mème lancée par Melania Trump le 19 janvier 2025, juste après celle de Donald ?",
    choices: ["$FLOTUS", "$MELANIA", "$FIRSTLADY", "$MAGA-QUEEN"],
    correct_index: 1,
    explanation: "Melania Trump a lancé le token $MELANIA le 19 janvier 2025, un jour après le lancement du $TRUMP par Donald Trump, les deux provoquant des interrogations éthiques.",
    svg_config: null,
  },
  {
    difficulty: 10, category: "politique-fr", type: "text", time_limit: 30,
    text: "Par combien de voix la motion de censure contre le gouvernement Barnier a-t-elle été adoptée le 4 décembre 2024 ?",
    choices: ["289 voix", "309 voix", "331 voix", "350 voix"],
    correct_index: 1,
    explanation: "La motion de censure contre le gouvernement Barnier a été adoptée par 331 voix (NFP + RN), bien au-delà de la majorité absolue de 289 requise.",
    svg_config: null,
  },
  {
    difficulty: 10, category: "science", type: "text", time_limit: 30,
    text: "Combien de qubits la puce quantique Willow de Google contient-elle ?",
    choices: ["53", "72", "105", "256"],
    correct_index: 2,
    explanation: "La puce Willow de Google contient 105 qubits et a démontré une réduction exponentielle des erreurs en augmentant le nombre de qubits, un résultat historique.",
    svg_config: null,
  },
  {
    difficulty: 10, category: "culture", type: "text", time_limit: 30,
    text: "Combien de nominations aux Oscars 2025 le film Emilia Pérez a-t-il obtenues au total ?",
    choices: ["8", "10", "13", "15"],
    correct_index: 2,
    explanation: "Emilia Pérez de Jacques Audiard a obtenu 13 nominations aux Oscars 2025, un record pour un film en langue non anglaise.",
    svg_config: null,
  },
  {
    difficulty: 10, category: "environnement", type: "text", time_limit: 30,
    text: "Quel pays a inauguré la plus grande ferme solaire du monde en 2025, dépassant 2 GW de capacité ?",
    choices: ["Inde", "Chine", "Arabie Saoudite", "Australie"],
    correct_index: 1,
    explanation: "La Chine a continué à dominer le secteur solaire mondial en 2025, inaugurant des installations photovoltaïques massives dépassant les 2 GW dans le désert de Xinjiang.",
    svg_config: null,
  },
  {
    difficulty: 10, category: "societe", type: "text", time_limit: 30,
    text: "Quel montant total de dommages les incendies de Los Angeles de janvier 2025 ont-ils causé selon les premières estimations ?",
    choices: ["50 milliards de dollars", "100 milliards de dollars", "150 à 200 milliards de dollars", "250 milliards de dollars"],
    correct_index: 2,
    explanation: "Les incendies de Los Angeles de janvier 2025 ont causé entre 150 et 200 milliards de dollars de dommages selon les estimations, en faisant la catastrophe naturelle la plus coûteuse de l'histoire de Californie.",
    svg_config: null,
  },
  {
    difficulty: 10, category: "politique-monde", type: "text", time_limit: 30,
    text: "Quel chef rebelle syrien, ancien leader de Hayat Tahrir al-Sham, est devenu la figure clé du pouvoir de transition après la chute d'Assad ?",
    choices: ["Abu Ibrahim al-Hashimi", "Ahmed al-Sharaa (Abu Mohammed al-Joulani)", "Hassan Nasrallah", "Zahran Alloush"],
    correct_index: 1,
    explanation: "Ahmed al-Sharaa, connu sous son nom de guerre Abu Mohammed al-Joulani, leader de HTS, est devenu la figure centrale de la transition syrienne après la chute d'Assad en décembre 2024.",
    svg_config: null,
  },
];
