import type { Question } from "./types";

export const questions: Omit<Question, "id">[] = [
  // ===== DIFFICULTE 1 — TRIVIAL (15s) =====
  {
    difficulty: 1, category: "sequence", type: "text", time_limit: 15,
    text: "Quelle est la suite : 2, 4, 6, 8, ?",
    choices: ["9", "10", "12", "11"],
    correct_index: 1,
    explanation: "C'est la suite des nombres pairs. Chaque nombre augmente de 2. 8 + 2 = 10.",
    svg_config: null,
  },
  {
    difficulty: 1, category: "pattern", type: "text", time_limit: 15,
    text: "Quel est l'intrus : Chien, Chat, Poisson, Table ?",
    choices: ["Chien", "Chat", "Poisson", "Table"],
    correct_index: 3,
    explanation: "Table est un objet, les trois autres sont des animaux.",
    svg_config: null,
  },
  {
    difficulty: 1, category: "sequence", type: "text", time_limit: 15,
    text: "Quelle est la suite : 1, 3, 5, 7, ?",
    choices: ["8", "9", "10", "11"],
    correct_index: 1,
    explanation: "C'est la suite des nombres impairs. Chaque nombre augmente de 2. 7 + 2 = 9.",
    svg_config: null,
  },
  {
    difficulty: 1, category: "deduction", type: "text", time_limit: 15,
    text: "Si tous les chats ont des moustaches et Minou est un chat, alors :",
    choices: ["Minou n'a pas de moustaches", "Minou a des moustaches", "Minou est un chien", "On ne peut pas savoir"],
    correct_index: 1,
    explanation: "Syllogisme simple : tous les chats ont des moustaches + Minou est un chat = Minou a des moustaches.",
    svg_config: null,
  },
  {
    difficulty: 1, category: "pattern", type: "text", time_limit: 15,
    text: "Quel est l'intrus : Rouge, Bleu, Vert, Lundi ?",
    choices: ["Rouge", "Bleu", "Vert", "Lundi"],
    correct_index: 3,
    explanation: "Lundi est un jour de la semaine, les trois autres sont des couleurs.",
    svg_config: null,
  },
  {
    difficulty: 1, category: "math-logic", type: "text", time_limit: 15,
    text: "Si j'ai 5 pommes et j'en donne 2, combien m'en reste-t-il ?",
    choices: ["2", "3", "5", "7"],
    correct_index: 1,
    explanation: "5 - 2 = 3. Il reste 3 pommes.",
    svg_config: null,
  },
  {
    difficulty: 1, category: "sequence", type: "text", time_limit: 15,
    text: "Completez : Lundi, Mardi, Mercredi, ?",
    choices: ["Vendredi", "Samedi", "Jeudi", "Dimanche"],
    correct_index: 2,
    explanation: "Les jours de la semaine dans l'ordre. Apres Mercredi vient Jeudi.",
    svg_config: null,
  },
  {
    difficulty: 1, category: "lateral", type: "text", time_limit: 20,
    text: "Un pere et son fils ont ensemble 36 ans. Le pere a 30 ans de plus que le fils. Quel age a le fils ?",
    choices: ["6 ans", "3 ans", "5 ans", "8 ans"],
    correct_index: 1,
    explanation: "Si le fils a x ans, le pere a x+30. Donc x + (x+30) = 36, soit 2x = 6, x = 3.",
    svg_config: null,
  },
  {
    difficulty: 1, category: "pattern", type: "svg", time_limit: 15,
    text: "Quel forme complete la serie ?",
    choices: ["Cercle rouge", "Carre bleu", "Triangle vert", "Cercle bleu"],
    correct_index: 3,
    explanation: "La serie alterne : cercle rouge, carre bleu, cercle rouge, carre bleu. Le prochain est cercle bleu car la couleur suit le pattern.",
    svg_config: { renderer: "PatternSequence", params: { shapes: ["circle", "square", "circle", "square"], colors: ["red", "blue", "red", "blue"], missing: 4, answer: "circle-blue" } },
  },
  {
    difficulty: 1, category: "deduction", type: "text", time_limit: 15,
    text: "Marie est plus grande que Paul. Paul est plus grand que Luc. Qui est le plus petit ?",
    choices: ["Marie", "Paul", "Luc", "On ne sait pas"],
    correct_index: 2,
    explanation: "Marie > Paul > Luc. Luc est le plus petit.",
    svg_config: null,
  },

  // ===== DIFFICULTE 2 — FACILE (15s) =====
  {
    difficulty: 2, category: "sequence", type: "text", time_limit: 15,
    text: "Quelle est la suite : 3, 6, 12, 24, ?",
    choices: ["30", "36", "48", "42"],
    correct_index: 2,
    explanation: "Chaque nombre est multiplie par 2. 24 × 2 = 48.",
    svg_config: null,
  },
  {
    difficulty: 2, category: "deduction", type: "text", time_limit: 15,
    text: "Dans une course, vous depassez le 2e. Quelle est votre position ?",
    choices: ["1er", "2e", "3e", "Dernier"],
    correct_index: 1,
    explanation: "En depassant le 2e, vous prenez sa place : vous etes maintenant 2e (pas 1er !).",
    svg_config: null,
  },
  {
    difficulty: 2, category: "math-logic", type: "text", time_limit: 15,
    text: "Un fermier a 17 moutons. Tous sauf 9 meurent. Combien en reste-t-il ?",
    choices: ["8", "9", "0", "17"],
    correct_index: 1,
    explanation: "'Tous sauf 9 meurent' signifie que 9 survivent. Il en reste 9.",
    svg_config: null,
  },
  {
    difficulty: 2, category: "pattern", type: "text", time_limit: 15,
    text: "Quel est l'intrus : 2, 5, 8, 12, 14 ?",
    choices: ["2", "5", "12", "14"],
    correct_index: 2,
    explanation: "La suite ajoute 3 a chaque fois : 2, 5, 8, 11, 14. Le nombre 12 n'appartient pas a cette suite (devrait etre 11).",
    svg_config: null,
  },
  {
    difficulty: 2, category: "sequence", type: "text", time_limit: 15,
    text: "A, C, E, G, ?",
    choices: ["H", "I", "J", "K"],
    correct_index: 1,
    explanation: "On saute une lettre a chaque fois : A(B)C(D)E(F)G(H)I.",
    svg_config: null,
  },
  {
    difficulty: 2, category: "lateral", type: "text", time_limit: 15,
    text: "Combien de mois ont 28 jours ?",
    choices: ["1 seul (fevrier)", "6 mois", "Tous les 12", "Aucun"],
    correct_index: 2,
    explanation: "Tous les mois ont AU MOINS 28 jours. La question est un piege classique.",
    svg_config: null,
  },
  {
    difficulty: 2, category: "deduction", type: "text", time_limit: 15,
    text: "Si certains A sont B et tous les B sont C, alors :",
    choices: ["Tous les A sont C", "Certains A sont C", "Aucun A n'est C", "Tous les C sont A"],
    correct_index: 1,
    explanation: "Certains A sont B, et ces B sont aussi C. Donc certains A (ceux qui sont B) sont aussi C.",
    svg_config: null,
  },
  {
    difficulty: 2, category: "math-logic", type: "text", time_limit: 25,
    text: "2 + 2 = poisson. 3 + 3 = huit. 7 + 7 = triangle. 8 + 8 = infini. Que vaut 5 + 5 ?",
    choices: ["10", "Dix", "Oeuf", "Cinq"],
    correct_index: 2,
    explanation: "On regarde la FORME VISUELLE du résultat écrit en chiffres : 4 → deux traits qui se croisent comme un poisson, 6 → ressemble au chiffre 8 (boucles), 14 → forme triangulaire du 4, 16 → le 1 et le 6 forment un signe infini couché. Et 10 ? Le 1 à côté du 0 forme un œuf !",
    svg_config: null,
  },
  {
    difficulty: 2, category: "pattern", type: "svg", time_limit: 15,
    text: "Trouvez l'intrus parmi ces formes :",
    choices: ["Forme 1", "Forme 2", "Forme 3", "Forme 4"],
    correct_index: 2,
    explanation: "Toutes les formes sont symetriques sauf la forme 3 qui est asymetrique.",
    svg_config: { renderer: "OddOneOut", params: { shapes: ["symmetric-star", "symmetric-diamond", "asymmetric-blob", "symmetric-hexagon"], oddIndex: 2 } },
  },
  {
    difficulty: 2, category: "sequence", type: "text", time_limit: 15,
    text: "1, 1, 2, 3, 5, 8, ?",
    choices: ["10", "11", "12", "13"],
    correct_index: 3,
    explanation: "C'est la suite de Fibonacci : chaque nombre est la somme des deux precedents. 5 + 8 = 13.",
    svg_config: null,
  },

  // ===== DIFFICULTE 3 — FACILE+ (15s) =====
  {
    difficulty: 3, category: "deduction", type: "text", time_limit: 15,
    text: "3 amis comparent leurs ages. Alex est plus vieux que Ben. Charlie est plus jeune qu'Alex mais plus vieux que Ben. Classez-les du plus vieux au plus jeune.",
    choices: ["Alex, Charlie, Ben", "Charlie, Alex, Ben", "Alex, Ben, Charlie", "Ben, Charlie, Alex"],
    correct_index: 0,
    explanation: "Alex > Charlie > Ben. Alex est le plus vieux, puis Charlie, puis Ben.",
    svg_config: null,
  },
  {
    difficulty: 3, category: "sequence", type: "text", time_limit: 15,
    text: "Quelle est la suite : 1, 4, 9, 16, 25, ?",
    choices: ["30", "36", "49", "35"],
    correct_index: 1,
    explanation: "Ce sont les carres parfaits : 1², 2², 3², 4², 5². Le suivant est 6² = 36.",
    svg_config: null,
  },
  {
    difficulty: 3, category: "math-logic", type: "text", time_limit: 20,
    text: "Si 3 chats attrapent 3 souris en 3 minutes, combien faut-il de chats pour attraper 100 souris en 100 minutes ?",
    choices: ["100 chats", "3 chats", "33 chats", "1 chat"],
    correct_index: 1,
    explanation: "Chaque chat attrape 1 souris en 3 minutes. En 100 minutes, 1 chat attrape ~33 souris. 3 chats attrapent ~99-100 souris.",
    svg_config: null,
  },
  {
    difficulty: 3, category: "lateral", type: "text", time_limit: 15,
    text: "J'ai des villes mais pas de maisons, des forets mais pas d'arbres, de l'eau mais pas de poissons. Qui suis-je ?",
    choices: ["Un reve", "Une carte", "Un jeu video", "Un livre"],
    correct_index: 1,
    explanation: "Une carte geographique a des villes, forets et eau representes, mais pas les elements reels.",
    svg_config: null,
  },
  {
    difficulty: 3, category: "pattern", type: "text", time_limit: 15,
    text: "Quel est l'intrus : 121, 131, 141, 155, 161 ?",
    choices: ["121", "131", "155", "161"],
    correct_index: 2,
    explanation: "Tous les nombres sont des palindromes (se lisent de la meme facon dans les deux sens) sauf 155.",
    svg_config: null,
  },
  {
    difficulty: 3, category: "deduction", type: "text", time_limit: 15,
    text: "Tous les Bloops sont Razzies. Tous les Razzies sont Lazzies. Donc :",
    choices: ["Tous les Lazzies sont Bloops", "Tous les Bloops sont Lazzies", "Certains Lazzies sont Razzies", "Aucun Bloop n'est Lazzie"],
    correct_index: 1,
    explanation: "Si Bloops ⊂ Razzies et Razzies ⊂ Lazzies, alors Bloops ⊂ Lazzies. Tous les Bloops sont Lazzies.",
    svg_config: null,
  },
  {
    difficulty: 3, category: "sequence", type: "text", time_limit: 15,
    text: "O, T, T, F, F, S, S, ?",
    choices: ["E", "N", "H", "T"],
    correct_index: 0,
    explanation: "Ce sont les initiales des chiffres en anglais : One, Two, Three, Four, Five, Six, Seven, Eight. E pour Eight.",
    svg_config: null,
  },
  {
    difficulty: 3, category: "math-logic", type: "text", time_limit: 20,
    text: "Un escargot grimpe un mur de 10m. Chaque jour il monte de 3m, chaque nuit il glisse de 2m. En combien de jours atteint-il le sommet ?",
    choices: ["10 jours", "8 jours", "7 jours", "5 jours"],
    correct_index: 1,
    explanation: "Chaque jour net = +1m. Apres 7 jours il est a 7m. Le 8e jour il monte de 3m → 10m, il est au sommet avant de glisser.",
    svg_config: null,
  },
  {
    difficulty: 3, category: "pattern", type: "svg", time_limit: 15,
    text: "Quel element complete la grille 3x3 ?",
    choices: ["Triangle bleu", "Cercle rouge", "Carre vert", "Triangle rouge"],
    correct_index: 0,
    explanation: "Chaque ligne et colonne contient un cercle, un carre et un triangle, chacun d'une couleur differente. La case manquante doit etre un triangle bleu.",
    svg_config: { renderer: "GridLogic", params: { size: 3, shapes: [["circle-red","square-blue","triangle-green"],["square-green","triangle-red","circle-blue"],["triangle-blue",null,null]], missing: [2,1] } },
  },
  {
    difficulty: 3, category: "deduction", type: "text", time_limit: 20,
    text: "Il y a 5 maisons de couleurs differentes. L'anglais vit dans la maison rouge. L'espagnol a un chien. Le cafe est bu dans la maison verte. Qui boit du the ?",
    choices: ["L'anglais", "L'espagnol", "Le norvegien", "Pas assez d'info"],
    correct_index: 3,
    explanation: "Avec seulement ces 3 indices, on ne peut pas determiner qui boit du the. Il manque des contraintes (c'est une version simplifiee de l'enigme d'Einstein).",
    svg_config: null,
  },

  // ===== DIFFICULTE 4 — MOYEN- (20s) =====
  {
    difficulty: 4, category: "sequence", type: "text", time_limit: 20,
    text: "Quelle est la suite : 2, 6, 14, 30, ?",
    choices: ["46", "60", "62", "58"],
    correct_index: 2,
    explanation: "Chaque terme = precedent × 2 + 2. (2→6: 2×2+2=6, 6→14: 6×2+2=14, 14→30: 14×2+2=30, 30→62: 30×2+2=62).",
    svg_config: null,
  },
  {
    difficulty: 4, category: "deduction", type: "text", time_limit: 30,
    text: "Alice dit : 'Bob ment'. Bob dit : 'Charlie ment'. Charlie dit : 'Alice et Bob mentent'. Si exactement un des trois dit la verite, qui ?",
    choices: ["Alice", "Bob", "Charlie", "Impossible a determiner"],
    correct_index: 1,
    explanation: "Si Bob dit vrai : Charlie ment. Comme Charlie ment en disant 'les deux mentent', au moins un (Alice ou Bob) dit vrai. Bob dit vrai, coherent. Alice dit que Bob ment → Alice ment. Coherent : seul Bob dit vrai.",
    svg_config: null,
  },
  {
    difficulty: 4, category: "math-logic", type: "text", time_limit: 20,
    text: "Un baton mesure 1 metre et demi plus la moitie de sa longueur. Quelle est sa longueur ?",
    choices: ["2 metres", "2.5 metres", "3 metres", "1.75 metres"],
    correct_index: 2,
    explanation: "Soit L la longueur. L = 1.5 + L/2. Donc L - L/2 = 1.5, L/2 = 1.5, L = 3 metres.",
    svg_config: null,
  },
  {
    difficulty: 4, category: "probability", type: "text", time_limit: 20,
    text: "J'ai 2 enfants. L'un d'eux est un garcon. Quelle est la probabilite que les deux soient des garcons ?",
    choices: ["1/2", "1/3", "1/4", "2/3"],
    correct_index: 1,
    explanation: "Les combinaisons possibles avec au moins un garcon : GG, GF, FG. Seule GG a deux garcons. Probabilite = 1/3.",
    svg_config: null,
  },
  {
    difficulty: 4, category: "pattern", type: "text", time_limit: 20,
    text: "Si MAISON = 6, CHAT = 4, ARBRE = 5, alors LOGIQUE = ?",
    choices: ["5", "6", "7", "8"],
    correct_index: 2,
    explanation: "Chaque mot vaut son nombre de lettres. MAISON = 6 lettres, CHAT = 4, ARBRE = 5. LOGIQUE = 7 lettres.",
    svg_config: null,
  },
  {
    difficulty: 4, category: "lateral", type: "text", time_limit: 25,
    text: "Un homme regarde un portrait et dit : 'Je n'ai ni frere ni soeur, mais le pere de cet homme est le fils de mon pere.' Qui est sur le portrait ?",
    choices: ["Lui-meme", "Son pere", "Son fils", "Son grand-pere"],
    correct_index: 2,
    explanation: "'Le fils de mon pere' = lui-meme (car pas de frere). Donc 'le pere de cet homme est moi-meme'. L'homme sur le portrait est son fils.",
    svg_config: null,
  },
  {
    difficulty: 4, category: "sequence", type: "text", time_limit: 25,
    text: "61, 52, 63, 94, 46, ?",
    choices: ["18", "28", "38", "57"],
    correct_index: 0,
    explanation: "Chaque nombre est l'inverse d'un carre : 16→61, 25→52, 36→63, 49→94, 64→46, 81→18.",
    svg_config: null,
  },
  {
    difficulty: 4, category: "deduction", type: "text", time_limit: 20,
    text: "Il faut 5 machines, 5 minutes pour fabriquer 5 gadgets. Combien faut-il de temps a 100 machines pour fabriquer 100 gadgets ?",
    choices: ["100 minutes", "5 minutes", "20 minutes", "1 minute"],
    correct_index: 1,
    explanation: "Chaque machine met 5 minutes pour 1 gadget. 100 machines fabriquent 100 gadgets en 5 minutes (en parallele).",
    svg_config: null,
  },
  {
    difficulty: 4, category: "pattern", type: "svg", time_limit: 20,
    text: "Quelle figure equilibre la balance ?",
    choices: ["1 cercle", "2 cercles", "3 cercles", "4 cercles"],
    correct_index: 1,
    explanation: "D'apres la premiere balance : 1 carre = 3 cercles. La deuxieme montre 2 carres vs ? cercles. 2 × 3 = 6... mais un cote a deja 4 cercles, il en manque 2.",
    svg_config: { renderer: "BalanceScale", params: { equations: [{ left: ["square"], right: ["circle","circle","circle"] }], question: { left: ["square","circle"], right: ["circle","circle","circle","?"] }, answer: 2 } },
  },
  {
    difficulty: 4, category: "math-logic", type: "text", time_limit: 20,
    text: "Quel est le plus petit nombre de pieces de monnaie necessaire pour pouvoir donner n'importe quel montant exact de 1 a 15 centimes ?",
    choices: ["4", "5", "6", "8"],
    correct_index: 0,
    explanation: "Avec des pieces de 1, 2, 4 et 8 centimes (systeme binaire), on peut faire n'importe quel montant de 1 a 15. Il faut 4 pieces.",
    svg_config: null,
  },

  // ===== DIFFICULTE 5 — MOYEN (20s) =====
  {
    difficulty: 5, category: "probability", type: "text", time_limit: 30,
    text: "Le probleme de Monty Hall : 3 portes, 1 voiture, 2 chevres. Vous choisissez une porte. Le presentateur ouvre une autre porte (avec une chevre). Devez-vous changer ?",
    choices: ["Oui, 2/3 de chances", "Non, 1/2 de chances", "Ca ne change rien", "Oui, 3/4 de chances"],
    correct_index: 0,
    explanation: "En changeant, vous gagnez 2/3 du temps. Votre choix initial a 1/3 de chances d'etre bon. La porte restante concentre les 2/3 restants.",
    svg_config: null,
  },
  {
    difficulty: 5, category: "deduction", type: "text", time_limit: 20,
    text: "Sur une ile, les chevaliers disent toujours vrai, les menteurs toujours faux. A dit : 'Nous sommes tous les deux des menteurs.' Que sont A et B ?",
    choices: ["A chevalier, B menteur", "A menteur, B chevalier", "Tous deux menteurs", "Tous deux chevaliers"],
    correct_index: 1,
    explanation: "Si A etait chevalier, il dirait vrai, mais 'nous sommes tous les deux menteurs' serait faux. Contradiction. Donc A est menteur. Sa phrase est fausse, donc ils ne sont PAS tous les deux menteurs → B est chevalier.",
    svg_config: null,
  },
  {
    difficulty: 5, category: "math-logic", type: "text", time_limit: 30,
    text: "Vous avez 12 boules identiques, l'une est plus lourde. Avec une balance a plateaux, quel est le minimum de pesees pour la trouver ?",
    choices: ["2", "3", "4", "6"],
    correct_index: 1,
    explanation: "Divisez en 3 groupes de 4. Pesee 1 : 4 vs 4. Si equilibre, la boule est dans le 3e groupe. Repetez avec des groupes de plus en plus petits. 3 pesees suffisent (3³ = 27 > 12).",
    svg_config: null,
  },
  {
    difficulty: 5, category: "sequence", type: "text", time_limit: 30,
    text: "Quelle est la suite : 1, 11, 21, 1211, 111221, ?",
    choices: ["312211", "122211", "212221", "131221"],
    correct_index: 0,
    explanation: "C'est la suite 'look and say'. 1→'un 1'=11→'deux 1'=21→'un 2 un 1'=1211→'un 1 un 2 deux 1'=111221→'trois 1 deux 2 un 1'=312211.",
    svg_config: null,
  },
  {
    difficulty: 5, category: "lateral", type: "text", time_limit: 30,
    text: "Un prisonnier doit choisir entre 2 portes. Devant chaque porte, un gardien. L'un ment toujours, l'autre dit toujours vrai. Il peut poser UNE question a UN gardien. Que demande-t-il ?",
    choices: ["'Quelle porte mene a la liberte ?'", "'Es-tu le menteur ?'", "'Que dirait l'autre gardien si je lui demandais quelle porte mene a la liberte ?'", "'Quelle porte choisirais-tu ?'"],
    correct_index: 2,
    explanation: "En demandant ce que l'AUTRE dirait, on obtient toujours la mauvaise porte (double negation). Il suffit de choisir l'AUTRE porte.",
    svg_config: null,
  },
  {
    difficulty: 5, category: "deduction", type: "text", time_limit: 35,
    text: "5 pirates se partagent 100 pieces d'or. Le plus ancien propose un partage, vote a la majorite (egalite = accepte). S'il est rejete, il meurt et le suivant propose. Que propose le pirate 1 ?",
    choices: ["98 pour lui, 0, 1, 0, 1", "20 pour chacun", "100 pour lui", "96 pour lui, 0, 1, 0, 3"],
    correct_index: 0,
    explanation: "Par induction a rebours : le pirate 1 donne 1 piece aux pirates 3 et 5 (qui acceptent car ils auraient moins sans lui). Il garde 98.",
    svg_config: null,
  },
  {
    difficulty: 5, category: "math-logic", type: "text", time_limit: 20,
    text: "Un nenuhar double de taille chaque jour. Il couvre tout l'etang en 48 jours. En combien de jours couvre-t-il la moitie ?",
    choices: ["24 jours", "47 jours", "36 jours", "42 jours"],
    correct_index: 1,
    explanation: "S'il double chaque jour et couvre tout au jour 48, il couvrait la moitie au jour 47.",
    svg_config: null,
  },
  {
    difficulty: 5, category: "pattern", type: "text", time_limit: 20,
    text: "Si 1=5, 2=25, 3=125, 4=625, alors 5= ?",
    choices: ["3125", "1", "5", "25"],
    correct_index: 1,
    explanation: "Piège ! L'énoncé dit explicitement que 1=5. Si 1=5, alors par symétrie 5=1. Ce n'est pas un calcul de puissances de 5, c'est une relation d'égalité.",
    svg_config: null,
  },
  {
    difficulty: 5, category: "sequence", type: "text", time_limit: 20,
    text: "Quelle est la prochaine lettre : J, F, M, A, M, J, J, ?",
    choices: ["A", "S", "K", "O"],
    correct_index: 0,
    explanation: "Ce sont les initiales des mois : Janvier, Fevrier, Mars, Avril, Mai, Juin, Juillet, Aout. A pour Aout.",
    svg_config: null,
  },
  {
    difficulty: 5, category: "deduction", type: "text", time_limit: 25,
    text: "3 interrupteurs dans une piece, 1 ampoule dans une autre (invisible). Vous pouvez aller voir l'ampoule UNE seule fois. Comment trouver quel interrupteur controle l'ampoule ?",
    choices: ["Allumer les 3 et voir", "Allumer le 1, attendre, eteindre, allumer le 2, aller voir", "Impossible", "Allumer et eteindre rapidement"],
    correct_index: 1,
    explanation: "Allumez l'interrupteur 1 pendant 5min, eteignez-le, allumez le 2. Allez voir : ampoule allumee = inter 2, eteinte + chaude = inter 1, eteinte + froide = inter 3.",
    svg_config: null,
  },

  // ===== DIFFICULTE 6 — MOYEN+ (25s) =====
  {
    difficulty: 6, category: "probability", type: "text", time_limit: 25,
    text: "Vous lancez un de a 6 faces. Quel est le nombre moyen de lancers necessaires pour obtenir un 6 ?",
    choices: ["3", "6", "5", "4"],
    correct_index: 1,
    explanation: "Avec une probabilite de 1/6 a chaque lancer, l'esperance est 1/(1/6) = 6 lancers en moyenne.",
    svg_config: null,
  },
  {
    difficulty: 6, category: "deduction", type: "text", time_limit: 30,
    text: "100 casiers fermes, 100 etudiants. L'etudiant 1 ouvre tout. L'etudiant 2 change chaque 2e casier. L'etudiant 3 chaque 3e... Quels casiers sont ouverts a la fin ?",
    choices: ["Les nombres premiers", "Les carres parfaits", "Les nombres pairs", "Aucun"],
    correct_index: 1,
    explanation: "Un casier est ouvert s'il a ete change un nombre impair de fois. Seuls les carres parfaits ont un nombre impair de diviseurs. Ouverts : 1, 4, 9, 16, 25, 36, 49, 64, 81, 100.",
    svg_config: null,
  },
  {
    difficulty: 6, category: "math-logic", type: "text", time_limit: 25,
    text: "Combien de fois les aiguilles d'une horloge se superposent-elles en 24 heures ?",
    choices: ["24", "22", "23", "12"],
    correct_index: 1,
    explanation: "En 12h, les aiguilles se croisent 11 fois (pas 12 : elles se superposent vers 12h00 mais le croisement entre 10h et 12h absorbe celui de 11h). En 24h : 22 fois.",
    svg_config: null,
  },
  {
    difficulty: 6, category: "lateral", type: "text", time_limit: 25,
    text: "Un avion s'ecrase exactement sur la frontiere entre la France et la Belgique. Ou enterre-t-on les survivants ?",
    choices: ["En France", "En Belgique", "Au milieu", "On n'enterre pas les survivants"],
    correct_index: 3,
    explanation: "On n'enterre pas les SURVIVANTS ! Ils sont vivants.",
    svg_config: null,
  },
  {
    difficulty: 6, category: "sequence", type: "text", time_limit: 25,
    text: "Quelle est la suite : 0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ?",
    choices: ["134", "144", "155", "123"],
    correct_index: 1,
    explanation: "Suite de Fibonacci : 55 + 89 = 144.",
    svg_config: null,
  },
  {
    difficulty: 6, category: "deduction", type: "text", time_limit: 30,
    text: "Trois boites : une avec des pommes, une avec des oranges, une mixte. Chaque etiquette est FAUSSE. Vous tirez un fruit de la boite 'Mixte'. C'est une pomme. Que contient chaque boite ?",
    choices: ["Mixte=Pommes, Pommes=Oranges, Oranges=Mixte", "Mixte=Pommes, Pommes=Mixte, Oranges=Oranges", "On ne peut pas savoir", "Mixte=Oranges, Pommes=Mixte, Oranges=Pommes"],
    correct_index: 0,
    explanation: "La boite 'Mixte' a une fausse etiquette + vous tirez une pomme → elle ne contient QUE des pommes. La boite 'Pommes' (fausse) n'est pas pommes ni pommes-et-oranges (prise) → elle est oranges. La boite 'Oranges' est donc mixte.",
    svg_config: null,
  },
  {
    difficulty: 6, category: "math-logic", type: "text", time_limit: 40,
    text: "Trouvez le chiffre manquant : 8809=6, 7111=0, 2172=0, 6666=4, 1111=0, 3213=0, 7662=2, 9313=1, 0000=4, 2222=0, 3333=0, 5555=0, 8193=3, 8096=5, 7777=0, 9999=4, 7756=1, 6855=3, 9881=5, 5531=0. 2581=?",
    choices: ["2", "3", "4", "5"],
    correct_index: 2,
    explanation: "On compte le nombre de trous/boucles fermees dans chaque chiffre. 0→1, 8→2, 6→1, 9→1. Les autres (1,2,3,5,7) → 0. 2581 : 2(0)+5(0)+8(2)+1(0) = 4 anneaux.",
    svg_config: null,
  },
  {
    difficulty: 6, category: "pattern", type: "svg", time_limit: 25,
    text: "Completez la grille logique 3x3 :",
    choices: ["Etoile noire", "Cercle blanc", "Triangle gris", "Carre noir"],
    correct_index: 0,
    explanation: "Chaque ligne et colonne contient une forme unique (cercle, carre, etoile) et une couleur unique (blanc, gris, noir). La case manquante doit etre une etoile noire.",
    svg_config: { renderer: "GridLogic", params: { size: 3, shapes: [["circle-white","square-gray","star-black"],["square-black","star-white","circle-gray"],["star-black","circle-white","square-gray"]], missing: [2,0] } },
  },
  {
    difficulty: 6, category: "probability", type: "text", time_limit: 25,
    text: "Le paradoxe des anniversaires : combien de personnes faut-il pour avoir >50% de chances que deux partagent le meme anniversaire ?",
    choices: ["183", "23", "50", "365"],
    correct_index: 1,
    explanation: "Il suffit de 23 personnes ! C'est contre-intuitif car on compare toutes les paires (253 paires pour 23 personnes), pas juste chaque personne avec les 364 jours restants.",
    svg_config: null,
  },
  {
    difficulty: 6, category: "deduction", type: "text", time_limit: 25,
    text: "Vous avez 8 balles identiques. L'une est plus lourde. Avec une balance a plateaux et seulement 2 pesees, comment la trouver ?",
    choices: ["Peser 4 contre 4, puis 2 contre 2", "Peser 3 contre 3, puis selon le resultat", "Impossible en 2 pesees", "Peser 1 contre 1 quatre fois"],
    correct_index: 1,
    explanation: "Pesez 3 vs 3. Si equilibre : la lourde est dans les 2 restantes, pesez-les. Si desequilibre : prenez le cote lourd (3 balles), pesez 1 vs 1. Si equilibre, c'est la 3e.",
    svg_config: null,
  },

  // ===== DIFFICULTE 7 — DIFFICILE (25s) =====
  {
    difficulty: 7, category: "paradox", type: "text", time_limit: 25,
    text: "Le paradoxe du barbier : un barbier rase tous ceux qui ne se rasent pas eux-memes. Le barbier se rase-t-il lui-meme ?",
    choices: ["Oui", "Non", "Parfois", "La question est un paradoxe sans reponse"],
    correct_index: 3,
    explanation: "S'il se rase lui-meme, il ne devrait pas (il rase ceux qui NE se rasent PAS). S'il ne se rase pas, il devrait se raser. C'est le paradoxe de Russell : l'enonce est logiquement contradictoire.",
    svg_config: null,
  },
  {
    difficulty: 7, category: "probability", type: "text", time_limit: 25,
    text: "Vous etes dans un jeu TV. Vous avez gagne 1000€. On vous propose de jouer a pile ou face : pile vous gagnez 2000€ de plus, face vous perdez 1000€. Que dit la theorie de l'utilite ?",
    choices: ["Toujours jouer (esperance positive)", "Ne pas jouer (aversion au risque)", "Ca depend de votre fortune totale", "Jouer si la piece est truquee"],
    correct_index: 2,
    explanation: "L'esperance est positive (+500€ en moyenne), mais la theorie de l'utilite dit que ca depend de votre richesse totale. L'utilite marginale decroit : perdre 1000€ quand on est pauvre 'fait plus mal' que gagner 2000€.",
    svg_config: null,
  },
  {
    difficulty: 7, category: "math-logic", type: "text", time_limit: 30,
    text: "Deux cordes mettent chacune exactement 1h a bruler (mais pas uniformement). Comment mesurer exactement 45 minutes ?",
    choices: ["Allumer une corde et attendre 3/4", "Allumer les deux bouts d'une corde + un bout de l'autre", "Impossible", "Couper une corde en 4"],
    correct_index: 1,
    explanation: "Allumez la corde A aux DEUX bouts + la corde B a un bout. A brule en 30 min (deux bouts). A ce moment, allumez l'autre bout de B. B brule encore 15 min. Total : 45 min.",
    svg_config: null,
  },
  {
    difficulty: 7, category: "deduction", type: "text", time_limit: 25,
    text: "3 sages ont chacun un chapeau (blanc ou noir) pris parmi 3 blancs et 2 noirs. Ils voient les chapeaux des autres mais pas le leur. Le 1er dit 'Je ne sais pas'. Le 2e dit 'Je ne sais pas'. Le 3e (aveugle) dit 'Je sais !'. Quelle couleur ?",
    choices: ["Noir", "Blanc", "Ca depend", "Impossible a determiner"],
    correct_index: 1,
    explanation: "Si les 2 premiers avaient vu 2 noirs, ils auraient su (blanc force). L'un puis l'autre ne sait pas, donc il n'y a pas 2 noirs visibles. Le 3e (aveugle) deduit par elimination : son chapeau est blanc.",
    svg_config: null,
  },
  {
    difficulty: 7, category: "sequence", type: "text", time_limit: 25,
    text: "Quelle est la suite : 1, 2, 4, 8, 16, 31, ?",
    choices: ["32", "57", "62", "64"],
    correct_index: 1,
    explanation: "Ce N'EST PAS les puissances de 2 ! C'est le nombre maximal de regions creees par n points sur un cercle. Formule : C(n,4)+C(n,2)+1. Pour n=7 : C(7,4)+C(7,2)+1 = 35+21+1 = 57.",
    svg_config: null,
  },
  {
    difficulty: 7, category: "lateral", type: "text", time_limit: 25,
    text: "Un homme entre dans un bar et demande un verre d'eau. Le barman sort un pistolet et le pointe sur lui. L'homme dit 'merci' et part. Pourquoi ?",
    choices: ["Le barman est fou", "L'homme avait le hoquet", "C'est un reve", "Le pistolet etait a eau"],
    correct_index: 1,
    explanation: "L'homme avait le hoquet et voulait de l'eau. Le barman a trouve un meilleur remede : lui faire peur. Ca a marche, d'ou le 'merci'.",
    svg_config: null,
  },
  {
    difficulty: 7, category: "math-logic", type: "text", time_limit: 35,
    text: "Vous avez une jarre de 3L et une de 5L. Comment mesurer exactement 4L ?",
    choices: ["Remplir 5L, vider 3L dedans, garder 2L, remplir 3L, ajouter les 2L", "Remplir 5L, vider dans 3L (reste 2 dans 5L), vider 3L, verser 2L dans 3L, remplir 5L, verser dans 3L", "Impossible", "Remplir les deux et soustraire"],
    correct_index: 1,
    explanation: "5L→3L (reste 2 dans 5L). Vider 3L. 2L→3L. Remplir 5L. 5L→3L (il reste 1L de place dans 3L). Resultat : 4L dans la jarre de 5L.",
    svg_config: null,
  },
  {
    difficulty: 7, category: "deduction", type: "text", time_limit: 35,
    text: "Les yeux bleus : sur une ile, 100 personnes aux yeux bleus et d'autres aux yeux marrons. Personne ne connait sa propre couleur. Un oracle dit : 'Il y a au moins une personne aux yeux bleus.' Apres combien de jours les yeux bleus partent ?",
    choices: ["1 jour", "100 jours", "50 jours", "Jamais"],
    correct_index: 1,
    explanation: "C'est le probleme du savoir commun. Si 1 personne → part jour 1. Si 2 → jour 2 (chacun voit 1 et deduit). Par induction, 100 personnes partent le jour 100.",
    svg_config: null,
  },
  {
    difficulty: 7, category: "pattern", type: "svg", time_limit: 25,
    text: "Quel est l'element manquant dans cette suite de transformations ?",
    choices: ["Figure A", "Figure B", "Figure C", "Figure D"],
    correct_index: 1,
    explanation: "A chaque etape, la figure subit une rotation de 45° et un element est ajoute. La figure B est la seule qui suit cette double transformation.",
    svg_config: { renderer: "PatternSequence", params: { shapes: ["triangle-0", "triangle-45-dot", "triangle-90-dot-dot", "?"], rotationStep: 45, addElement: true, answer: 1 } },
  },
  {
    difficulty: 7, category: "probability", type: "text", time_limit: 30,
    text: "100 passagers montent dans un avion de 100 places. Le premier a perdu son billet et s'assied au hasard. Les suivants prennent leur place si libre, sinon une place au hasard. Quelle est la probabilite que le dernier passager ait sa place ?",
    choices: ["1/100", "1/2", "99/100", "0"],
    correct_index: 1,
    explanation: "Surprenant : la probabilite est exactement 1/2, quel que soit le nombre de passagers. Le dernier siege libre est toujours soit la place du passager 1, soit celle du passager 100, avec probabilite egale.",
    svg_config: null,
  },

  // ===== DIFFICULTE 8 — TRES DIFFICILE (30s) =====
  {
    difficulty: 8, category: "math-logic", type: "text", time_limit: 40,
    text: "Vous avez 25 chevaux et pouvez faire des courses de 5. Sans chronometre, quel est le minimum de courses pour trouver les 3 plus rapides ?",
    choices: ["5", "6", "7", "8"],
    correct_index: 2,
    explanation: "5 courses pour les groupes. 1 course des 5 gagnants. Puis 1 course finale avec le 2e et 3e du groupe du gagnant global + le 2e du groupe du 2e + le 3e du gagnant des gagnants. Total : 7.",
    svg_config: null,
  },
  {
    difficulty: 8, category: "deduction", type: "text", time_limit: 40,
    text: "Alice, Bob et Charlie ont des nombres sur le front (entiers positifs, l'un est la somme des deux autres). Chacun voit les deux autres. Alice(20), Bob(30) voient les nombres des autres. Tour 1 : tous disent 'je ne sais pas'. Tour 2 : tous disent 'je ne sais pas'. Tour 3 : quelqu'un sait. Quel est le nombre de Charlie ?",
    choices: ["10", "50", "20", "30"],
    correct_index: 0,
    explanation: "Charlie voit 20 et 30. Son nombre est soit 50 (somme) soit 10 (difference). Apres 2 tours de 'je ne sais pas', l'elimination progressive montre que Charlie = 10.",
    svg_config: null,
  },
  {
    difficulty: 8, category: "probability", type: "text", time_limit: 30,
    text: "Le probleme de l'enveloppe : deux enveloppes contiennent de l'argent, l'une le double de l'autre. Vous en ouvrez une : 100€. Devez-vous echanger ?",
    choices: ["Oui, esperance = 125€", "Non, esperance = 100€", "Ca ne change rien", "C'est un paradoxe"],
    correct_index: 3,
    explanation: "C'est un paradoxe ! Le calcul naif dit : 50% de 200€ + 50% de 50€ = 125€ → echanger. Mais la meme logique s'applique APRES l'echange, creant une boucle infinie. Le raisonnement bayesien montre que sans prior sur les montants, echanger ne change pas l'esperance.",
    svg_config: null,
  },
  {
    difficulty: 8, category: "lateral", type: "text", time_limit: 30,
    text: "Un roi demande a ses 1000 vignerons de gouter 1000 tonneaux de vin pour trouver l'unique tonneau empoisonne. Le poison tue en exactement 1 mois. Le banquet est dans 1 mois. Quel est le nombre MINIMUM de gouteurs necessaires ?",
    choices: ["500", "100", "10", "32"],
    correct_index: 2,
    explanation: "10 gouteurs suffisent ! Numerotez les tonneaux en binaire (10 bits = 1024 > 1000). Chaque gouteur boit de tous les tonneaux dont son bit correspondant est 1. Apres 1 mois, les morts forment le nombre binaire du tonneau empoisonne.",
    svg_config: null,
  },
  {
    difficulty: 8, category: "math-logic", type: "text", time_limit: 30,
    text: "Le probleme de Josephus : 41 soldats en cercle. Chaque 3e est elimine. Ou devez-vous vous placer pour survivre ?",
    choices: ["Position 1", "Position 31", "Position 11", "Position 41"],
    correct_index: 1,
    explanation: "En appliquant la recurrence de Josephus J(n,k) = (J(n-1,k) + k) mod n avec n=41 et k=3, la position gagnante est 31 (indexe a partir de 1).",
    svg_config: null,
  },
  {
    difficulty: 8, category: "deduction", type: "text", time_limit: 35,
    text: "Le probleme des 100 prisonniers : 100 tiroirs numerotes, chacun contient un numero unique. Chaque prisonnier peut ouvrir 50 tiroirs. Ils sont liberes si TOUS trouvent leur numero. Quelle est la meilleure strategie ?",
    choices: ["Chacun ouvre 50 tiroirs au hasard (~0%)", "Suivre les cycles (chacun commence par son numero)", "Le premier memorise et communique", "Impossible"],
    correct_index: 1,
    explanation: "La strategie des cycles : chaque prisonnier ouvre le tiroir de son numero, puis le tiroir indique par le numero trouve, etc. Cela marche si aucun cycle ne depasse 50. Probabilite de succes : ~31% ! Bien mieux que le hasard (~0%).",
    svg_config: null,
  },
  {
    difficulty: 8, category: "sequence", type: "text", time_limit: 30,
    text: "Quelle est la suite : 2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, ?",
    choices: ["33", "35", "37", "39"],
    correct_index: 2,
    explanation: "Ce sont les nombres premiers dans l'ordre. Apres 31, le prochain premier est 37.",
    svg_config: null,
  },
  {
    difficulty: 8, category: "paradox", type: "text", time_limit: 30,
    text: "Le paradoxe de Newcomb : un etre omniscient a predit votre choix. Boite A : 1000€. Boite B : 1M€ si l'etre predit que vous prenez SEULEMENT B, vide sinon. Prenez-vous A+B ou seulement B ?",
    choices: ["A+B (dominance)", "Seulement B (esperance)", "Ca depend de votre croyance en l'etre", "Les deux choix sont equivalents"],
    correct_index: 2,
    explanation: "Ce paradoxe divise les philosophes. Les 'causalistes' prennent A+B (la boite B est deja remplie ou non). Les 'evidentialistes' prennent B (correle a 1M€). Pas de consensus !",
    svg_config: null,
  },
  {
    difficulty: 8, category: "pattern", type: "svg", time_limit: 30,
    text: "Combien de triangles voyez-vous dans cette figure ?",
    choices: ["8", "13", "18", "24"],
    correct_index: 2,
    explanation: "Dans un grand triangle subdivise par 3 medianes, on trouve : 6 petits triangles + 6 triangles moyens (2 petits) + 6 grands triangles (3 petits). Attention a ne pas compter ceux formes par les medianes qui se croisent. Total : 18.",
    svg_config: { renderer: "PatternSequence", params: { type: "triangle-count", subdivisions: 3, answer: 18 } },
  },
  {
    difficulty: 8, category: "math-logic", type: "text", time_limit: 30,
    text: "Vous etes sur un segment [0,1]. Un point est choisi uniformement au hasard. Vous devez ecrire un nombre. Si votre nombre est plus proche du point que celui de votre adversaire, vous gagnez. Votre adversaire joue 1/2. Que jouez-vous ?",
    choices: ["1/2 aussi", "1/4", "Juste a cote de 1/2 (comme 0.49)", "3/4"],
    correct_index: 2,
    explanation: "En jouant juste a cote de 1/2 (ex: 0.4999), vous capturez presque tout l'intervalle [0, 0.5) alors que votre adversaire ne garde que [0.5, 0.75]. C'est le theoreme du votant median applique.",
    svg_config: null,
  },

  // ===== DIFFICULTE 9 — EXPERT (30s) =====
  {
    difficulty: 9, category: "math-logic", type: "text", time_limit: 30,
    text: "Le probleme de Monty Hall generalise : 100 portes, 1 voiture, 99 chevres. Vous choisissez une porte. Le presentateur ouvre 98 portes (chevres). Devez-vous changer ?",
    choices: ["Oui, 99/100", "Non, 1/2", "Ca ne change rien", "Oui, 98/100"],
    correct_index: 0,
    explanation: "Meme logique que le Monty Hall classique mais amplifie. Votre choix initial a 1/100 de chances. La porte restante concentre 99/100. Il faut TOUJOURS changer.",
    svg_config: null,
  },
  {
    difficulty: 9, category: "deduction", type: "text", time_limit: 30,
    text: "3 chapeaux (2 blancs, 1 noir) sur 3 personnes en file. Chacun voit ceux devant. Le 3e (derriere) dit 'je ne sais pas'. Le 2e dit 'je ne sais pas'. Que sait le 1er (devant) ?",
    choices: ["Son chapeau est blanc", "Son chapeau est noir", "Il ne peut pas savoir", "Ca depend"],
    correct_index: 0,
    explanation: "Le 3e voit les 2 devant. S'il voyait 2 noirs, il saurait (blanc force, il n'y a qu'1 noir). Il dit 'je ne sais pas' → il ne voit PAS 2 noirs. Le 2e le sait. S'il voyait un noir devant lui, il deduirait qu'il est blanc. Il dit 'je ne sais pas' → le 1er n'a pas un chapeau noir. Donc le 1er sait : il est blanc.",
    svg_config: null,
  },
  {
    difficulty: 9, category: "probability", type: "text", time_limit: 35,
    text: "Le probleme de la secretaire : vous interviewez 100 candidats sequentiellement. Vous devez embaucher ou rejeter immediatement. Quelle est la strategie optimale ?",
    choices: ["Rejeter les 37 premiers, puis prendre le prochain meilleur", "Prendre le premier excellent", "Rejeter les 50 premiers", "Prendre le dernier"],
    correct_index: 0,
    explanation: "La strategie optimale est de rejeter les premiers n/e ≈ 37 candidats (e ≈ 2.718), puis de prendre le premier candidat meilleur que tous les precedents. Probabilite de trouver le meilleur : ~37%.",
    svg_config: null,
  },
  {
    difficulty: 9, category: "paradox", type: "text", time_limit: 30,
    text: "Le paradoxe de Saint-Petersbourg : on lance une piece jusqu'a obtenir face. Si face au lancer n, vous gagnez 2^n euros. Combien paieriez-vous pour jouer ?",
    choices: ["2€ (gain moyen)", "L'esperance est infinie", "4€", "10€"],
    correct_index: 1,
    explanation: "L'esperance = 1/2×2 + 1/4×4 + 1/8×8 + ... = 1+1+1+... = infini ! Pourtant personne ne paierait 1000€ pour jouer. Ce paradoxe a mene a la theorie de l'utilite (Bernoulli).",
    svg_config: null,
  },
  {
    difficulty: 9, category: "math-logic", type: "text", time_limit: 30,
    text: "Sur une table ronde, Alice et Bob posent alternativement des pieces de 1€ (sans chevauchement). Celui qui ne peut plus poser perd. Qui a une strategie gagnante ?",
    choices: ["Alice (premier joueur)", "Bob (second joueur)", "Aucun des deux", "Ca depend de la taille de la table"],
    correct_index: 0,
    explanation: "Alice joue au centre exact. Ensuite, elle copie symetriquement chaque coup de Bob (par rapport au centre). Bob sera toujours le premier a ne plus pouvoir jouer.",
    svg_config: null,
  },
  {
    difficulty: 9, category: "deduction", type: "text", time_limit: 40,
    text: "Deux amis pensent chacun a un entier positif. Leur somme est 11. Chacun connait la somme. A dit : 'Je ne connais pas ton nombre.' B dit : 'Je ne connais pas ton nombre.' A dit : 'Maintenant je connais ton nombre !' Quel est le nombre de A ?",
    choices: ["3", "4", "5", "6"],
    correct_index: 3,
    explanation: "Somme=11, entiers positifs : paires possibles (1,10) (2,9) (3,8) (4,7) (5,6) etc. Si A avait 1 ou 10, il saurait (une seule paire). A dit 'je ne sais pas' → A est entre 2 et 9. B raisonne pareil → B est entre 2 et 9. Au 2e tour, les paires restantes se reduisent. Au 3e tour, A peut deduire : A=6, B=5.",
    svg_config: null,
  },
  {
    difficulty: 9, category: "lateral", type: "text", time_limit: 40,
    text: "Vous devez traverser un pont en 17 minutes avec 3 amis. Il fait nuit, vous avez une lampe. Le pont supporte 2 personnes max. Temps individuels : 1min, 2min, 5min, 10min. Comment faire ?",
    choices: ["1+10, 1 revient, 1+5, 1 revient, 1+2 = 19min", "1+2, 1 revient, 5+10, 2 revient, 1+2 = 17min", "Impossible en 17min", "1+2, 2 revient, 5+10, 1 revient, 1+2 = 19min"],
    correct_index: 1,
    explanation: "L'astuce : envoyer les deux plus lents ensemble ! 1+2 vont (2min). 1 revient (1min). 5+10 vont (10min). 2 revient (2min). 1+2 vont (2min). Total : 17min.",
    svg_config: null,
  },
  {
    difficulty: 9, category: "math-logic", type: "text", time_limit: 35,
    text: "Combien de zeros a la fin de 100! (factorielle de 100) ?",
    choices: ["10", "20", "24", "25"],
    correct_index: 2,
    explanation: "On compte les facteurs 5 dans 100! : ⌊100/5⌋ + ⌊100/25⌋ + ⌊100/125⌋ = 20 + 4 + 0 = 24. (Les facteurs 2 sont toujours plus nombreux.)",
    svg_config: null,
  },
  {
    difficulty: 9, category: "paradox", type: "text", time_limit: 30,
    text: "Le dilemme du prisonnier itere : vous jouez 200 tours contre un adversaire. Cooperer rapporte 3/3 (mutuel), trahir rapporte 5/0 (unilateral). La meilleure strategie connue ?",
    choices: ["Toujours trahir", "Toujours cooperer", "Tit-for-Tat (copier le coup precedent)", "Aleatoire 50/50"],
    correct_index: 2,
    explanation: "Tit-for-Tat (Anatol Rapoport) : cooperer au 1er tour, puis copier le dernier coup de l'adversaire. Simple, previsible, pardonne. Gagnant du tournoi d'Axelrod en 1984.",
    svg_config: null,
  },
  {
    difficulty: 9, category: "deduction", type: "text", time_limit: 45,
    text: "Sum and Product puzzle : X et Y sont deux entiers entre 2 et 99. S connait S=X+Y, P connait P=X*Y. S dit : 'P ne peut pas connaitre X et Y'. P dit : 'Maintenant je connais X et Y'. S dit : 'Maintenant moi aussi'. X et Y ?",
    choices: ["4 et 13", "3 et 11", "2 et 6", "4 et 7"],
    correct_index: 0,
    explanation: "C'est le puzzle de Freudenthal. Apres analyse exhaustive des contraintes d'information : X=4, Y=13 (S=17, P=52). C'est l'unique solution ou les declarations sont coherentes.",
    svg_config: null,
  },

  // ===== DIFFICULTE 10 — IMPOSSIBLE (45s) =====
  {
    difficulty: 10, category: "math-logic", type: "text", time_limit: 45,
    text: "Le problème des chapeaux infini : un nombre dénombrable de mathématiciens, chacun avec un chapeau (noir ou blanc). Chacun voit TOUS les autres chapeaux sauf le sien. Simultanément, chacun devine sa couleur. Avec la bonne stratégie, combien se trompent au maximum ?",
    choices: ["Un nombre fini (grâce à l'axiome du choix)", "La moitié en moyenne", "Tous sauf un", "Impossible de limiter les erreurs"],
    correct_index: 0,
    explanation: "Grâce à l'axiome du choix ! On définit des classes d'équivalence de suites binaires (deux suites sont équivalentes si elles diffèrent en un nombre fini de positions). On choisit un représentant par classe. Chaque mathématicien voit tous les autres, déduit la classe, et devine selon le représentant. Résultat : au plus un nombre FINI de personnes se trompent.",
    svg_config: null,
  },
  {
    difficulty: 10, category: "paradox", type: "text", time_limit: 45,
    text: "Le theoreme de Banach-Tarski : on peut decomposer une boule en un nombre fini de morceaux et les reassembler en DEUX boules identiques a l'originale. Combien de morceaux minimum ?",
    choices: ["3", "4", "5", "Infini"],
    correct_index: 2,
    explanation: "Le theoreme prouve qu'on peut le faire avec 5 morceaux (dont un point). Ces morceaux ne sont pas mesurables au sens de Lebesgue — ils ne peuvent pas exister physiquement. Le theoreme utilise l'axiome du choix et le paradoxe de Hausdorff.",
    svg_config: null,
  },
  {
    difficulty: 10, category: "math-logic", type: "text", time_limit: 45,
    text: "Le probleme de l'arret (Halting Problem) : peut-on ecrire un programme qui determine si n'importe quel autre programme s'arrete ou boucle indefiniment ?",
    choices: ["Oui, avec assez de puissance de calcul", "Non, c'est indecidable", "Oui, pour la plupart des programmes", "Seulement pour les programmes deterministes"],
    correct_index: 1,
    explanation: "Turing a prouve en 1936 que c'est indecidable par diagonalisation. Si un tel programme H existait, on pourrait construire un programme paradoxal qui s'arrete ssi H dit qu'il ne s'arrete pas. Contradiction.",
    svg_config: null,
  },
  {
    difficulty: 10, category: "deduction", type: "text", time_limit: 45,
    text: "Le theoreme d'incompletude de Godel : tout systeme formel coherent et suffisamment puissant contient des enonces vrais mais :",
    choices: ["Prouvables", "Non prouvables", "Faux", "Indetermines"],
    correct_index: 1,
    explanation: "Le premier theoreme d'incompletude de Godel (1931) : tout systeme formel coherent contenant l'arithmetique contient des enonces vrais mais non prouvables DANS ce systeme. Il a construit une phrase 'G' disant 'cette phrase n'est pas prouvable'.",
    svg_config: null,
  },
  {
    difficulty: 10, category: "probability", type: "text", time_limit: 45,
    text: "Le probleme de Sleeping Beauty : elle est endormie. On lance une piece. Si pile, on la reveille lundi seulement. Si face, on la reveille lundi ET mardi (en lui effacant la memoire). A chaque reveil, quelle probabilite doit-elle assigner a 'pile' ?",
    choices: ["1/2 (halfer)", "1/3 (thirder)", "Les deux sont defensibles", "2/3"],
    correct_index: 2,
    explanation: "C'est un probleme ouvert en philosophie des probabilites ! Les 'halfers' disent 1/2 (la piece est equitable, rien n'a change). Les 'thirders' disent 1/3 (3 reveils equiprobables, 1 seul est pile). Pas de consensus apres 20+ ans de debat.",
    svg_config: null,
  },
  {
    difficulty: 10, category: "math-logic", type: "text", time_limit: 45,
    text: "Quelle est la cardinalite de l'ensemble des nombres reels entre 0 et 1 comparee a celle des reels entre 0 et l'infini ?",
    choices: ["Strictement inférieure", "Égale", "Strictement supérieure", "Incomparable"],
    correct_index: 1,
    explanation: "Elles sont égales ! On peut construire une bijection : f(x) = tan(π(x - 1/2)) envoie (0,1) sur (-∞,+∞). Les deux ensembles ont la même cardinalité (celle du continu, notée 𝔠 ou 2^ℵ₀). Un intervalle fini contient autant de réels que la droite entière !",
    svg_config: null,
  },
  {
    difficulty: 10, category: "paradox", type: "text", time_limit: 45,
    text: "Le paradoxe de Skolem : le theoreme de Lowenheim-Skolem dit que si une theorie des ensembles a un modele, elle en a un denombrable. Mais la theorie prouve l'existence d'ensembles non denombrables. Comment ?",
    choices: ["La theorie est contradictoire", "Non-denominabilite est relative au modele", "Le theoreme est faux", "Les ensembles non denombrables n'existent pas"],
    correct_index: 1,
    explanation: "La non-denominabilite est INTERNE au modele : l'ensemble est 'non denombrable' car aucune bijection avec N n'EXISTE dans le modele, meme si vu de l'exterieur le modele entier est denombrable. C'est la relativite du concept de cardinalite.",
    svg_config: null,
  },
  {
    difficulty: 10, category: "deduction", type: "text", time_limit: 45,
    text: "P = NP ? Parmi ces problemes, lequel est dans NP mais on ne sait pas s'il est dans P ?",
    choices: ["Le tri d'un tableau", "La factorisation d'entiers", "La multiplication de matrices", "La recherche dans un tableau"],
    correct_index: 1,
    explanation: "La factorisation d'entiers est dans NP (on peut verifier un facteur rapidement) mais on ne sait pas si c'est dans P (pas d'algorithme polynomial connu). C'est la base de la cryptographie RSA. Note : ce n'est pas NP-complet non plus !",
    svg_config: null,
  },
  {
    difficulty: 10, category: "math-logic", type: "text", time_limit: 45,
    text: "L'hypothese du continu (HC) : existe-t-il un cardinal strictement entre ℵ₀ (denombrable) et 2^ℵ₀ (continu) ?",
    choices: ["Oui", "Non", "C'est independant de ZFC", "Ca depend des axiomes"],
    correct_index: 2,
    explanation: "Godel (1940) a montre que HC est coherente avec ZFC. Cohen (1963) a montre que sa negation aussi. HC est donc INDEPENDANTE de ZFC : on ne peut ni la prouver ni la refuter avec les axiomes standards de la theorie des ensembles.",
    svg_config: null,
  },
  {
    difficulty: 10, category: "paradox", type: "text", time_limit: 45,
    text: "Le theoreme de Goodstein : toute suite de Goodstein finit par atteindre 0, mais ce theoreme ne peut PAS etre prouve dans l'arithmetique de Peano. Pourquoi est-ce remarquable ?",
    choices: ["C'est un contre-exemple a Godel", "C'est un enonce 'naturel' independant de PA", "Ca prouve que PA est incoherent", "C'est prouvable dans PA en fait"],
    correct_index: 1,
    explanation: "C'est le premier exemple 'naturel' d'un enonce mathematique vrai (prouvable dans ZFC via les ordinaux transfinis) mais independant de l'arithmetique de Peano. Godel avait montre que de tels enonces existaient, mais son exemple etait artificiel (auto-referentiel).",
    svg_config: null,
  },
];
