import type { Question } from "./types";

export const questionsMarques: Omit<Question, "id">[] = [
  // ===== DIFFICULTE 1 — ULTRA-CONNU (15s) =====
  {
    difficulty: 1, category: "slogan", type: "text", time_limit: 15,
    text: "À quelle marque appartient le slogan « Just Do It » ?",
    choices: ["Adidas", "Nike", "Puma", "Reebok"],
    correct_index: 1,
    explanation: "« Just Do It » est le slogan emblématique de Nike, lancé en 1988.",
    svg_config: null,
  },
  {
    difficulty: 1, category: "logo", type: "text", time_limit: 15,
    text: "Quelle marque a pour logo une pomme croquée ?",
    choices: ["Samsung", "Apple", "Microsoft", "Sony"],
    correct_index: 1,
    explanation: "La pomme croquée est le logo d'Apple depuis 1977.",
    svg_config: null,
  },
  {
    difficulty: 1, category: "logo", type: "text", time_limit: 15,
    text: "Quelle marque a pour logo un crocodile ?",
    choices: ["Le Coq Sportif", "Lacoste", "Fred Perry", "Ralph Lauren"],
    correct_index: 1,
    explanation: "Le crocodile vert est l'emblème de Lacoste, fondée par le tennisman René Lacoste.",
    svg_config: null,
  },
  {
    difficulty: 1, category: "logo", type: "text", time_limit: 15,
    text: "Quelle marque de chaussures a pour logo trois bandes ?",
    choices: ["Nike", "Adidas", "Puma", "New Balance"],
    correct_index: 1,
    explanation: "Les trois bandes sont la signature visuelle d'Adidas.",
    svg_config: null,
  },
  {
    difficulty: 1, category: "secteur", type: "text", time_limit: 15,
    text: "Dans quel secteur opère la marque Carrefour ?",
    choices: ["Grande distribution", "Automobile", "Banque", "Télécoms"],
    correct_index: 0,
    explanation: "Carrefour est l'une des principales enseignes françaises de grande distribution.",
    svg_config: null,
  },
  {
    difficulty: 1, category: "secteur", type: "text", time_limit: 15,
    text: "Dans quel secteur opère la marque Décathlon ?",
    choices: ["Bricolage", "Articles de sport", "Alimentation", "Mode de luxe"],
    correct_index: 1,
    explanation: "Décathlon est une enseigne française spécialisée dans les articles de sport.",
    svg_config: null,
  },
  {
    difficulty: 1, category: "slogan", type: "text", time_limit: 15,
    text: "À quelle marque appartient le slogan « Parce que je le vaux bien » ?",
    choices: ["Nivea", "L'Oréal", "Garnier", "Dove"],
    correct_index: 1,
    explanation: "« Parce que je le vaux bien » est le slogan culte de L'Oréal depuis 1973.",
    svg_config: null,
  },
  {
    difficulty: 1, category: "logo", type: "text", time_limit: 15,
    text: "Quelle marque a pour logo deux arches dorées en forme de M ?",
    choices: ["Burger King", "McDonald's", "Quick", "KFC"],
    correct_index: 1,
    explanation: "Les arches dorées en forme de M sont le logo mondialement connu de McDonald's.",
    svg_config: null,
  },
  {
    difficulty: 1, category: "secteur", type: "text", time_limit: 15,
    text: "Dans quel secteur opère la marque SNCF ?",
    choices: ["Aérien", "Ferroviaire", "Maritime", "Automobile"],
    correct_index: 1,
    explanation: "La SNCF est la principale entreprise ferroviaire française.",
    svg_config: null,
  },
  {
    difficulty: 1, category: "secteur", type: "text", time_limit: 15,
    text: "Dans quel secteur opère la marque Renault ?",
    choices: ["Automobile", "Électroménager", "Banque", "Aéronautique"],
    correct_index: 0,
    explanation: "Renault est un constructeur automobile français fondé en 1899.",
    svg_config: null,
  },

  // ===== DIFFICULTE 2 — TRES CONNU (15s) =====
  {
    difficulty: 2, category: "slogan", type: "text", time_limit: 15,
    text: "À quelle marque appartient le slogan « Venez comme vous êtes » ?",
    choices: ["Quick", "McDonald's", "KFC", "Burger King"],
    correct_index: 1,
    explanation: "« Venez comme vous êtes » est le slogan de McDonald's en France depuis 2004.",
    svg_config: null,
  },
  {
    difficulty: 2, category: "slogan", type: "text", time_limit: 15,
    text: "À quelle marque appartient le slogan « Carglass répare, Carglass remplace » ?",
    choices: ["Norauto", "Carglass", "Feu Vert", "Speedy"],
    correct_index: 1,
    explanation: "Ce jingle ultra-connu en France appartient à Carglass, spécialiste du vitrage automobile.",
    svg_config: null,
  },
  {
    difficulty: 2, category: "logo", type: "text", time_limit: 15,
    text: "Quelle marque a pour logo une virgule (swoosh) ?",
    choices: ["Puma", "Nike", "Asics", "Under Armour"],
    correct_index: 1,
    explanation: "Le « swoosh » en forme de virgule est le logo de Nike.",
    svg_config: null,
  },
  {
    difficulty: 2, category: "secteur", type: "text", time_limit: 15,
    text: "Dans quel secteur opère la marque Free ?",
    choices: ["Énergie", "Télécoms", "Assurance", "Banque"],
    correct_index: 1,
    explanation: "Free est un opérateur de télécommunications français du groupe Iliad.",
    svg_config: null,
  },
  {
    difficulty: 2, category: "logo", type: "text", time_limit: 15,
    text: "Quelle marque a pour logo une sirène verte sur fond blanc ?",
    choices: ["Costa Coffee", "Starbucks", "Caffè Nero", "Columbus Café"],
    correct_index: 1,
    explanation: "La sirène à deux queues est le logo de la chaîne de cafés Starbucks.",
    svg_config: null,
  },
  {
    difficulty: 2, category: "secteur", type: "text", time_limit: 15,
    text: "Dans quel secteur opère la marque Haribo ?",
    choices: ["Boissons", "Confiserie", "Biscuits salés", "Glaces"],
    correct_index: 1,
    explanation: "Haribo est un fabricant allemand de bonbons et confiseries.",
    svg_config: null,
  },
  {
    difficulty: 2, category: "slogan", type: "text", time_limit: 15,
    text: "À quelle marque appartient le slogan « Haribo c'est beau la vie, pour les grands et les petits » ?",
    choices: ["Lutti", "Haribo", "Carambar", "Krema"],
    correct_index: 1,
    explanation: "Ce jingle est la signature historique de Haribo en France.",
    svg_config: null,
  },
  {
    difficulty: 2, category: "logo", type: "text", time_limit: 15,
    text: "Quelle marque a pour logo un félin bondissant (puma) ?",
    choices: ["Puma", "Jaguar (vêtements)", "Le Coq Sportif", "Kappa"],
    correct_index: 0,
    explanation: "Le puma bondissant est le logo de la marque sportive allemande Puma.",
    svg_config: null,
  },
  {
    difficulty: 2, category: "secteur", type: "text", time_limit: 15,
    text: "Dans quel secteur opère la marque Leroy Merlin ?",
    choices: ["Sport", "Bricolage et jardinage", "Alimentation", "Habillement"],
    correct_index: 1,
    explanation: "Leroy Merlin est une enseigne française de bricolage, construction et jardinage.",
    svg_config: null,
  },
  {
    difficulty: 2, category: "logo", type: "text", time_limit: 15,
    text: "Quelle marque automobile a pour logo un losange ?",
    choices: ["Peugeot", "Renault", "Citroën", "Volvo"],
    correct_index: 1,
    explanation: "Le losange est le logo de Renault depuis les années 1920.",
    svg_config: null,
  },

  // ===== DIFFICULTE 3 — GRAND PUBLIC (15s) =====
  {
    difficulty: 3, category: "slogan", type: "text", time_limit: 15,
    text: "À quelle marque appartient le slogan « Et pour vous, ce sera quoi ? » ?",
    choices: ["MACIF", "MAAF", "MMA", "GMF"],
    correct_index: 1,
    explanation: "« Et pour vous, ce sera quoi ? » est le slogan de l'assureur MAAF.",
    svg_config: null,
  },
  {
    difficulty: 3, category: "logo", type: "text", time_limit: 15,
    text: "Quelle marque a pour logo un lion (vache souriante) rouge entourée de boîtes de fromage ?",
    choices: ["Kiri", "La Vache qui rit", "Babybel", "Caprice des Dieux"],
    correct_index: 1,
    explanation: "La vache rouge hilare aux boucles d'oreilles est l'emblème de La Vache qui rit (groupe Bel).",
    svg_config: null,
  },
  {
    difficulty: 3, category: "secteur", type: "text", time_limit: 15,
    text: "Dans quel secteur opère la marque MAAF ?",
    choices: ["Banque", "Assurance", "Télécoms", "Énergie"],
    correct_index: 1,
    explanation: "La MAAF est une société d'assurance mutuelle française.",
    svg_config: null,
  },
  {
    difficulty: 3, category: "logo", type: "text", time_limit: 15,
    text: "Quelle marque a pour logo un enfant noir souriant avec un fez rouge ?",
    choices: ["Ricoré", "Banania", "Nesquik", "Benco"],
    correct_index: 1,
    explanation: "Le tirailleur souriant est la mascotte historique de la marque de chocolat en poudre Banania.",
    svg_config: null,
  },
  {
    difficulty: 3, category: "slogan", type: "text", time_limit: 15,
    text: "À quelle marque appartient le slogan « Think Different » ?",
    choices: ["IBM", "Apple", "Microsoft", "Intel"],
    correct_index: 1,
    explanation: "« Think Different » est la campagne emblématique d'Apple lancée en 1997.",
    svg_config: null,
  },
  {
    difficulty: 3, category: "secteur", type: "text", time_limit: 15,
    text: "Dans quel secteur opère la marque Michelin ?",
    choices: ["Pneumatiques", "Carburants", "Pièces moteur", "Vitrage auto"],
    correct_index: 0,
    explanation: "Michelin est un fabricant français de pneumatiques, également connu pour son guide gastronomique.",
    svg_config: null,
  },
  {
    difficulty: 3, category: "logo", type: "text", time_limit: 15,
    text: "Quelle marque a pour mascotte un bonhomme blanc fait de pneus empilés ?",
    choices: ["Continental", "Michelin", "Goodyear", "Bridgestone"],
    correct_index: 1,
    explanation: "Le Bibendum, bonhomme en pneus, est la mascotte de Michelin depuis 1898.",
    svg_config: null,
  },
  {
    difficulty: 3, category: "slogan", type: "text", time_limit: 15,
    text: "Quel est le slogan de la marque L'Oréal ?",
    choices: ["Parce que je le vaux bien", "La beauté à l'état pur", "Vivez votre beauté", "Toute la beauté du monde"],
    correct_index: 0,
    explanation: "« Parce que je le vaux bien » est le slogan culte de L'Oréal.",
    svg_config: null,
  },
  {
    difficulty: 3, category: "secteur", type: "text", time_limit: 15,
    text: "Dans quel secteur opère la marque Danone ?",
    choices: ["Cosmétiques", "Produits laitiers et alimentaire", "Boissons alcoolisées", "Pharmacie"],
    correct_index: 1,
    explanation: "Danone est un groupe agroalimentaire français, leader des produits laitiers frais.",
    svg_config: null,
  },
  {
    difficulty: 3, category: "logo", type: "text", time_limit: 15,
    text: "Quelle marque a pour logo trois bonshommes en forme de « M » colorés (mascottes) ?",
    choices: ["Smarties", "M&M's", "Skittles", "Treets"],
    correct_index: 1,
    explanation: "Les personnages M&M's colorés, dont le rouge et le jaune, sont l'emblème de la marque.",
    svg_config: null,
  },

  // ===== DIFFICULTE 4 — CONNU (20s) =====
  {
    difficulty: 4, category: "slogan", type: "text", time_limit: 20,
    text: "À quelle marque appartient le slogan « I'm lovin' it » ?",
    choices: ["Burger King", "McDonald's", "Subway", "KFC"],
    correct_index: 1,
    explanation: "« I'm lovin' it » est le slogan international de McDonald's depuis 2003.",
    svg_config: null,
  },
  {
    difficulty: 4, category: "logo", type: "text", time_limit: 20,
    text: "Quelle marque a pour logo une coquille Saint-Jacques jaune et rouge ?",
    choices: ["BP", "Shell", "Total", "Esso"],
    correct_index: 1,
    explanation: "La coquille (shell en anglais) jaune et rouge est le logo du pétrolier Shell.",
    svg_config: null,
  },
  {
    difficulty: 4, category: "secteur", type: "text", time_limit: 20,
    text: "Dans quel secteur opère la marque Bouygues (Bouygues Telecom) ?",
    choices: ["Télécoms", "Assurance", "Distribution", "Pharmacie"],
    correct_index: 0,
    explanation: "Bouygues Telecom est l'un des grands opérateurs télécoms français (groupe Bouygues).",
    svg_config: null,
  },
  {
    difficulty: 4, category: "slogan", type: "text", time_limit: 20,
    text: "Quel est le slogan de la marque Red Bull ?",
    choices: ["Red Bull te réveille", "Red Bull donne des ailes", "L'énergie sans limite", "Red Bull, plus fort"],
    correct_index: 1,
    explanation: "« Red Bull donne des ailes » (« gives you wings ») est le slogan mondial de Red Bull.",
    svg_config: null,
  },
  {
    difficulty: 4, category: "logo", type: "text", time_limit: 20,
    text: "Quelle marque a pour logo un taureau rouge chargeant vers un cercle jaune ?",
    choices: ["Monster", "Red Bull", "Burn", "Dark Dog"],
    correct_index: 1,
    explanation: "Deux taureaux rouges face à un soleil jaune forment le logo de Red Bull.",
    svg_config: null,
  },
  {
    difficulty: 4, category: "secteur", type: "text", time_limit: 20,
    text: "Dans quel secteur opère la marque Sephora ?",
    choices: ["Parfumerie et cosmétiques", "Prêt-à-porter", "Bijouterie", "Optique"],
    correct_index: 0,
    explanation: "Sephora est une chaîne de parfumerie et cosmétiques du groupe LVMH.",
    svg_config: null,
  },
  {
    difficulty: 4, category: "slogan", type: "text", time_limit: 20,
    text: "À quelle marque appartient le slogan « Skip, et ça repart » ?",
    choices: ["Ariel", "Skip", "Le Chat", "Dash"],
    correct_index: 1,
    explanation: "« Skip, et ça repart » est la signature de la lessive Skip (Unilever).",
    svg_config: null,
  },
  {
    difficulty: 4, category: "logo", type: "text", time_limit: 20,
    text: "Quelle marque de cosmétiques de luxe a pour logo deux « C » entrelacés et dos à dos ?",
    choices: ["Dior", "Chanel", "Cartier", "Céline"],
    correct_index: 1,
    explanation: "Les deux « C » entrelacés représentent Coco Chanel, logo de la maison Chanel.",
    svg_config: null,
  },
  {
    difficulty: 4, category: "secteur", type: "text", time_limit: 20,
    text: "Dans quel secteur opère la marque Doliprane ?",
    choices: ["Cosmétiques", "Médicaments (pharmacie)", "Compléments sportifs", "Boissons"],
    correct_index: 1,
    explanation: "Doliprane est une marque de paracétamol, médicament antidouleur et antipyrétique.",
    svg_config: null,
  },
  {
    difficulty: 4, category: "slogan", type: "text", time_limit: 20,
    text: "Quel est le slogan historique de la SNCF des années 1980 « ... à nous de vous faire préférer le train » ?",
    choices: ["La SNCF, à nous de vous faire préférer le train", "SNCF, prenez le large", "SNCF, en avant", "SNCF, voyagez l'esprit libre"],
    correct_index: 0,
    explanation: "« À nous de vous faire préférer le train » est un slogan emblématique de la SNCF.",
    svg_config: null,
  },

  // ===== DIFFICULTE 5 — UN PEU PLUS PRECIS (20s) =====
  {
    difficulty: 5, category: "slogan", type: "text", time_limit: 20,
    text: "À quelle marque appartient le slogan « Because you're worth it » (version anglaise) ?",
    choices: ["Maybelline", "L'Oréal Paris", "Revlon", "Estée Lauder"],
    correct_index: 1,
    explanation: "« Because you're worth it » est la version anglaise du slogan de L'Oréal Paris.",
    svg_config: null,
  },
  {
    difficulty: 5, category: "logo", type: "text", time_limit: 20,
    text: "Quelle marque a pour logo une étoile à trois branches dans un cercle ?",
    choices: ["BMW", "Mercedes-Benz", "Audi", "Opel"],
    correct_index: 1,
    explanation: "L'étoile à trois branches est l'emblème de Mercedes-Benz.",
    svg_config: null,
  },
  {
    difficulty: 5, category: "secteur", type: "text", time_limit: 20,
    text: "Dans quel secteur opère la marque Tefal ?",
    choices: ["Articles culinaires et électroménager", "Cosmétiques", "Outillage", "Jouets"],
    correct_index: 0,
    explanation: "Tefal (groupe SEB) est spécialisée dans les poêles et le petit électroménager.",
    svg_config: null,
  },
  {
    difficulty: 5, category: "slogan", type: "text", time_limit: 20,
    text: "Quel est le slogan de la marque M6 (« ... la petite chaîne qui monte ») historique ?",
    choices: ["M6, toujours plus", "La petite chaîne qui monte", "M6, c'est vous", "M6, vivez la"],
    correct_index: 1,
    explanation: "« La petite chaîne qui monte » était la signature de M6 à ses débuts.",
    svg_config: null,
  },
  {
    difficulty: 5, category: "logo", type: "text", time_limit: 20,
    text: "Quelle marque automobile a pour logo quatre anneaux entrelacés ?",
    choices: ["Audi", "Volkswagen", "Toyota", "Mazda"],
    correct_index: 0,
    explanation: "Les quatre anneaux symbolisent la fusion de quatre constructeurs à l'origine d'Audi.",
    svg_config: null,
  },
  {
    difficulty: 5, category: "secteur", type: "text", time_limit: 20,
    text: "Dans quel secteur opère la marque Boulanger ?",
    choices: ["Boulangerie", "Électroménager et multimédia", "Habillement", "Meuble"],
    correct_index: 1,
    explanation: "Malgré son nom, Boulanger est une enseigne d'électroménager et de produits multimédias.",
    svg_config: null,
  },
  {
    difficulty: 5, category: "slogan", type: "text", time_limit: 20,
    text: "À quelle marque appartient le slogan « Vorsprung durch Technik » ?",
    choices: ["BMW", "Audi", "Volkswagen", "Mercedes-Benz"],
    correct_index: 1,
    explanation: "« Vorsprung durch Technik » (l'avance par la technique) est le slogan d'Audi.",
    svg_config: null,
  },
  {
    difficulty: 5, category: "logo", type: "text", time_limit: 20,
    text: "Quelle marque a pour logo un panda noir et blanc ?",
    choices: ["Greenpeace", "WWF", "National Geographic", "Pandacraft"],
    correct_index: 1,
    explanation: "Le panda est le logo du WWF (Fonds mondial pour la nature) depuis 1961.",
    svg_config: null,
  },
  {
    difficulty: 5, category: "secteur", type: "text", time_limit: 20,
    text: "Dans quel secteur opère la marque Yamaha ?",
    choices: ["Uniquement la moto", "Instruments de musique et motos", "Électroménager", "Téléphonie"],
    correct_index: 1,
    explanation: "Yamaha est connue à la fois pour ses instruments de musique et ses motos.",
    svg_config: null,
  },
  {
    difficulty: 5, category: "slogan", type: "text", time_limit: 20,
    text: "Quel est le slogan de la marque MAIF « ... assureur militant » ?",
    choices: ["MAIF, assureur militant", "MAIF, l'assurance solidaire", "MAIF, à vos côtés", "MAIF, tout simplement"],
    correct_index: 0,
    explanation: "« Assureur militant » est la signature de la mutuelle MAIF.",
    svg_config: null,
  },

  // ===== DIFFICULTE 6 — INFORME (20s) =====
  {
    difficulty: 6, category: "slogan", type: "text", time_limit: 20,
    text: "À quelle marque appartient le slogan « A diamond is forever » (« Un diamant est éternel ») ?",
    choices: ["Cartier", "De Beers", "Tiffany & Co.", "Swarovski"],
    correct_index: 1,
    explanation: "« A diamond is forever » est le slogan de De Beers, créé en 1947.",
    svg_config: null,
  },
  {
    difficulty: 6, category: "logo", type: "text", time_limit: 20,
    text: "Quelle marque a pour logo un « target » : un cercle rouge avec un point central (cible) ?",
    choices: ["Walmart", "Target", "Costco", "Kmart"],
    correct_index: 1,
    explanation: "La cible rouge est le logo de l'enseigne américaine Target.",
    svg_config: null,
  },
  {
    difficulty: 6, category: "secteur", type: "text", time_limit: 20,
    text: "Dans quel secteur opère la marque Bic ?",
    choices: ["Articles de bureau (stylos, briquets, rasoirs)", "Cosmétiques", "Jouets", "Alimentation"],
    correct_index: 0,
    explanation: "Bic est connue pour ses stylos, briquets et rasoirs jetables.",
    svg_config: null,
  },
  {
    difficulty: 6, category: "slogan", type: "text", time_limit: 20,
    text: "Quel est le slogan de la marque Nespresso ?",
    choices: ["Le café autrement", "What else ?", "Un café d'exception", "Vivez l'instant"],
    correct_index: 1,
    explanation: "« What else ? » est le slogan de Nespresso, popularisé par George Clooney.",
    svg_config: null,
  },
  {
    difficulty: 6, category: "logo", type: "text", time_limit: 20,
    text: "Quelle marque a pour logo un écureuil (ou cacahuète anthropomorphe avec monocle) ?",
    choices: ["Benenuts", "Mr. Peanut (Planters)", "Lay's", "Vico"],
    correct_index: 1,
    explanation: "Mr. Peanut, cacahuète avec monocle et haut-de-forme, est la mascotte de Planters.",
    svg_config: null,
  },
  {
    difficulty: 6, category: "secteur", type: "text", time_limit: 20,
    text: "Dans quel secteur opère la marque Salomon ?",
    choices: ["Articles de montagne et trail", "Cosmétiques", "Bricolage", "Boissons"],
    correct_index: 0,
    explanation: "Salomon est spécialisée dans les équipements de ski, randonnée et trail running.",
    svg_config: null,
  },
  {
    difficulty: 6, category: "slogan", type: "text", time_limit: 20,
    text: "À quelle marque appartient le slogan « Impossible is nothing » ?",
    choices: ["Nike", "Adidas", "Reebok", "Under Armour"],
    correct_index: 1,
    explanation: "« Impossible is nothing » est un slogan emblématique d'Adidas.",
    svg_config: null,
  },
  {
    difficulty: 6, category: "logo", type: "text", time_limit: 20,
    text: "Quelle marque a pour logo un coquillage stylisé bleu et une signature de gym ?",
    choices: ["Basic-Fit", "Fitness Park", "Neoness", "Keep Cool"],
    correct_index: 0,
    explanation: "Basic-Fit, leader européen des salles de sport low-cost, utilise un logo orange et bleu.",
    svg_config: null,
  },
  {
    difficulty: 6, category: "secteur", type: "text", time_limit: 20,
    text: "Dans quel secteur opère la marque Saint-Gobain ?",
    choices: ["Matériaux de construction", "Agroalimentaire", "Textile", "Télécoms"],
    correct_index: 0,
    explanation: "Saint-Gobain est un groupe français de matériaux (verre, isolation, construction).",
    svg_config: null,
  },
  {
    difficulty: 6, category: "slogan", type: "text", time_limit: 20,
    text: "Quel est le slogan de la marque Gillette ?",
    choices: ["La perfection au masculin", "The best a man can get", "Pour les vrais hommes", "Rasez de près"],
    correct_index: 1,
    explanation: "« The best a man can get » (« La perfection au masculin » en français) est le slogan de Gillette.",
    svg_config: null,
  },

  // ===== DIFFICULTE 7 — POINTU (25s) =====
  {
    difficulty: 7, category: "slogan", type: "text", time_limit: 25,
    text: "À quelle marque appartient le slogan « Connecting People » ?",
    choices: ["Ericsson", "Nokia", "Motorola", "Sony Ericsson"],
    correct_index: 1,
    explanation: "« Connecting People » est le slogan historique de Nokia.",
    svg_config: null,
  },
  {
    difficulty: 7, category: "slogan", type: "text", time_limit: 25,
    text: "À quelle marque de café appartient le slogan « Un café nommé désir » ?",
    choices: ["Carte Noire", "Grand-Mère", "Maison du Café", "Jacques Vabre"],
    correct_index: 0,
    explanation: "« Un café nommé désir » est la signature de Carte Noire.",
    svg_config: null,
  },
  {
    difficulty: 7, category: "logo", type: "text", time_limit: 25,
    text: "Quelle marque automobile a pour logo un lion debout (rampant) ?",
    choices: ["Peugeot", "Holden", "Citroën", "Saab"],
    correct_index: 0,
    explanation: "Le lion est l'emblème de Peugeot depuis 1858.",
    svg_config: null,
  },
  {
    difficulty: 7, category: "secteur", type: "text", time_limit: 25,
    text: "Dans quel secteur opère la marque Legrand ?",
    choices: ["Appareillage électrique", "Mobilier", "Outillage à main", "Plomberie"],
    correct_index: 0,
    explanation: "Legrand est un fabricant français d'appareillage électrique et d'infrastructures numériques.",
    svg_config: null,
  },
  {
    difficulty: 7, category: "slogan", type: "text", time_limit: 25,
    text: "Quel est le slogan de la marque Décathlon ?",
    choices: ["À fond la forme", "Le sport pour tous", "Bougez avec nous", "Décathlon, le plein d'énergie"],
    correct_index: 0,
    explanation: "« À fond la forme » est le slogan historique de Décathlon.",
    svg_config: null,
  },
  {
    difficulty: 7, category: "logo", type: "text", time_limit: 25,
    text: "Quelle marque a pour logo un alligator/dragon « Lacoste » — non, plutôt un bouquetin pour cette marque outdoor ?",
    choices: ["The North Face", "Quechua (Décathlon)", "Millet", "Eider"],
    correct_index: 2,
    explanation: "Le bouquetin est le symbole de la marque française de montagne Millet.",
    svg_config: null,
  },
  {
    difficulty: 7, category: "secteur", type: "text", time_limit: 25,
    text: "Dans quel secteur opère la marque Seb (groupe SEB) à l'origine ?",
    choices: ["Petit électroménager", "Téléphonie", "Cosmétiques", "Vêtements"],
    correct_index: 0,
    explanation: "SEB (Société d'Emboutissage de Bourgogne) est spécialisée dans le petit électroménager (Cocotte-Minute, friteuses...).",
    svg_config: null,
  },
  {
    difficulty: 7, category: "slogan", type: "text", time_limit: 25,
    text: "À quelle marque appartient le slogan « Think small » (campagne mythique des années 1960) ?",
    choices: ["Mini", "Volkswagen", "Fiat", "Renault"],
    correct_index: 1,
    explanation: "« Think small » est la célèbre campagne de Volkswagen pour la Coccinelle aux États-Unis.",
    svg_config: null,
  },
  {
    difficulty: 7, category: "logo", type: "text", time_limit: 25,
    text: "Quelle marque de bière a pour logo une étoile rouge à cinq branches ?",
    choices: ["Kronenbourg", "Heineken", "San Miguel", "Carlsberg"],
    correct_index: 1,
    explanation: "L'étoile rouge fait partie de l'identité de la bière Heineken (avec le e penché).",
    svg_config: null,
  },
  {
    difficulty: 7, category: "secteur", type: "text", time_limit: 25,
    text: "Dans quel secteur opère la marque Somfy ?",
    choices: ["Motorisation (volets, portails)", "Téléphonie", "Cosmétiques", "Alimentation"],
    correct_index: 0,
    explanation: "Somfy est leader mondial de la motorisation des ouvertures et fermetures de l'habitat.",
    svg_config: null,
  },

  // ===== DIFFICULTE 8 — TRES POINTU (25s) =====
  {
    difficulty: 8, category: "slogan", type: "text", time_limit: 25,
    text: "À quelle marque appartient le slogan « Have a break, have a KitKat » ?",
    choices: ["Twix", "KitKat", "Lion", "Snickers"],
    correct_index: 1,
    explanation: "« Have a break, have a KitKat » est le slogan historique de KitKat (Nestlé).",
    svg_config: null,
  },
  {
    difficulty: 8, category: "logo", type: "text", time_limit: 25,
    text: "Quelle marque a pour logo un chevron double (deux chevrons inversés) ?",
    choices: ["Citroën", "Peugeot", "DS Automobiles", "Renault"],
    correct_index: 0,
    explanation: "Les deux chevrons de Citroën évoquent les engrenages à chevrons inventés par André Citroën.",
    svg_config: null,
  },
  {
    difficulty: 8, category: "secteur", type: "text", time_limit: 25,
    text: "Dans quel secteur opère la marque Schneider Electric ?",
    choices: ["Gestion de l'énergie et automatismes", "Électroménager grand public", "Téléphonie", "Banque"],
    correct_index: 0,
    explanation: "Schneider Electric est spécialisée dans la gestion de l'énergie et l'automatisation industrielle.",
    svg_config: null,
  },
  {
    difficulty: 8, category: "slogan", type: "text", time_limit: 25,
    text: "Quel est le slogan international de la marque De Beers ?",
    choices: ["Forever yours", "A diamond is forever", "The shine of love", "Eternal beauty"],
    correct_index: 1,
    explanation: "« A diamond is forever » a été élu slogan du XXe siècle par Advertising Age.",
    svg_config: null,
  },
  {
    difficulty: 8, category: "logo", type: "text", time_limit: 25,
    text: "Quelle marque de luxe a pour logo une tête de Méduse ?",
    choices: ["Gucci", "Versace", "Fendi", "Prada"],
    correct_index: 1,
    explanation: "La tête de Méduse est l'emblème de la maison italienne Versace.",
    svg_config: null,
  },
  {
    difficulty: 8, category: "secteur", type: "text", time_limit: 25,
    text: "Dans quel secteur opère la marque Air Liquide ?",
    choices: ["Gaz industriels et médicaux", "Eaux minérales", "Climatisation domestique", "Boissons gazeuses"],
    correct_index: 0,
    explanation: "Air Liquide est un leader mondial des gaz industriels et médicaux.",
    svg_config: null,
  },
  {
    difficulty: 8, category: "slogan", type: "text", time_limit: 25,
    text: "À quelle marque appartient le slogan « Maybe she's born with it. Maybe it's Maybelline » ?",
    choices: ["Rimmel", "Maybelline", "Bourjois", "Gemey"],
    correct_index: 1,
    explanation: "« Maybe it's Maybelline » est le slogan de la marque de cosmétiques Maybelline.",
    svg_config: null,
  },
  {
    difficulty: 8, category: "logo", type: "text", time_limit: 25,
    text: "Quelle marque a pour logo un « bibendum » — non, plutôt un soleil souriant (mascotte) pour cette marque de margarine ?",
    choices: ["Fruit d'Or", "Planta Fin", "St Hubert", "Astra"],
    correct_index: 0,
    explanation: "Fruit d'Or utilise un soleil dans son identité, associée au tournesol et à l'huile végétale.",
    svg_config: null,
  },
  {
    difficulty: 8, category: "secteur", type: "text", time_limit: 25,
    text: "Dans quel secteur opère la marque Bel (groupe Bel) ?",
    choices: ["Fromages de marque", "Charcuterie", "Boissons", "Surgelés"],
    correct_index: 0,
    explanation: "Le groupe Bel produit La Vache qui rit, Babybel, Kiri et Boursin.",
    svg_config: null,
  },
  {
    difficulty: 8, category: "slogan", type: "text", time_limit: 25,
    text: "Quel est le slogan de la marque EDF des campagnes « ... changer l'énergie ensemble » ?",
    choices: ["EDF, l'énergie est notre avenir", "Changer l'énergie ensemble", "EDF, pour vous", "L'énergie en commun"],
    correct_index: 1,
    explanation: "« Changer l'énergie ensemble » est une signature de campagne d'EDF.",
    svg_config: null,
  },

  // ===== DIFFICULTE 9 — EXPERT (30s) =====
  {
    difficulty: 9, category: "slogan", type: "text", time_limit: 30,
    text: "À quelle marque appartient le slogan « The Ultimate Driving Machine » ?",
    choices: ["Mercedes-Benz", "BMW", "Audi", "Lexus"],
    correct_index: 1,
    explanation: "« The Ultimate Driving Machine » (« Le plaisir de conduire ») est le slogan de BMW.",
    svg_config: null,
  },
  {
    difficulty: 9, category: "slogan", type: "text", time_limit: 30,
    text: "Quel est le slogan publicitaire historique d'Avis, célèbre pour avoir assumé sa 2e place ?",
    choices: ["We're number one", "We try harder", "Drive easy", "The smart choice"],
    correct_index: 1,
    explanation: "« We try harder » est la campagne d'Avis, location de voitures, assumant être numéro deux derrière Hertz.",
    svg_config: null,
  },
  {
    difficulty: 9, category: "logo", type: "text", time_limit: 30,
    text: "Quelle marque a pour logo un cheval cabré noir sur fond jaune ?",
    choices: ["Lamborghini", "Ferrari", "Porsche", "Ford Mustang"],
    correct_index: 1,
    explanation: "Le « Cavallino Rampante », cheval cabré noir sur fond jaune, est l'emblème de Ferrari.",
    svg_config: null,
  },
  {
    difficulty: 9, category: "secteur", type: "text", time_limit: 30,
    text: "Dans quel secteur opère la marque Bureau Veritas ?",
    choices: ["Inspection, certification et essais", "Mobilier de bureau", "Édition", "Logistique"],
    correct_index: 0,
    explanation: "Bureau Veritas est un leader mondial des services d'inspection, certification et essais en laboratoire.",
    svg_config: null,
  },
  {
    difficulty: 9, category: "slogan", type: "text", time_limit: 30,
    text: "À quelle marque appartient le slogan « Quand c'est trop, c'est Tropico » ?",
    choices: ["Oasis", "Tropico", "Pulco", "Banga"],
    correct_index: 1,
    explanation: "« Quand c'est trop, c'est Tropico » est le jingle de la boisson Tropico.",
    svg_config: null,
  },
  {
    difficulty: 9, category: "logo", type: "text", time_limit: 30,
    text: "Quelle marque de matériel hi-fi/audio a pour logo une note de musique stylisée ou « b » (cette marque casque) ?",
    choices: ["Bose", "Beats by Dre", "Sennheiser", "JBL"],
    correct_index: 1,
    explanation: "Le « b » minuscule dans un cercle rouge est le logo de Beats by Dre.",
    svg_config: null,
  },
  {
    difficulty: 9, category: "secteur", type: "text", time_limit: 30,
    text: "Dans quel secteur opère la marque Dassault Systèmes (distincte de Dassault Aviation) ?",
    choices: ["Logiciels de conception 3D", "Aviation militaire", "Presse", "Vins"],
    correct_index: 0,
    explanation: "Dassault Systèmes édite des logiciels de CAO/PLM comme CATIA et SOLIDWORKS.",
    svg_config: null,
  },
  {
    difficulty: 9, category: "slogan", type: "text", time_limit: 30,
    text: "Quel est le slogan publicitaire iconique de M&M's en France « Le chocolat qui fond... » ?",
    choices: ["Le chocolat qui fond dans la bouche, pas dans la main", "Le chocolat des champions", "Fondez de plaisir", "Croquez la vie"],
    correct_index: 0,
    explanation: "« Le chocolat qui fond dans la bouche, pas dans la main » est le slogan historique de M&M's.",
    svg_config: null,
  },
  {
    difficulty: 9, category: "logo", type: "text", time_limit: 30,
    text: "Quelle marque a pour logo un « tigre » roux (mascotte de céréales) ?",
    choices: ["Chocapic (loup)", "Frosties / Frosted Flakes (Tony le Tigre)", "Coco Pops (singe)", "Trésor (ours)"],
    correct_index: 1,
    explanation: "Tony le Tigre est la mascotte des céréales Frosties (Frosted Flakes de Kellogg's).",
    svg_config: null,
  },
  {
    difficulty: 9, category: "secteur", type: "text", time_limit: 30,
    text: "Dans quel secteur opère la marque Vinci ?",
    choices: ["Construction et concessions (autoroutes)", "Mode", "Banque", "Cosmétiques"],
    correct_index: 0,
    explanation: "Vinci est un groupe français de BTP et de concessions (autoroutes, aéroports).",
    svg_config: null,
  },

  // ===== DIFFICULTE 10 — TRES EXPERT (30s) =====
  {
    difficulty: 10, category: "slogan", type: "text", time_limit: 30,
    text: "À quelle marque appartient le slogan « Melts in your mouth, not in your hand » à l'origine ?",
    choices: ["Smarties", "M&M's", "Skittles", "Reese's"],
    correct_index: 1,
    explanation: "« Melts in your mouth, not in your hand » est le slogan original de M&M's (1954).",
    svg_config: null,
  },
  {
    difficulty: 10, category: "slogan", type: "text", time_limit: 30,
    text: "À quelle marque appartient le slogan « Where's the beef? », célèbre campagne américaine des années 1980 ?",
    choices: ["McDonald's", "Wendy's", "Burger King", "Hardee's"],
    correct_index: 1,
    explanation: "« Where's the beef? » est la campagne culte de la chaîne Wendy's en 1984.",
    svg_config: null,
  },
  {
    difficulty: 10, category: "logo", type: "text", time_limit: 30,
    text: "Quelle marque de stylos de luxe a pour logo une étoile blanche à six pointes (l'« étoile des neiges ») ?",
    choices: ["Parker", "Montblanc", "Waterman", "Cross"],
    correct_index: 1,
    explanation: "L'emblème blanc de Montblanc évoque la cime enneigée du mont Blanc vue d'en haut.",
    svg_config: null,
  },
  {
    difficulty: 10, category: "secteur", type: "text", time_limit: 30,
    text: "Dans quel secteur opère la marque Edenred (issue d'Accor) ?",
    choices: ["Titres-services (tickets restaurant)", "Hôtellerie", "Restauration rapide", "Assurance"],
    correct_index: 0,
    explanation: "Edenred, spin-off d'Accor en 2010, est leader des titres de paiement spécialisés comme Ticket Restaurant.",
    svg_config: null,
  },
  {
    difficulty: 10, category: "slogan", type: "text", time_limit: 30,
    text: "À quelle marque appartient le slogan publicitaire « Reach out and touch someone » ?",
    choices: ["Verizon", "AT&T", "Vodafone", "Orange"],
    correct_index: 1,
    explanation: "« Reach out and touch someone » est une campagne historique de l'opérateur américain AT&T.",
    svg_config: null,
  },
  {
    difficulty: 10, category: "logo", type: "text", time_limit: 30,
    text: "Quelle marque de luxe italienne a pour logo deux « F » inversés et adossés ?",
    choices: ["Ferragamo", "Fendi", "Furla", "Fila"],
    correct_index: 1,
    explanation: "Le double « F » (« FF » de Fun Furs) dessiné par Karl Lagerfeld est l'emblème de Fendi.",
    svg_config: null,
  },
  {
    difficulty: 10, category: "secteur", type: "text", time_limit: 30,
    text: "Dans quel secteur opère la marque ArcelorMittal ?",
    choices: ["Sidérurgie (acier)", "Aluminium uniquement", "Pétrochimie", "Ciment"],
    correct_index: 0,
    explanation: "ArcelorMittal est le premier sidérurgiste mondial (production d'acier).",
    svg_config: null,
  },
  {
    difficulty: 10, category: "slogan", type: "text", time_limit: 30,
    text: "À quelle marque appartient le slogan « Finger lickin' good » ?",
    choices: ["McDonald's", "KFC", "Popeyes", "Quick"],
    correct_index: 1,
    explanation: "« Finger lickin' good » (« C'est bon jusqu'au bout des doigts ») est le slogan historique de KFC.",
    svg_config: null,
  },
  {
    difficulty: 10, category: "pub", type: "text", time_limit: 30,
    text: "Quelle marque de pneus a pour campagne historique des publicités notées par le « Bibendum » et un guide gastronomique étoilé ?",
    choices: ["Goodyear", "Michelin", "Pirelli", "Dunlop"],
    correct_index: 1,
    explanation: "Michelin, outre le Bibendum, édite le célèbre Guide Michelin attribuant les étoiles aux restaurants.",
    svg_config: null,
  },
  {
    difficulty: 10, category: "logo", type: "text", time_limit: 30,
    text: "Quelle marque de spiritueux a pour logo une cloche/un blason avec un cerf, marque de whisky écossais ?",
    choices: ["Jack Daniel's", "The Glenlivet", "Glenfiddich (cerf)", "Chivas"],
    correct_index: 2,
    explanation: "Le cerf (« stag ») est l'emblème du whisky single malt Glenfiddich (« vallée du cerf » en gaélique).",
    svg_config: null,
  },
];
