import type { Question } from "./types";

export const questionsInsolite: Omit<Question, "id">[] = [
  // ===== Difficulté 1 (très connu) — time_limit 15 =====
  {
    difficulty: 1, category: "insolite", type: "text", time_limit: 15,
    text: "Quel aliment naturel peut se conserver des milliers d'années sans jamais se périmer ?",
    choices: ["Le riz", "Le miel", "Le sel", "Le sucre"],
    correct_index: 1,
    explanation: "Grâce à sa très faible teneur en eau et à son acidité, le miel ne se gâte pas. On a retrouvé du miel encore comestible dans des tombes égyptiennes vieilles de plus de 3000 ans.",
    svg_config: null,
  },
  {
    difficulty: 1, category: "nature-insolite", type: "text", time_limit: 15,
    text: "Quel animal terrestre est le plus grand du monde ?",
    choices: ["L'hippopotame", "Le rhinocéros", "L'éléphant d'Afrique", "La girafe"],
    correct_index: 2,
    explanation: "L'éléphant de savane d'Afrique est le plus grand et le plus lourd des animaux terrestres, pouvant peser jusqu'à 6 tonnes.",
    svg_config: null,
  },
  {
    difficulty: 1, category: "geo-insolite", type: "text", time_limit: 15,
    text: "Quel est le plus petit État du monde par sa superficie ?",
    choices: ["Monaco", "Le Vatican", "Saint-Marin", "Nauru"],
    correct_index: 1,
    explanation: "Avec seulement 0,44 km², le Vatican est de loin le plus petit État souverain du monde, plus petit qu'un grand parc urbain.",
    svg_config: null,
  },
  {
    difficulty: 1, category: "nature-insolite", type: "text", time_limit: 15,
    text: "Quel animal a un cœur qui peut peser plus de 600 kg ?",
    choices: ["L'éléphant", "La baleine bleue", "Le cachalot", "Le requin-baleine"],
    correct_index: 1,
    explanation: "La baleine bleue est le plus grand animal ayant jamais existé : son cœur peut peser autant qu'une petite voiture.",
    svg_config: null,
  },
  {
    difficulty: 1, category: "insolite", type: "text", time_limit: 15,
    text: "Combien d'os possède le corps humain adulte ?",
    choices: ["106", "206", "306", "406"],
    correct_index: 1,
    explanation: "L'adulte compte 206 os. Le bébé en a environ 300, mais beaucoup fusionnent au cours de la croissance.",
    svg_config: null,
  },
  {
    difficulty: 1, category: "geo-insolite", type: "text", time_limit: 15,
    text: "Quel est le plus long fleuve du monde par sa longueur ?",
    choices: ["L'Amazone", "Le Nil", "Le Mississippi", "Le Yangtsé"],
    correct_index: 1,
    explanation: "Le Nil, avec environ 6650 km, est traditionnellement considéré comme le plus long fleuve du monde, devant l'Amazone.",
    svg_config: null,
  },
  {
    difficulty: 1, category: "nature-insolite", type: "text", time_limit: 15,
    text: "Quel animal ne peut pas sauter ?",
    choices: ["Le kangourou", "L'éléphant", "La grenouille", "Le lapin"],
    correct_index: 1,
    explanation: "À cause de son poids et de la structure de ses pattes, l'éléphant est le seul mammifère incapable de sauter : il garde toujours au moins une patte au sol.",
    svg_config: null,
  },
  {
    difficulty: 1, category: "record", type: "text", time_limit: 15,
    text: "Quelle planète du système solaire est la plus grande ?",
    choices: ["Saturne", "Jupiter", "Neptune", "La Terre"],
    correct_index: 1,
    explanation: "Jupiter est si grande qu'elle pourrait contenir plus de 1300 fois la Terre dans son volume.",
    svg_config: null,
  },
  {
    difficulty: 1, category: "anecdote", type: "text", time_limit: 15,
    text: "De quelle couleur est le sang d'une pieuvre ?",
    choices: ["Rouge", "Bleu", "Vert", "Transparent"],
    correct_index: 1,
    explanation: "Le sang de la pieuvre est bleu car il utilise l'hémocyanine à base de cuivre, et non l'hémoglobine à base de fer comme nous.",
    svg_config: null,
  },
  {
    difficulty: 1, category: "nature-insolite", type: "text", time_limit: 15,
    text: "Quel oiseau est le plus rapide du monde en piqué ?",
    choices: ["L'aigle royal", "Le faucon pèlerin", "L'autruche", "Le martinet"],
    correct_index: 1,
    explanation: "En piqué, le faucon pèlerin dépasse les 350 km/h, ce qui en fait l'animal le plus rapide de la planète.",
    svg_config: null,
  },

  // ===== Difficulté 2 — time_limit 15 =====
  {
    difficulty: 2, category: "nature-insolite", type: "text", time_limit: 15,
    text: "Combien de cœurs possède une pieuvre ?",
    choices: ["1", "2", "3", "5"],
    correct_index: 2,
    explanation: "La pieuvre a trois cœurs : deux pompent le sang vers les branchies, le troisième vers le reste du corps.",
    svg_config: null,
  },
  {
    difficulty: 2, category: "geo-insolite", type: "text", time_limit: 15,
    text: "Quel pays est traversé par le plus grand nombre de fuseaux horaires ?",
    choices: ["La Russie", "La France", "Les États-Unis", "La Chine"],
    correct_index: 1,
    explanation: "En comptant ses territoires d'outre-mer répartis sur tous les océans, la France couvre 12 fuseaux horaires, le record mondial.",
    svg_config: null,
  },
  {
    difficulty: 2, category: "anecdote", type: "text", time_limit: 15,
    text: "Quel organe du corps humain ne ressent pas la douleur ?",
    choices: ["Le foie", "Le cerveau", "L'estomac", "La peau"],
    correct_index: 1,
    explanation: "Le cerveau lui-même n'a pas de récepteurs de la douleur : c'est pourquoi certaines opérations cérébrales se font sur patient éveillé.",
    svg_config: null,
  },
  {
    difficulty: 2, category: "nature-insolite", type: "text", time_limit: 15,
    text: "Quel animal dort debout et peut dormir les yeux ouverts ?",
    choices: ["Le chat", "Le cheval", "Le chien", "Le lapin"],
    correct_index: 1,
    explanation: "Grâce à un système de blocage de ses articulations, le cheval peut dormir debout pour fuir rapidement un prédateur.",
    svg_config: null,
  },
  {
    difficulty: 2, category: "insolite", type: "text", time_limit: 15,
    text: "Quelle partie du corps humain continue de grandir toute la vie ?",
    choices: ["Les oreilles et le nez", "Les mains", "Les pieds", "Les yeux"],
    correct_index: 0,
    explanation: "Faits de cartilage, le nez et les oreilles s'allongent et s'affaissent légèrement avec l'âge, contrairement aux os.",
    svg_config: null,
  },
  {
    difficulty: 2, category: "geo-insolite", type: "text", time_limit: 15,
    text: "Quel océan est le plus grand du monde ?",
    choices: ["L'océan Atlantique", "L'océan Pacifique", "L'océan Indien", "L'océan Arctique"],
    correct_index: 1,
    explanation: "L'océan Pacifique couvre à lui seul environ un tiers de la surface du globe, plus que toutes les terres émergées réunies.",
    svg_config: null,
  },
  {
    difficulty: 2, category: "anecdote", type: "text", time_limit: 15,
    text: "Quel est le muscle le plus puissant du corps humain par rapport à sa taille ?",
    choices: ["Le biceps", "Le masséter (mâchoire)", "Le cœur", "Le mollet"],
    correct_index: 1,
    explanation: "Le masséter, qui ferme la mâchoire, peut exercer une force de plusieurs dizaines de kilos sur les molaires.",
    svg_config: null,
  },
  {
    difficulty: 2, category: "nature-insolite", type: "text", time_limit: 15,
    text: "Combien de temps peut vivre une fourmi reine de certaines espèces ?",
    choices: ["1 an", "5 ans", "Plus de 15 ans", "50 ans"],
    correct_index: 2,
    explanation: "Certaines reines fourmis vivent plus de 15 ans, voire jusqu'à près de 30 ans, une longévité record chez les insectes.",
    svg_config: null,
  },
  {
    difficulty: 2, category: "record", type: "text", time_limit: 15,
    text: "Quel est le métal liquide à température ambiante ?",
    choices: ["Le plomb", "Le mercure", "L'étain", "Le zinc"],
    correct_index: 1,
    explanation: "Le mercure est le seul métal liquide à température ambiante, ce qui lui a longtemps valu d'équiper les thermomètres.",
    svg_config: null,
  },
  {
    difficulty: 2, category: "histoire-insolite", type: "text", time_limit: 15,
    text: "Quel animal a été envoyé dans l'espace en premier par l'URSS en 1957 ?",
    choices: ["Un singe", "Une chienne nommée Laïka", "Un chat", "Une souris"],
    correct_index: 1,
    explanation: "La chienne Laïka, à bord de Spoutnik 2, fut le premier être vivant mis en orbite autour de la Terre.",
    svg_config: null,
  },

  // ===== Difficulté 3 — time_limit 15 =====
  {
    difficulty: 3, category: "nature-insolite", type: "text", time_limit: 15,
    text: "Quel animal possède l'œil le plus grand du règne animal ?",
    choices: ["La baleine bleue", "Le calmar géant", "L'autruche", "Le cachalot"],
    correct_index: 1,
    explanation: "L'œil du calmar géant peut atteindre 27 cm de diamètre, soit la taille d'une assiette, pour voir dans les abysses.",
    svg_config: null,
  },
  {
    difficulty: 3, category: "geo-insolite", type: "text", time_limit: 15,
    text: "Quel désert est le plus grand du monde ?",
    choices: ["Le Sahara", "Le désert d'Antarctique", "Le désert de Gobi", "Le désert d'Arabie"],
    correct_index: 1,
    explanation: "Un désert se définit par ses très faibles précipitations : l'Antarctique, désert glacé, est le plus vaste du monde, devant le Sahara.",
    svg_config: null,
  },
  {
    difficulty: 3, category: "anecdote", type: "text", time_limit: 15,
    text: "Combien de fois bat le cœur humain en moyenne sur une journée ?",
    choices: ["Environ 10 000 fois", "Environ 100 000 fois", "Environ 1 million de fois", "Environ 10 millions de fois"],
    correct_index: 1,
    explanation: "À environ 70 battements par minute, le cœur bat près de 100 000 fois par jour, soit plus de 2,5 milliards de fois dans une vie.",
    svg_config: null,
  },
  {
    difficulty: 3, category: "insolite", type: "text", time_limit: 15,
    text: "Quelle est la seule lettre qui n'apparaît dans aucun nom d'État américain ?",
    choices: ["La lettre Q", "La lettre Z", "La lettre X", "La lettre J"],
    correct_index: 0,
    explanation: "La lettre Q est la seule à n'apparaître dans le nom d'aucun des 50 États américains.",
    svg_config: null,
  },
  {
    difficulty: 3, category: "nature-insolite", type: "text", time_limit: 15,
    text: "Quel animal est capable de régénérer une patte, un œil ou même une partie de son cerveau ?",
    choices: ["Le lézard", "L'axolotl", "La grenouille", "Le crabe"],
    correct_index: 1,
    explanation: "L'axolotl, une salamandre du Mexique, peut régénérer ses membres, sa moelle épinière et même des portions de son cœur et de son cerveau.",
    svg_config: null,
  },
  {
    difficulty: 3, category: "record", type: "text", time_limit: 15,
    text: "Quelle est la planète la plus chaude du système solaire ?",
    choices: ["Mercure", "Vénus", "Mars", "Jupiter"],
    correct_index: 1,
    explanation: "Bien que Mercure soit plus proche du Soleil, l'épais effet de serre de Vénus en fait la planète la plus chaude, avec environ 460 °C en surface.",
    svg_config: null,
  },
  {
    difficulty: 3, category: "histoire-insolite", type: "text", time_limit: 15,
    text: "Quelle guerre est considérée comme la plus courte de l'Histoire, ayant duré moins d'une heure ?",
    choices: ["La guerre anglo-zanzibarite de 1896", "La guerre des Six Jours", "La guerre du Football", "La guerre de Crimée"],
    correct_index: 0,
    explanation: "La guerre anglo-zanzibarite de 1896 a duré environ 38 minutes, ce qui en fait la plus courte guerre documentée.",
    svg_config: null,
  },
  {
    difficulty: 3, category: "nature-insolite", type: "text", time_limit: 15,
    text: "Quel animal a une langue plus longue que son propre corps ?",
    choices: ["Le caméléon", "Le fourmilier", "Le serpent", "La girafe"],
    correct_index: 0,
    explanation: "La langue du caméléon peut dépasser la longueur totale de son corps, et se déploie en une fraction de seconde pour capturer ses proies.",
    svg_config: null,
  },
  {
    difficulty: 3, category: "geo-insolite", type: "text", time_limit: 15,
    text: "Quel pays compte le plus grand nombre d'îles au monde ?",
    choices: ["L'Indonésie", "La Suède", "Les Philippines", "Le Canada"],
    correct_index: 1,
    explanation: "Avec plus de 260 000 îles recensées, la Suède possède le plus grand nombre d'îles de tous les pays, même si la plupart sont inhabitées.",
    svg_config: null,
  },
  {
    difficulty: 3, category: "anecdote", type: "text", time_limit: 15,
    text: "Quelle est la vitesse approximative d'un éternuement ?",
    choices: ["Environ 20 km/h", "Environ 60 km/h", "Environ 160 km/h", "Environ 500 km/h"],
    correct_index: 2,
    explanation: "L'air et les gouttelettes expulsés lors d'un éternuement peuvent atteindre environ 160 km/h.",
    svg_config: null,
  },

  // ===== Difficulté 4 — time_limit 20 =====
  {
    difficulty: 4, category: "nature-insolite", type: "text", time_limit: 20,
    text: "Quel animal possède des empreintes presque identiques à celles de l'humain au point de tromper la police ?",
    choices: ["Le gorille", "Le koala", "Le chimpanzé", "L'orang-outan"],
    correct_index: 1,
    explanation: "Les empreintes digitales du koala sont si semblables aux nôtres qu'elles peuvent être confondues avec des empreintes humaines à l'œil nu.",
    svg_config: null,
  },
  {
    difficulty: 4, category: "geo-insolite", type: "text", time_limit: 20,
    text: "Quelle capitale est la plus haute du monde en altitude ?",
    choices: ["Quito (Équateur)", "La Paz (Bolivie)", "Bogota (Colombie)", "Lhassa (Tibet)"],
    correct_index: 1,
    explanation: "La Paz, siège du gouvernement bolivien, culmine à environ 3640 m, ce qui en fait la capitale la plus haute du monde.",
    svg_config: null,
  },
  {
    difficulty: 4, category: "histoire-insolite", type: "text", time_limit: 20,
    text: "Quel objet du quotidien fut d'abord vendu comme médicament avant de devenir une boisson ?",
    choices: ["Le café", "Le Coca-Cola", "Le thé", "La limonade"],
    correct_index: 1,
    explanation: "Le Coca-Cola fut inventé en 1886 par un pharmacien et vendu comme tonique médicinal censé soigner divers maux.",
    svg_config: null,
  },
  {
    difficulty: 4, category: "anecdote", type: "text", time_limit: 20,
    text: "Combien de litres de salive un humain produit-il en moyenne au cours de sa vie ?",
    choices: ["Environ 500 litres", "Environ 5 000 litres", "Environ 25 000 litres", "Environ 100 000 litres"],
    correct_index: 2,
    explanation: "Un humain produit en moyenne entre 0,5 et 1,5 litre de salive par jour, soit assez pour remplir plusieurs piscines au cours d'une vie.",
    svg_config: null,
  },
  {
    difficulty: 4, category: "nature-insolite", type: "text", time_limit: 20,
    text: "Quel animal a le sommeil le plus court, ne dormant qu'environ deux heures par jour ?",
    choices: ["Le cheval", "La girafe", "Le lion", "L'éléphant"],
    correct_index: 1,
    explanation: "À l'état sauvage, la girafe ne dort qu'environ deux heures par jour, souvent par courtes siestes debout.",
    svg_config: null,
  },
  {
    difficulty: 4, category: "record", type: "text", time_limit: 20,
    text: "Quel est l'élément chimique le plus abondant dans l'univers ?",
    choices: ["L'oxygène", "L'hydrogène", "Le carbone", "L'hélium"],
    correct_index: 1,
    explanation: "L'hydrogène, l'atome le plus simple, représente environ 75 % de la matière ordinaire de l'univers.",
    svg_config: null,
  },
  {
    difficulty: 4, category: "geo-insolite", type: "text", time_limit: 20,
    text: "Quel pays a deux capitales officielles distinctes pour des raisons stratégiques ?",
    choices: ["L'Afrique du Sud", "Le Brésil", "L'Australie", "Le Canada"],
    correct_index: 0,
    explanation: "L'Afrique du Sud a même trois capitales : Pretoria (exécutif), Le Cap (législatif) et Bloemfontein (judiciaire).",
    svg_config: null,
  },
  {
    difficulty: 4, category: "nature-insolite", type: "text", time_limit: 20,
    text: "Quel animal possède trois paupières par œil ?",
    choices: ["Le chameau", "Le hibou", "Le crocodile", "Le faucon"],
    correct_index: 0,
    explanation: "Le chameau a une troisième paupière transparente qui protège ses yeux du sable tout en lui permettant de voir.",
    svg_config: null,
  },
  {
    difficulty: 4, category: "histoire-insolite", type: "text", time_limit: 20,
    text: "Quelle célèbre tour devait n'être qu'une structure temporaire avant d'être conservée ?",
    choices: ["Big Ben", "La tour Eiffel", "La tour de Pise", "La tour de Londres"],
    correct_index: 1,
    explanation: "La tour Eiffel, construite pour l'Exposition de 1889, devait être démontée au bout de 20 ans, mais son utilité comme antenne radio l'a sauvée.",
    svg_config: null,
  },
  {
    difficulty: 4, category: "anecdote", type: "text", time_limit: 20,
    text: "Quel est l'unique mammifère capable de voler réellement (et non de planer) ?",
    choices: ["L'écureuil volant", "La chauve-souris", "Le lémurien volant", "Le pétaure"],
    correct_index: 1,
    explanation: "La chauve-souris est le seul mammifère doté d'un vol battu véritable ; les autres animaux dits volants ne font que planer.",
    svg_config: null,
  },

  // ===== Difficulté 5 — time_limit 20 =====
  {
    difficulty: 5, category: "nature-insolite", type: "text", time_limit: 20,
    text: "Quel animal a un cerveau réparti en partie dans ses bras, qui peuvent agir indépendamment ?",
    choices: ["La méduse", "La pieuvre", "L'étoile de mer", "Le crabe"],
    correct_index: 1,
    explanation: "Environ les deux tiers des neurones de la pieuvre se trouvent dans ses bras, qui peuvent réagir et goûter sans ordre du cerveau central.",
    svg_config: null,
  },
  {
    difficulty: 5, category: "geo-insolite", type: "text", time_limit: 20,
    text: "Quelle mer n'a aucune côte et est délimitée uniquement par des courants océaniques ?",
    choices: ["La mer des Sargasses", "La mer Morte", "La mer de Corail", "La mer Caspienne"],
    correct_index: 0,
    explanation: "La mer des Sargasses, dans l'Atlantique Nord, est la seule mer sans côte : ses limites sont définies par des courants marins.",
    svg_config: null,
  },
  {
    difficulty: 5, category: "histoire-insolite", type: "text", time_limit: 20,
    text: "Quel ancien peuple utilisait l'urine comme bain de bouche et dentifrice ?",
    choices: ["Les Grecs", "Les Romains", "Les Égyptiens", "Les Vikings"],
    correct_index: 1,
    explanation: "Les Romains utilisaient l'urine, riche en ammoniaque, comme agent blanchissant pour les dents et le nettoyage des toges.",
    svg_config: null,
  },
  {
    difficulty: 5, category: "anecdote", type: "text", time_limit: 20,
    text: "Combien de bactéries vivent en moyenne dans la bouche humaine ?",
    choices: ["Des milliers", "Des millions", "Des centaines de millions", "Des milliards"],
    correct_index: 3,
    explanation: "La bouche humaine abrite plusieurs milliards de bactéries appartenant à des centaines d'espèces différentes.",
    svg_config: null,
  },
  {
    difficulty: 5, category: "nature-insolite", type: "text", time_limit: 20,
    text: "Quel animal peut survivre dans l'espace, exposé au vide et aux radiations ?",
    choices: ["Le cafard", "Le tardigrade", "La fourmi", "Le scorpion"],
    correct_index: 1,
    explanation: "Le tardigrade, microscopique, peut entrer en cryptobiose et survivre au vide spatial, aux radiations et à des températures extrêmes.",
    svg_config: null,
  },
  {
    difficulty: 5, category: "record", type: "text", time_limit: 20,
    text: "Quel est l'objet fabriqué par l'homme le plus éloigné de la Terre ?",
    choices: ["Hubble", "La sonde Voyager 1", "La sonde Cassini", "L'ISS"],
    correct_index: 1,
    explanation: "Lancée en 1977, Voyager 1 a quitté le système solaire et se trouve à plus de 24 milliards de km de la Terre, l'objet humain le plus lointain.",
    svg_config: null,
  },
  {
    difficulty: 5, category: "geo-insolite", type: "text", time_limit: 20,
    text: "Quel pays s'étend à la fois sur l'Europe et l'Asie, avec sa plus grande ville à cheval sur les deux continents ?",
    choices: ["La Grèce", "La Turquie", "L'Italie", "Le Liban"],
    correct_index: 1,
    explanation: "Istanbul est l'une des rares grandes villes au monde située sur deux continents : le détroit du Bosphore y sépare la partie européenne de la partie asiatique de la Turquie.",
    svg_config: null,
  },
  {
    difficulty: 5, category: "anecdote", type: "text", time_limit: 20,
    text: "Quelle est la couleur du Soleil vu de l'espace, hors atmosphère ?",
    choices: ["Jaune", "Blanc", "Orange", "Rouge"],
    correct_index: 1,
    explanation: "Le Soleil émet de la lumière de toutes les couleurs et apparaît blanc hors atmosphère ; il nous semble jaune car l'atmosphère diffuse le bleu.",
    svg_config: null,
  },
  {
    difficulty: 5, category: "nature-insolite", type: "text", time_limit: 20,
    text: "Quel animal possède un venin parmi les plus puissants du monde tout en étant une simple méduse ?",
    choices: ["La méduse-boîte (cuboméduse)", "La méduse lune", "La galère portugaise", "La méduse pélagique"],
    correct_index: 0,
    explanation: "La méduse-boîte d'Australie figure parmi les animaux les plus venimeux : son venin peut provoquer un arrêt cardiaque en quelques minutes.",
    svg_config: null,
  },
  {
    difficulty: 5, category: "histoire-insolite", type: "text", time_limit: 20,
    text: "Quel pharaon a vu sa momie recevoir un véritable passeport pour voyager vers la France en 1976 ?",
    choices: ["Toutânkhamon", "Ramsès II", "Khéops", "Akhenaton"],
    correct_index: 1,
    explanation: "Pour être transportée en France et restaurée, la momie de Ramsès II a reçu un passeport officiel où sa profession était indiquée comme « roi (décédé) ».",
    svg_config: null,
  },

  // ===== Difficulté 6 — time_limit 20 =====
  {
    difficulty: 6, category: "nature-insolite", type: "text", time_limit: 20,
    text: "Quel mammifère pond des œufs tout en allaitant ses petits ?",
    choices: ["Le pangolin", "L'ornithorynque", "Le paresseux", "Le tamanoir"],
    correct_index: 1,
    explanation: "L'ornithorynque est un monotrème : il pond des œufs, possède un bec de canard et est l'un des rares mammifères venimeux.",
    svg_config: null,
  },
  {
    difficulty: 6, category: "geo-insolite", type: "text", time_limit: 20,
    text: "Dans quel pays se trouve le point continental le plus éloigné de tout océan, surnommé le pôle d'inaccessibilité ?",
    choices: ["La Mongolie", "La Chine", "Le Kazakhstan", "La Russie"],
    correct_index: 1,
    explanation: "Le point eurasien le plus éloigné de tout océan se situe dans le nord-ouest de la Chine, à environ 2500 km des côtes les plus proches.",
    svg_config: null,
  },
  {
    difficulty: 6, category: "histoire-insolite", type: "text", time_limit: 20,
    text: "Quelle invention courante doit son nom à une marque devenue nom commun, à l'origine destinée à isoler le son ?",
    choices: ["Le Frigidaire", "Le Frisbee", "Le Klaxon", "Le Sopalin"],
    correct_index: 2,
    explanation: "Klaxon était une marque d'avertisseurs sonores du début du XXe siècle, devenue le nom commun de l'objet en français.",
    svg_config: null,
  },
  {
    difficulty: 6, category: "anecdote", type: "text", time_limit: 20,
    text: "Quel pourcentage de l'ADN humain partageons-nous environ avec la banane ?",
    choices: ["Environ 1 %", "Environ 25 %", "Environ 50 %", "Environ 90 %"],
    correct_index: 2,
    explanation: "Humains et bananes partagent environ 50 % de leurs gènes, car de nombreux mécanismes cellulaires de base sont communs à tout le vivant.",
    svg_config: null,
  },
  {
    difficulty: 6, category: "nature-insolite", type: "text", time_limit: 20,
    text: "Quel animal a la morsure la plus puissante au monde mesurée à ce jour ?",
    choices: ["Le grand requin blanc", "Le crocodile marin", "Le lion", "L'hippopotame"],
    correct_index: 1,
    explanation: "Le crocodile marin détient la morsure mesurée la plus puissante du règne animal, avec une force de plusieurs milliers de newtons.",
    svg_config: null,
  },
  {
    difficulty: 6, category: "record", type: "text", time_limit: 20,
    text: "Quelle est la substance naturelle la plus dure connue, formée dans des étoiles à neutrons ou diamants ?",
    choices: ["Le graphène", "Le diamant", "Le titane", "Le quartz"],
    correct_index: 1,
    explanation: "Parmi les matériaux naturels, le diamant reste le plus dur connu sur l'échelle de Mohs, où il atteint la note maximale de 10.",
    svg_config: null,
  },
  {
    difficulty: 6, category: "geo-insolite", type: "text", time_limit: 20,
    text: "Quel lac contient environ 20 % de l'eau douce liquide non gelée de la planète ?",
    choices: ["Le lac Supérieur", "Le lac Baïkal", "Le lac Victoria", "La mer Caspienne"],
    correct_index: 1,
    explanation: "Le lac Baïkal, en Sibérie, est le plus profond du monde et contient à lui seul environ un cinquième de l'eau douce liquide de surface.",
    svg_config: null,
  },
  {
    difficulty: 6, category: "anecdote", type: "text", time_limit: 20,
    text: "Combien de temps faut-il à la lumière du Soleil pour atteindre la Terre ?",
    choices: ["Environ 8 secondes", "Environ 8 minutes", "Environ 8 heures", "Instantanément"],
    correct_index: 1,
    explanation: "La lumière met environ 8 minutes et 20 secondes pour parcourir les 150 millions de km qui nous séparent du Soleil.",
    svg_config: null,
  },
  {
    difficulty: 6, category: "nature-insolite", type: "text", time_limit: 20,
    text: "Quel arbre est considéré comme le plus vieil organisme vivant individuel connu, âgé de près de 5000 ans ?",
    choices: ["Le séquoia géant", "Le pin de Bristlecone", "Le baobab", "Le chêne"],
    correct_index: 1,
    explanation: "Un pin de Bristlecone des montagnes de Californie, surnommé Mathusalem, est âgé d'environ 4850 ans.",
    svg_config: null,
  },
  {
    difficulty: 6, category: "histoire-insolite", type: "text", time_limit: 20,
    text: "Quelle découverte a été faite par accident en laissant traîner une boîte de Petri contaminée par une moisissure ?",
    choices: ["L'aspirine", "La pénicilline", "Le vaccin contre la rage", "L'insuline"],
    correct_index: 1,
    explanation: "En 1928, Alexander Fleming découvrit la pénicilline en remarquant qu'une moisissure tuait les bactéries dans une boîte oubliée.",
    svg_config: null,
  },

  // ===== Difficulté 7 — time_limit 25 =====
  {
    difficulty: 7, category: "nature-insolite", type: "text", time_limit: 25,
    text: "Quelle espèce de méduse est considérée comme biologiquement « immortelle » car elle peut rajeunir ?",
    choices: ["Turritopsis dohrnii", "Aurelia aurita", "Chrysaora", "Pelagia noctiluca"],
    correct_index: 0,
    explanation: "Turritopsis dohrnii peut, face au stress, revenir à son stade de polype et recommencer son cycle de vie, échappant ainsi à la mort par vieillissement.",
    svg_config: null,
  },
  {
    difficulty: 7, category: "geo-insolite", type: "text", time_limit: 25,
    text: "Quel pays a déménagé administrativement de fuseau horaire pour rester à l'heure d'un voisin commercial, créant un saut de calendrier ?",
    choices: ["Les Samoa", "Les Tonga", "Les Fidji", "Kiribati"],
    correct_index: 0,
    explanation: "En 2011, les Samoa ont sauté le 30 décembre pour passer de l'est à l'ouest de la ligne de changement de date et s'aligner sur l'Australie et la Nouvelle-Zélande.",
    svg_config: null,
  },
  {
    difficulty: 7, category: "histoire-insolite", type: "text", time_limit: 25,
    text: "Quel empereur romain aurait nommé son cheval Incitatus à de hautes fonctions, selon la légende ?",
    choices: ["Néron", "Caligula", "Commode", "Tibère"],
    correct_index: 1,
    explanation: "Selon les récits antiques, Caligula adorait tant son cheval Incitatus qu'il aurait envisagé de le faire consul, symbole de sa folie supposée.",
    svg_config: null,
  },
  {
    difficulty: 7, category: "anecdote", type: "text", time_limit: 25,
    text: "Quelle est la seule partie du corps humain dépourvue d'apport sanguin et nourrie par diffusion ?",
    choices: ["Les ongles", "La cornée de l'œil", "Les cheveux", "L'émail dentaire"],
    correct_index: 1,
    explanation: "La cornée ne contient aucun vaisseau sanguin pour rester transparente ; elle reçoit oxygène et nutriments directement de l'air et des larmes.",
    svg_config: null,
  },
  {
    difficulty: 7, category: "nature-insolite", type: "text", time_limit: 25,
    text: "Quel animal possède un cerveau en forme d'anneau autour de son œsophage, traversé par la nourriture qu'il avale ?",
    choices: ["L'oursin", "La sangsue et de nombreux invertébrés", "La grenouille", "La tortue"],
    correct_index: 1,
    explanation: "Chez de nombreux invertébrés comme les annélides, le cerveau forme un anneau (collier péri-œsophagien) qui entoure le tube digestif, lequel le traverse littéralement.",
    svg_config: null,
  },
  {
    difficulty: 7, category: "record", type: "text", time_limit: 25,
    text: "Quel est l'endroit habité de façon permanente le plus froid de la planète, avec des températures hivernales sous -60 °C ?",
    choices: ["Verkhoïansk (Russie)", "Vostok (Antarctique)", "Norilsk (Russie)", "Iqaluit (Canada)"],
    correct_index: 0,
    explanation: "Oïmiakon et Verkhoïansk, en Sibérie, sont les localités habitées en permanence les plus froides, avec des records proches de -68 °C.",
    svg_config: null,
  },
  {
    difficulty: 7, category: "geo-insolite", type: "text", time_limit: 25,
    text: "Quel détroit relie l'Asie et l'Amérique du Nord, séparées par moins de 90 km ?",
    choices: ["Le détroit de Magellan", "Le détroit de Béring", "Le détroit de Gibraltar", "Le détroit de Malacca"],
    correct_index: 1,
    explanation: "Le détroit de Béring sépare la Russie et l'Alaska d'à peine 88 km, avec deux îles distantes de seulement 4 km appartenant chacune à un pays.",
    svg_config: null,
  },
  {
    difficulty: 7, category: "anecdote", type: "text", time_limit: 25,
    text: "Quel phénomène fait que les astronautes grandissent temporairement de quelques centimètres dans l'espace ?",
    choices: ["La déshydratation", "L'absence de gravité décompressant la colonne", "La perte musculaire", "La pression de la combinaison"],
    correct_index: 1,
    explanation: "En apesanteur, les disques de la colonne vertébrale se détendent : les astronautes peuvent gagner jusqu'à 5 cm avant de retrouver leur taille sur Terre.",
    svg_config: null,
  },
  {
    difficulty: 7, category: "nature-insolite", type: "text", time_limit: 25,
    text: "Quel animal produit un lait rose pour nourrir ses petits ?",
    choices: ["Le flamant rose", "Le dauphin", "L'hippopotame", "L'éléphant"],
    correct_index: 2,
    explanation: "L'hippopotame sécrète une substance protectrice rougeâtre qui, mêlée à son lait, peut lui donner une teinte rosée.",
    svg_config: null,
  },
  {
    difficulty: 7, category: "histoire-insolite", type: "text", time_limit: 25,
    text: "Quelle université a été fondée avant l'existence de l'empire aztèque, étant l'une des plus anciennes en activité continue ?",
    choices: ["Oxford", "L'université d'Al Quaraouiyine (Fès)", "La Sorbonne", "Bologne"],
    correct_index: 1,
    explanation: "Fondée en 859 au Maroc, Al Quaraouiyine est reconnue comme la plus ancienne université encore en activité au monde.",
    svg_config: null,
  },

  // ===== Difficulté 8 — time_limit 25 =====
  {
    difficulty: 8, category: "nature-insolite", type: "text", time_limit: 25,
    text: "Quel animal possède le génome le plus complexe connu, avec bien plus de paires de bases que l'humain ?",
    choices: ["L'éléphant", "Certaines amibes (Polychaos dubium)", "La baleine bleue", "Le crocodile"],
    correct_index: 1,
    explanation: "L'amibe Polychaos dubium aurait un génome environ 200 fois plus grand que celui de l'humain, illustrant le « paradoxe de la valeur C ».",
    svg_config: null,
  },
  {
    difficulty: 8, category: "geo-insolite", type: "text", time_limit: 25,
    text: "Quel pays possède une frontière terrestre avec un seul autre pays, qui l'entoure complètement, mis à part le Vatican ?",
    choices: ["Le Lesotho", "Monaco", "Le Liechtenstein", "Andorre"],
    correct_index: 0,
    explanation: "Le Lesotho est entièrement enclavé dans l'Afrique du Sud ; avec Saint-Marin et le Vatican, il est l'un des trois pays au monde totalement entourés par un seul État.",
    svg_config: null,
  },
  {
    difficulty: 8, category: "histoire-insolite", type: "text", time_limit: 25,
    text: "Quelle ville antique a connu une « danse de la peste » en 1518, où des dizaines de personnes dansèrent sans pouvoir s'arrêter ?",
    choices: ["Strasbourg", "Florence", "Cologne", "Lyon"],
    correct_index: 0,
    explanation: "En 1518 à Strasbourg, l'« épidémie dansante » poussa des centaines d'habitants à danser durant des jours, certains jusqu'à l'épuisement mortel.",
    svg_config: null,
  },
  {
    difficulty: 8, category: "anecdote", type: "text", time_limit: 25,
    text: "Quel est le seul nombre dont le nom en français comporte autant de lettres que sa valeur ?",
    choices: ["Quatre", "Cinq", "Trois", "Sept"],
    correct_index: 0,
    explanation: "Le mot « quatre » compte exactement quatre lettres : c'est le seul nombre en français à posséder cette propriété.",
    svg_config: null,
  },
  {
    difficulty: 8, category: "nature-insolite", type: "text", time_limit: 25,
    text: "Quel animal voit son cerveau diminuer puis repousser de façon saisonnière (effet Dehnel) ?",
    choices: ["La taupe", "La musaraigne", "Le hérisson", "Le campagnol"],
    correct_index: 1,
    explanation: "La musaraigne réduit la taille de son crâne et de son cerveau en hiver pour économiser de l'énergie, puis les fait repartiellement repousser au printemps.",
    svg_config: null,
  },
  {
    difficulty: 8, category: "record", type: "text", time_limit: 25,
    text: "Quel son a été le plus fort jamais enregistré dans l'histoire moderne, audible à des milliers de kilomètres ?",
    choices: ["Une éruption volcanique (Krakatoa, 1883)", "Une explosion nucléaire", "Le tonnerre", "Une fusée Saturn V"],
    correct_index: 0,
    explanation: "L'éruption du Krakatoa en 1883 produisit un son d'environ 180 dB entendu jusqu'à près de 5000 km, le bruit le plus fort de l'ère moderne.",
    svg_config: null,
  },
  {
    difficulty: 8, category: "geo-insolite", type: "text", time_limit: 25,
    text: "Quel pays est le plus plat du monde, son point culminant ne dépassant pas quelques dizaines de mètres ?",
    choices: ["Les Pays-Bas", "Les Maldives", "Le Danemark", "Le Bangladesh"],
    correct_index: 1,
    explanation: "Aux Maldives, le point le plus élevé du pays ne dépasse pas environ 2,4 m, ce qui en fait le pays le plus plat et le plus menacé par la montée des eaux.",
    svg_config: null,
  },
  {
    difficulty: 8, category: "anecdote", type: "text", time_limit: 25,
    text: "Combien de temps a duré le plus long hoquet documenté chez un humain ?",
    choices: ["3 jours", "6 mois", "Plus de 60 ans", "10 ans"],
    correct_index: 2,
    explanation: "L'Américain Charles Osborne a eu le hoquet sans interruption de 1922 à 1990, soit environ 68 ans, un record reconnu.",
    svg_config: null,
  },
  {
    difficulty: 8, category: "nature-insolite", type: "text", time_limit: 25,
    text: "Quel oiseau peut voler à reculons grâce à un battement d'ailes unique ?",
    choices: ["Le martin-pêcheur", "Le colibri", "L'hirondelle", "Le moineau"],
    correct_index: 1,
    explanation: "Le colibri est le seul oiseau capable de voler à reculons, grâce à un mouvement d'ailes en huit qui lui permet aussi de faire du surplace.",
    svg_config: null,
  },
  {
    difficulty: 8, category: "histoire-insolite", type: "text", time_limit: 25,
    text: "Quel produit aujourd'hui banal était si précieux à Rome qu'il aurait servi à payer une partie du salaire des soldats ?",
    choices: ["Le poivre", "Le sel", "Le sucre", "Le café"],
    correct_index: 1,
    explanation: "Le sel était essentiel à la conservation des aliments ; le mot « salaire » vient du latin salarium, lié à la ration ou à l'achat de sel des soldats romains.",
    svg_config: null,
  },

  // ===== Difficulté 9 — time_limit 30 =====
  {
    difficulty: 9, category: "nature-insolite", type: "text", time_limit: 30,
    text: "Quelle plante aquatique géante possède des feuilles assez solides pour supporter le poids d'un enfant ?",
    choices: ["Le lotus sacré", "Le Victoria amazonica", "Le nénuphar blanc", "La jacinthe d'eau"],
    correct_index: 1,
    explanation: "Les feuilles du Victoria amazonica, nénuphar géant d'Amazonie, peuvent atteindre 3 m et supporter plusieurs dizaines de kilos grâce à leur réseau de nervures.",
    svg_config: null,
  },
  {
    difficulty: 9, category: "geo-insolite", type: "text", time_limit: 30,
    text: "Quel territoire est revendiqué par aucun pays, créant une rare « terra nullius » entre l'Égypte et le Soudan ?",
    choices: ["Bir Tawil", "Le Hala'ib", "Le Cabinda", "L'Ogaden"],
    correct_index: 0,
    explanation: "Bir Tawil est une zone désertique qu'aucun des deux pays ne revendique, car le revendiquer impliquerait de renoncer à un territoire bien plus vaste et convoité.",
    svg_config: null,
  },
  {
    difficulty: 9, category: "histoire-insolite", type: "text", time_limit: 30,
    text: "Quel scientifique a eu son doigt conservé dans un musée après sa mort, exposé pointant vers le ciel ?",
    choices: ["Isaac Newton", "Galilée", "Léonard de Vinci", "Copernic"],
    correct_index: 1,
    explanation: "Un majeur de Galilée est exposé au musée Galilée de Florence, pointant vers le haut, prélevé lors du transfert de sa dépouille en 1737.",
    svg_config: null,
  },
  {
    difficulty: 9, category: "anecdote", type: "text", time_limit: 30,
    text: "Quel est le seul aliment courant dont la digestion peut consommer presque autant de calories qu'il en apporte ?",
    choices: ["La pomme", "Le céleri", "Le concombre", "La laitue"],
    correct_index: 1,
    explanation: "Très riche en eau et en fibres et très pauvre en calories, le céleri demande tant d'énergie à mâcher et digérer qu'il en apporte à peine plus qu'il n'en coûte.",
    svg_config: null,
  },
  {
    difficulty: 9, category: "nature-insolite", type: "text", time_limit: 30,
    text: "Quel animal possède des dents sur la langue, lui permettant de râper sa nourriture ?",
    choices: ["L'escargot", "Le requin", "La grenouille", "Le pic-vert"],
    correct_index: 0,
    explanation: "L'escargot possède une radula, une langue couverte de milliers de minuscules dents qui lui sert à râper feuilles et végétaux.",
    svg_config: null,
  },
  {
    difficulty: 9, category: "record", type: "text", time_limit: 30,
    text: "Quel matériau de laboratoire est si noir qu'il absorbe plus de 99,9 % de la lumière visible ?",
    choices: ["Le charbon actif", "Le Vantablack", "L'obsidienne", "Le graphite"],
    correct_index: 1,
    explanation: "Le Vantablack, fait de nanotubes de carbone, absorbe plus de 99,9 % de la lumière, donnant l'impression d'un trou noir bidimensionnel.",
    svg_config: null,
  },
  {
    difficulty: 9, category: "geo-insolite", type: "text", time_limit: 30,
    text: "Quelle capitale détient le plus long nom officiel complet au monde, comptant plus de 160 caractères ?",
    choices: ["Kuala Lumpur", "Bangkok", "Colombo", "Phnom Penh"],
    correct_index: 1,
    explanation: "Le nom cérémoniel complet de Bangkok, capitale de la Thaïlande, est le plus long nom de lieu au monde et est reconnu comme tel par le livre Guinness des records.",
    svg_config: null,
  },
  {
    difficulty: 9, category: "anecdote", type: "text", time_limit: 30,
    text: "Quel phénomène explique que l'on ne peut pas se chatouiller soi-même ?",
    choices: ["La fatigue nerveuse", "La prédiction du cervelet", "Le manque de récepteurs", "La pression sanguine"],
    correct_index: 1,
    explanation: "Le cervelet anticipe nos propres mouvements et atténue la sensation : comme l'effet de surprise disparaît, le chatouillement auto-infligé ne fonctionne pas.",
    svg_config: null,
  },
  {
    difficulty: 9, category: "nature-insolite", type: "text", time_limit: 30,
    text: "Quel animal a un cri si grave qu'une partie de sa communication est inaudible pour l'oreille humaine ?",
    choices: ["Le loup", "L'éléphant", "Le lion", "Le gorille"],
    correct_index: 1,
    explanation: "Les éléphants communiquent par infrasons, des sons trop graves pour nous, qui peuvent voyager sur plusieurs kilomètres à travers le sol.",
    svg_config: null,
  },
  {
    difficulty: 9, category: "histoire-insolite", type: "text", time_limit: 30,
    text: "Quel micro-État est resté techniquement en guerre avec l'Allemagne pendant des décennies après 1918, faute d'avoir été inclus dans un traité de paix ?",
    choices: ["Monaco", "Andorre", "Le Liechtenstein", "Saint-Marin"],
    correct_index: 1,
    explanation: "Andorre, oubliée du traité de Versailles, est restée formellement en état de guerre depuis 1914 ; la paix avec l'Allemagne n'a été officialisée qu'en 1958.",
    svg_config: null,
  },

  // ===== Difficulté 10 (ultra-pointu) — time_limit 30 =====
  {
    difficulty: 10, category: "nature-insolite", type: "text", time_limit: 30,
    text: "Quel animal possède un type de protéine antigel dans le sang lui permettant de survivre congelé puis de revivre ?",
    choices: ["Le manchot empereur", "La grenouille des bois (Rana sylvatica)", "Le phoque de Weddell", "L'ours polaire"],
    correct_index: 1,
    explanation: "La grenouille des bois peut geler jusqu'à 65 % de l'eau de son corps en hiver grâce à des cryoprotecteurs, son cœur s'arrête, puis elle dégèle vivante au printemps.",
    svg_config: null,
  },
  {
    difficulty: 10, category: "geo-insolite", type: "text", time_limit: 30,
    text: "Quel est le point le plus éloigné du centre de la Terre, surpassant l'Everest sur ce critère précis ?",
    choices: ["Le K2", "Le sommet du Chimborazo", "Le Mauna Kea", "Le Denali"],
    correct_index: 1,
    explanation: "À cause du renflement équatorial de la Terre, le sommet du volcan Chimborazo en Équateur est le point de la surface le plus éloigné du centre du globe, devant l'Everest.",
    svg_config: null,
  },
  {
    difficulty: 10, category: "histoire-insolite", type: "text", time_limit: 30,
    text: "Quel objet retrouvé dans une épave antique grecque s'est révélé être un calculateur astronomique à engrenages vieux de plus de 2000 ans ?",
    choices: ["Le mécanisme d'Anticythère", "La pile de Bagdad", "Le disque de Phaistos", "L'astrolabe de Brescia"],
    correct_index: 0,
    explanation: "Le mécanisme d'Anticythère, daté d'environ 100 av. J.-C., est un calculateur à engrenages prédisant les positions astronomiques, d'une complexité inégalée avant des siècles.",
    svg_config: null,
  },
  {
    difficulty: 10, category: "anecdote", type: "text", time_limit: 30,
    text: "Quelle est la seule lettre de l'alphabet qui ne figure dans aucun symbole chimique de la table périodique standard ?",
    choices: ["La lettre J", "La lettre Q", "La lettre X", "La lettre W"],
    correct_index: 0,
    explanation: "La lettre J n'apparaît dans aucun symbole d'élément de la table périodique standard, contrairement à toutes les autres lettres.",
    svg_config: null,
  },
  {
    difficulty: 10, category: "nature-insolite", type: "text", time_limit: 30,
    text: "Quel champignon est considéré comme le plus grand organisme vivant connu sur Terre par sa superficie ?",
    choices: ["L'amanite", "Armillaria ostoyae (Oregon)", "Le cèpe", "Le pied bleu"],
    correct_index: 1,
    explanation: "Un Armillaria ostoyae de l'Oregon s'étend sur près de 9 km² sous terre et est âgé de milliers d'années, ce qui en fait le plus grand organisme vivant connu.",
    svg_config: null,
  },
  {
    difficulty: 10, category: "record", type: "text", time_limit: 30,
    text: "Quel métal présent dans une pièce de monnaie était autrefois plus précieux que l'or, au point de couronner le sommet du Washington Monument ?",
    choices: ["Le platine", "L'aluminium", "Le palladium", "Le titane"],
    correct_index: 1,
    explanation: "Avant qu'on sache le produire en masse, l'aluminium valait plus que l'or ; le sommet du Washington Monument fut coiffé d'aluminium en 1884 comme symbole de luxe.",
    svg_config: null,
  },
  {
    difficulty: 10, category: "geo-insolite", type: "text", time_limit: 30,
    text: "Quel pays possède une enclave dans une enclave dans une enclave, configuration territoriale unique aujourd'hui disparue ?",
    choices: ["L'Inde et le Bangladesh (Dahala Khagrabari)", "La Belgique et les Pays-Bas", "L'Espagne et le Maroc", "La Suisse et l'Allemagne"],
    correct_index: 0,
    explanation: "Jusqu'en 2015, Dahala Khagrabari était un champ indien entouré de territoire bangladais, lui-même dans une enclave indienne en territoire bangladais : le seul contre-enclave de 3e ordre au monde.",
    svg_config: null,
  },
  {
    difficulty: 10, category: "anecdote", type: "text", time_limit: 30,
    text: "Quel phénomène quantique fait qu'une partie de votre corps « traverse » techniquement de minuscules barrières en permanence ?",
    choices: ["La superposition", "L'effet tunnel", "L'intrication", "La décohérence"],
    correct_index: 1,
    explanation: "L'effet tunnel permet à des particules de franchir des barrières d'énergie qu'elles ne devraient pas pouvoir passer ; il est notamment essentiel aux réactions de fusion dans le Soleil.",
    svg_config: null,
  },
  {
    difficulty: 10, category: "nature-insolite", type: "text", time_limit: 30,
    text: "Quel crustacé possède la vision la plus complexe connue, avec jusqu'à 16 types de photorécepteurs ?",
    choices: ["Le homard", "La crevette-mante (squille)", "Le crabe royal", "La langoustine"],
    correct_index: 1,
    explanation: "La crevette-mante a jusqu'à 16 types de photorécepteurs (contre 3 chez l'humain) et perçoit la lumière polarisée, lui offrant une vision unique au monde.",
    svg_config: null,
  },
  {
    difficulty: 10, category: "histoire-insolite", type: "text", time_limit: 30,
    text: "Quel élément du tableau périodique a été nommé d'après un petit village de Suède, qui a donné son nom à quatre éléments différents ?",
    choices: ["Strontium", "Yttrium", "Scandium", "Hafnium"],
    correct_index: 1,
    explanation: "Le village d'Ytterby, en Suède, a donné son nom à quatre éléments (yttrium, ytterbium, terbium, erbium), un record absolu pour un lieu unique.",
    svg_config: null,
  },
];
